### ISSUE TITLE
Error: listen EADDRNOTAVAIL <IP_ADDR>:8545

### ISSUE THREAD

**Issue by kggp1995** [trufflesuite/ganache#101]
## Description

Can't connect Ganache to remote geth clients via RPC. Following error is observed
```
Error: listen EADDRNOTAVAIL <CUSTOM_IP_ADDR/DNS>:8545
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```
## Steps to reproduce

- Replaced the target URL in the ganache app settings to a custom IP/DNS in the first run.
- Make sure the RPC target is up and running :sweat_smile: 

# Versions

- Platform: Linux
- Node: v8.9.1
- Npm: 5.5.1

Keep up the great work!

**Comment by tcoulter** [comment]
Hi there. 

Ganache isn't intended to connect to a geth server. Instead, it's intended to start _its own_ server at the host and port you provide. By specifying a host/port on a remote computer, you're essentially asking Ganache to start a server on a remote computer, which it obviously can't do. 

Your host option should be some form of `localhost`, `127.0.0.1`, etc. We'll make this more clear in the settings. Thanks!

**Comment by ChaiBapchya** [comment]
a. Can ganache now be connected to a docker container on EC2?
b. Can ganache be used for connecting to existing blockchain and just use the feature of account management, contract deployment, etc
c. Fact that only localhost or 127.0.0.1 can be used is not made clear in settings. 
on GUI it simply has a textbox for IP, PORT and NETWORK (making me thing I can connect to my EC2 based blockchain)
on CLI i run the ganache-cli command to connect and it just ends (no error)

Hope you work on these issues.

**Comment by seesemichaelj** [comment]
Thanks @chaibapchya for bringing up these questions!

a. It still cannot and there currently isn't any plan to add this support.
b. Similar to (a) but slightly different; it still doesn't support this however.
c. We're adding a dropdown for Hostname to limit what users input to help clarify this in #666
d. (The cli issue) Glad you brought this up! Could you specify what the arguments are for your cli? Are you trying to use both Ganache UI and CLI on the same port?

**Comment by ChaiBapchya** [comment]
Yes I was trying to connect Ganache CLI to the existing ethereum blockchain on EC2.
Regardless of the wrong query, an error indicating the same would be really helpful.

Despite entering any of the following commands
```
ganache-cli -h a.b.c.d -p 8545
```
```
ganache-cli -h a.b.c.d -p 8545 -i 1234
```
```
ganache-cli -h a.b.c.d -p 8545 -i 1234 --debug
```
I get the same generic message
```
Network:
  -p, --port              port to bind to                        [default: 8545]
  -h, --host, -?, --help  Show help             [boolean] [default: "127.0.0.1"]

Accounts:
  -a, --accounts             number of accounts to generate at startup
                                                          [number] [default: 10]
  -e, --defaultBalanceEther  Amount of ether to assign each test account
                                                         [number] [default: 100]
  --account                  Account data in the form
                             '<private_key>,<initial_balance>', can be specified
                             multiple times. Note that private keys are 64
                             characters long and must be entered as an
                             0x-prefixed hex string. Balance can either be input
                             as an integer, or as a 0x-prefixed hex string with
                             either form specifying the initial balance in wei.
                                                                         [array]
  --acctKeys                 saves generated accounts and private keys as JSON
                             object in specified file                   [string]
  -n, --secure               Lock accounts by default [boolean] [default: false]
  --unlock                   Comma-separated list of accounts or indices to
                             unlock

Chain:
  -f, --fork                 URL and block number of another currently running
                             Ethereum client from which this client should fork.
                             Example: 'http://127.0.0.1:9545@12345'
  --db                       directory to save chain db                 [string]
  -s, --seed                 seed value for PRNG
                                 [default: Random value, unless -d is specified]
  -d, --deterministic        uses fixed (hardcoded) seed for identical results
                             from run-to-run          [boolean] [default: false]
  -m, --mnemonic             bip39 mnemonic phrase for generating a PRNG seed,
                             which is in turn used for hierarchical
                             deterministic (HD) account generation
  --noVMErrorsOnRPCResponse  Do not transmit transaction failures as RPC errors.
                             Enable this flag for error reporting behaviour
                             which is compatible with other clients such as geth
                             and Parity.              [boolean] [default: false]
  -b, --blockTime            Block time in seconds. Will instamine if option
                             omitted. Avoid using unless your test cases require
                             a specific mining interval.
  -i, --networkId            Network ID to be returned by 'net_version'.
                               [number] [default: System time at process start.]
  -g, --gasPrice             The price of gas in wei
                                                 [number] [default: 20000000000]
  -l, --gasLimit             The block gas limit     [number] [default: 6721975]

Other:
  --debug    Output VM opcodes for debugging          [boolean] [default: false]
  --verbose  Log all requests and responses to stdout [boolean] [default: false]
  --mem      Only show memory output, not tx history  [boolean] [default: false]

Options:
  --version  Show version number                                       [boolean]
```
Something more descriptive or understandable would be helpful.
Otherwise, people would have to come to this issue (after an hour of searching and trouble-shooting on client-side unnecessarily) to know that they can't do this.

**Comment by ChaiBapchya** [comment]
Moreover, this is in direct contradiction to what we read on the official page
[Ganache](http://truffleframework.com/docs/ganache/using)
> The Server page shows details about the network connection, including hostname, port, network ID, and whether to automatically mine each transaction into a block.

**Comment by seesemichaelj** [comment]
Great notes/feedback!

As far as the notes on the docs page, the hostname is similar to when you start a binding server port, traditionally the first argument is `host`. I totally agree this can be confusing, and I'll look into incorporating your feedback.

On a separate note, can I ask why you're trying to connect to the EC2 instance to help us understand? I can understand why you may want to use the UI, but Ganache CLI essentially is creating a blockchain RPC node which your EC2 already has.

Thanks again!

**Comment by ChaiBapchya** [comment]
I thought CLI allows all the capabilities than UI allows and somehow I thought Ganache can be used to connect to existing blockchain rather than create a new one again.

**Comment by seesemichaelj** [comment]
Great, thanks again.

You can see steps on #666 on how to get your Ganache UI configured to an appropriate IP since it currently won't let you change the settings when it fails on startup.

**Comment by seesemichaelj** [comment]
Hey @ChaiBapchya, just a heads up: the generic message stuff in ganache-cli is due to this bug/pr: https://github.com/trufflesuite/ganache-cli/pull/539

**Comment by kggp1995** [comment]
Hi @benjamincburns - as discussed during the ConsenSys India Meetups, could you please share the plans for allowing the Ganache UI to connect with remote ganache-cli instances?

Thanks.
