### ISSUE TITLE
return value of  msg.sender  was wrong when listening the contract's event

### ISSUE THREAD

**Issue by yuwiggin** [trufflesuite/ganache#1011]
I created a WebsocketProvider with 
```
let web3 = new Web3(new Web3.providers.WebsocketProvider('ws://localhost:8545'))
```
 to listen contract's event, but the return value of  `msg.sender` was wrong. 

Any suggestion?

Ganache CLI v6.3.0 (ganache-core: 2.4.0)
Node: 8.11.3
Truffle v5.0.3

**Comment by davidmurdoch** [comment]
Closing this one as I've confirmed that the code works as expected in v7.0.4.
