### ISSUE TITLE
Corrupted signature or message sometimes leads to invalid nonce error

### ISSUE THREAD

**Issue by webmaster128** [trufflesuite/ganache#1013]
How to reproduce:

1. Start a new instance of ganache-cli (v6.2.5/docker)
2. Use account `A` from the auto-generated accounts with funds 
3. Send some valid transactions to the blockchain
4. Query latest nonce, send an ETH send transaction with (a) corrupted signature or (b) corrupted data field

Instead of a "invalid signature" message this leads to:

```json
{
  "code": -32000,
  "message": "the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 14",
  "data": {
    "stack": "n: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 14\n    at i (/app/ganache-core.docker.cli.js:37:300962)\n    at blockchain.getQueuedNonce (/app/ganache-core.docker.cli.js:37:301093)\n    at /app/ganache-core.docker.cli.js:25:150975\n    at /app/ganache-core.docker.cli.js:37:630596\n    at /app/ganache-core.docker.cli.js:37:634357\n    at Object.return (/app/ganache-core.docker.cli.js:37:633934)\n    at /app/ganache-core.docker.cli.js:37:632186\n    at e (/app/ganache-core.docker.cli.js:37:634305)\n    at /app/ganache-core.docker.cli.js:37:634316\n    at /app/ganache-core.docker.cli.js:37:631398\n    at process._tickCallback (internal/process/next_tick.js:61:11)",
    "name": "n"
  }
}
```

However, there is probably a race condition involved since sometimes instead I get

```
{
  "code": -32000,
  "message": "Invalid Signature",
  "data": {
    "stack": "Error: Invalid Signature\n    at e.getSenderPublicKey (/app/ganache-core.docker.cli.js:10:88137)\n    at e.getSenderAddress (/app/ganache-core.docker.cli.js:10:87941)\n    at A.queueRawTransaction (/app/ganache-core.docker.cli.js:37:292154)\n    at u.eth_sendRawTransaction (/app/ganache-core.docker.cli.js:37:283039)\n    at u.handleRequest (/app/ganache-core.docker.cli.js:37:280006)\n    at t (/app/ganache-core.docker.cli.js:37:143367)\n    at a.handleRequest (/app/ganache-core.docker.cli.js:37:278371)\n    at t (/app/ganache-core.docker.cli.js:37:143367)\n    at s.f.handleRequest (/app/ganache-core.docker.cli.js:37:271502)\n    at s.handleRequest (/app/ganache-core.docker.cli.js:37:269329)\n    at t (/app/ganache-core.docker.cli.js:37:143367)\n    at c.handleRequest (/app/ganache-core.docker.cli.js:37:277385)\n    at t (/app/ganache-core.docker.cli.js:37:143367)\n    at a.handleRequest (/app/ganache-core.docker.cli.js:37:276832)\n    at t (/app/ganache-core.docker.cli.js:37:143367)\n    at d._handleAsync (/app/ganache-core.docker.cli.js:37:143403)\n    at Timeout._onTimeout (/app/ganache-core.docker.cli.js:37:142828)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)",
    "name": "Error"
  }
}
```

The ratio _incorrect nonce_ to _invalid signature_ is about half half.

I suspect the following: the sender is calculated from signature+message via the secp256k1 public key recovery algorithm. Now before the signature is checked for validity, the nonce is compared to the nonce of a wrong account `B != A`.

On Rinkeby I observe the same problem. They just report `{"code":-32000,"message":"invalid sender"}` which is a little bit less confusing but still not great.

**Comment by loekTheDreamer** [comment]
I am getting the same error but my transaction still completes in ganache
```
const sendEths = async () => {
    const provider = new ethers.providers.JsonRpcProvider(localUrl);

    const txCount = await provider.getTransactionCount(senderAccount);
    // build the transaction
    const tx = new Tx({
      nonce: ethers.utils.hexlify(txCount),
      gasPrice: '0x4a817c800',
      gasLimit: '0x5208',
      to: receiverAccount,
      value: '0x1158e460913d00000'
    });

    // sign the transaction
    tx.sign(Buffer.from(privateKey, 'hex'));

    // send the transaction
    try {
      const response = await provider.sendTransaction(
        '0x' + tx.serialize().toString('hex')
      );
      const done = await provider.waitForTransaction(response.hash);
      console.log(done);
    } catch (err) {
      console.log('what is the error', err);
    }
  }; 
```

I don't understand what @webmaster128 means about the corrupted signature. is this issue with submitting the wrong information in the raw transaction? Can anyone please tell me what I am doing wrong? 
Or is this issue in the package code?

**Comment by davidmurdoch** [comment]
@loekTheDreamer Can you try again with `ganache@7.0.0-alpha.1` and let me know if you still get the error(s)?

**Comment by webmaster128** [comment]
It has been years since I opened this one and I don't work in this particular technology anymore. I also don't know what this is about anymore. So from my side this can be closed. However, if anything of the above is still useful, feel free to use this ticket but don't expect activity from me anymore. Cheers!

**Comment by loekTheDreamer** [comment]
> @loekTheDreamer Can you try again with `ganache@7.0.0-alpha.1` and let me know if you still get the error(s)?

@dherault Thank you for your feedback. I have been using `ganache-ui` (also tried the latest version for testing 2.6.0-beta.3.1390) which produces the nonce error and after trying your suggestion with `ganache@7.0.0-alpha.1` it produces the following signature error:

what is the error Error: processing response error (body="{\"id\":50,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"Invalid signature v value\",\"stack\":\"Error: Invalid signature v value\\n    at _ecdsaRecover (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:142156)\\n    at Object.t.ecdsaRecover (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:142673)\\n    at Object.t.computeFromAddress (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:142910)\\n    at Object.t.computeIntrinsicsLegacyTx (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:143172)\\n    at LegacyTransaction.computeIntrinsics (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:138171)\\n    at new LegacyTransaction (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:135686)\\n    at Function.fromTxData (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:136365)\\n    at Function._fromData (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:144814)\\n    at Function.fromString (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:146689)\\n    at EthereumApi.eth_sendRawTransaction (/usr/local/lib/node_modules/ganache/dist/node/1.js:2:15705)\",\"code\":-32700}}", error={"code":-32700}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0xf86d808504a817c80082520894793303e187ed167745d45894d5aa3a5b6c5010418901158e460913d000008025a0403baf1d981c4cda521336ec711e30937aeec76c7bad7219e2d3e3449e7c7b61a0337c10292203a36df13d503d065c5f9eb361bb646beaa415b7c22d888823ab0f\"],\"id\":50,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://127.0.0.1:8545", code=SERVER_ERROR, version=web/5.4.0)
    at Logger.makeError (index.ts:225)
    at Logger.throwError (index.ts:237)
    at index.ts:284
    at Generator.next (<anonymous>)
    at fulfilled (index.ts:2)
    
Not sure what is going on to be honest. 
Is my code correct?
Is there anything else I can try?

**Comment by davidmurdoch** [comment]
@loekTheDreamer, can you send the results of running `tx.serialize().toString('hex')` here?

**Comment by loekTheDreamer** [comment]
@davidmurdoch  So it seems that `await provider.sendTransaction('0x' + tx.serialize().toString('hex'));` produces the signature error above. Not sure if i am understanding you correctly but here is what is being submitted:
``` javascript
  const testTx = '0x' + tx.serialize().toString('hex');
  console.log('testTx: ', testTx);
  // testTx:  0xf86d808504a817c80082520894793303e187ed167745d45894d5aa3a5b6c5010418901158e460913d000008025a0403baf1d981c4cda521336ec711e30937aeec76c7bad7219e2d3e3449e7c7b61a0337c10292203a36df13d503d065c5f9eb361bb646beaa415b7c22d888823ab0f

```    
Thank you for your assistance.

**Comment by loekTheDreamer** [comment]
@davidbancor I just tested this on react-native bare and it works. seems that the issue is just with the expo.

**Comment by davidmurdoch** [comment]
Closing this for issue maintenance. Please leave a comment if this is still an issue and we'll reopen and look into it further!
