### ISSUE TITLE
Running ganache with a 5 second block time and submitting a raw transaction the result attribute is null

### ISSUE THREAD

**Issue by enddynayn** [trufflesuite/ganache#1018]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [x]
* Link to my question on gitter: `https://gitter.im/ConsenSys/truffle?at=5baec22b5331811c2e1fb00d`

## Expected Behavior
{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0x8b20826f01279cbce8a1974b358e9f2ae319ce200eac083e405c202722f6b3d0"],"id":1}

RESULT:
{"id":1,"jsonrpc":"2.0","result":{"hash":"0x8b20826f01279cbce8a1974b358e9f2ae319ce200eac083e405c202722f6b3d0","nonce":"0x02","blockHash":"0xb2300ce6350cb17d3f47ef1f3806f8a6a41fbaba9323605812b511b6d03b5143","blockNumber":"0x0758","transactionIndex":"0x00","from":"0x7d79d17bf95327ddcfbadfa1e2ae5ea1e5b69cb1","to":"0x4999022264a851e991b1abae43e1e2e33c7c9408","value":"0x0de0b6b3a7640000","gas":"0x7b0c","gasPrice":"0x3b9aca00","input":"0x0","v":"0x02cc43d15bfb","r":"0x5cbd4654d7c28d62f5956c6e38824202ddba95ce42703d3c365bb4020e84a061","s":"0x0359319b49400fccf6d247a95d3daa9f896cad4ce989b1e4c96fcfc773764b46"}}

## Current Behavior
when calling eth_getTransactionByHash on a unmined block I get the following result:
{"id":1,"jsonrpc":"2.0","result":null}

## Expected Behavior.
I expect the blockNumber to be null since the block has not been mined yet instead of the entire result being null.

{"id":1,"jsonrpc":"2.0","result":{"hash":"0x8b20826f01279cbce8a1974b358e9f2ae319ce200eac083e405c202722f6b3d0","nonce":"0x02","blockHash":"0xb2300ce6350cb17d3f47ef1f3806f8a6a41fbaba9323605812b511b6d03b5143","blockNumber":NULL,"transactionIndex":"0x00","from":"0x7d79d17bf95327ddcfbadfa1e2ae5ea1e5b69cb1","to":"0x4999022264a851e991b1abae43e1e2e33c7c9408","value":"0x0de0b6b3a7640000","gas":"0x7b0c","gasPrice":"0x3b9aca00","input":"0x0","v":"0x02cc43d15bfb","r":"0x5cbd4654d7c28d62f5956c6e38824202ddba95ce42703d3c365bb4020e84a061","s":"0x0359319b49400fccf6d247a95d3daa9f896cad4ce989b1e4c96fcfc773764b46"}}

## Steps to Reproduce (for bugs)

ganache-cli -b 5

1. send a raw transaction
{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf88a8085051f4d5c00833d09009404ab2c75459216cba0fe0e9a980eadbbfdc8a71480a499882cdb313233000000000000000000000000000000000000000000000000000000000081fba0bb96b7d56ae7d50271db11f36910189f89ebe258c0d8ced504f484ca5fd3e5d6a01ed6519ae894bbda2c7b62f89f0cb1e8a896c51410b0732e21a65550c38ea01d"],"id":1}

2. get the result, for example:
{"id":1,"jsonrpc":"2.0","result":"0x3cb14061774bfb0766ec7c094a0d02d3fa629678f68c142c7a20b7584089e039"}

3. get transaction by hash
{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["0x3cb14061774bfb0766ec7c094a0d02d3fa629678f68c142c7a20b7584089e039"],"id":1}

4. response results null
{"id":1,"jsonrpc":"2.0","result":null}

## Your Environment
Ganache CLI v6.1.8 (ganache-core: 2.2.1)
Truffle v4.1.14

**Comment by its-everdred** [comment]
Thanks for reaching out! This should be resolved in ganache@7.0.0-alpha.1, please confirm if upgrading to that version works.

**Comment by haltman-at** [comment]
We're going to close this for issue maintenance, but please let us know if there's still a problem and we can reopen this.  Thanks!
