### ISSUE TITLE
Error in npm start: "An unhandled error has occurred inside Forge: make: Entering directory '/home/vishal_ubuntu/Blockchain/ganache/ganache/node_modules/macos-alias/build'   CXX(target) Release/obj.target/volume/src/volume.o ../src/volume.cc:9:2: error: #error This platform is not implemented yet  #error This platform is not implemented yet"

### ISSUE THREAD

**Issue by Vishalckc** [trufflesuite/ganache#102]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.5.1
3 info using node@v9.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ganache@1.0.0~prestart: ganache@1.0.0
6 info lifecycle ganache@1.0.0~start: ganache@1.0.0
7 verbose lifecycle ganache@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle ganache@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/vishal_ubuntu/Blockchain/ganache/ganache/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
9 verbose lifecycle ganache@1.0.0~start: CWD: /home/vishal_ubuntu/Blockchain/ganache/ganache
10 silly lifecycle ganache@1.0.0~start: Args: [ '-c', 'electron-forge start' ]
11 silly lifecycle ganache@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle ganache@1.0.0~start: Failed to exec start script
13 verbose stack Error: ganache@1.0.0 start: `electron-forge start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:135:13)
13 verbose stack     at EventEmitter.emit (events.js:224:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:135:13)
13 verbose stack     at ChildProcess.emit (events.js:224:7)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid ganache@1.0.0
15 verbose cwd /home/vishal_ubuntu/Blockchain/ganache/ganache
16 verbose Linux 4.13.0-16-lowlatency
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v9.0.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error ganache@1.0.0 start: `electron-forge start`
22 error Exit status 1
23 error Failed at the ganache@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
![ganache_issue](https://user-images.githubusercontent.com/17704966/32942656-adea457c-cbaf-11e7-9e02-117b5e809b1e.png)

**Comment by benjamincburns** [comment]
It's hard for me to understand this issue. I think you're reporting an error from `electron-forge start`. From the look of things it's likely that your version of nodejs is too old (install and use [nvm](https://github.com/creationix/nvm) and your life will be much better), or your version of ubuntu is too old. Either way, updating these things, and updating to the latest release tag should get you sorted.
