### ISSUE TITLE
Transactions deep event support

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache#1026]
From #80 @zulhfreelancer brought up a good test case for events on transaction pages.

Creating this issue so I don't forget to test the case

```
@seesemichaelj cool! Question — will it support deep events too?

For example, contract A call a function contract B.

Contract B emits an event. Will Ganache shows the emitted event in contract B as well?

If you guys need some pointers, do check out my small library here to extract out deep events.

https://github.com/zulhfreelancer/truffle-events

I hope that helps!
```

**Comment by seesemichaelj** [comment]
Looks like this is already supported @zulhfreelancer! Thanks for the test case!

![peek 2018-12-08 17-06](https://user-images.githubusercontent.com/549323/49691236-a8ccb480-fb0b-11e8-9b0a-7de6747e0fd5.gif)

**Comment by seesemichaelj** [comment]
I'm not sure if this is a bug or not: the `LogAlphabet` event shows that it is under `Foo` because the address in the `to` field of the transaction was a `Foo` contract and not a `Bar` contract. Would we expect the contract name to be `Bar` in this case?

**Comment by zulhfreelancer** [comment]
@seesemichaelj yes, I'm expecting it goes under `Bar`. Thank you!

**Comment by seesemichaelj** [comment]
Reopening this to make sure the correct contract name/address is displayed on deep events
