### ISSUE TITLE
When >1 transactions in a block, all logs are included in all transactions.

### ISSUE THREAD

**Issue by beether** [trufflesuite/ganache#1029]
## Expected Behavior
Each transaction's logs should contain logs only relevant to that transaction, and not other transactions in the same block.

## Current Behavior
Each transaction's logs will contain all logs of all transactions that occurred on the block.

## Steps to Reproduce (for bugs)

Create two transactions in one block and look at the logs.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by cds-amal** [comment]
Closing for maintenance.
