### ISSUE TITLE
getFilterChanges seems to treat the hexId as a string literal and not a value

### ISSUE THREAD

**Issue by bhauman** [trufflesuite/ganache#1032]
## Expected Behavior
If I call getFilterChanges with `0x7` id it should work for a filter with an id `0x07`.

## Current Behavior
If one creates a filter and it returns an id with a leading "0" i.e "0x07",
If one subsequently calls `getFilterChanges` with "0x7" it will fail with:
`FilterSubprovider - no filter with that id: 0x7`

## Possible Solution
Test for numeric value equivalence or remove leading "0"'s to test for equality when responding to `getFilterChanges` requests

**Comment by cds-amal** [comment]
Fixed in `ganache@7.0.0-alpha.1`
