### ISSUE TITLE
`now` not respected in solidity during calls directly after `increaseTime` is called

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/ganache#1033]
If you call `evm_increaseTime`, then call a function using `eth_call` that includes the `now` variable in Solidity, the value of `now` won't respect the increased time. Big thanks to @mzeitlin8 for pointing it out.

To reproduce:

- Compile and deploy a contract with the following function:
    ```
    function getCurrentTime() returns (uint){
        return now;
    }
    ```
- Call `evm_increaseTime` to change the time to some astronomical amount
- Without making a transaction, call `eth_call` to `getCurrentTime()`. You'll notice the astronomical time change isn't respected.

## Workaround
Call `evm_mine` before calling `getCurrentTime()`, or make any transaction before calling `getCurrentTime()`. This will ensure the time change is respected.

**Comment by kraikov** [comment]
Any update on that?

**Comment by davidmurdoch** [comment]
@kraikov are you still seeing an issue with this in Ganache v7?

**Comment by kraikov** [comment]
@davidmurdoch yes, I'm using v7.0.1 and I've tried with both
`sendRpcRequest('evm_increaseTime', [seconds])`  and `sendRpcRequest('evm_mine', [])`

The block timestamp seems correct whenever I fetch the block data, but the solidity code that depends on `block.timestamp` does not respect it.

**Comment by davidmurdoch** [comment]
`evm_increaseTime` param is the `the total time offset *in milliseconds*`. I wonder if that be the issue you are seeing? Can you check and let me know, if it's actually not working when passed a milliseconds offset this is a top priority bug and we'll get a fix out ASAP!

**Comment by davidmurdoch** [comment]
I'm going to close this one, at least for now, @kraikov. If this is still an issue for you can you open a new one for it?
