### ISSUE TITLE
Discrepancy between geth and TestRPC with extcodesize()

### ISSUE THREAD

**Issue by tymat** [trufflesuite/ganache#1034]
The following solidity inline assembly returns a different value on TestRPC compared to other ethereum implementations:

```
function getCodeSize(address _address) returns (uint256 _codesize) {
   uint256 _codesize;
   assembly { _codesize := extcodesize(_address) }
   return _codesize
}
```

In geth it will return `0` when passed the address of an externally owned account but in TestRPC this returns `1`

## Expected Behavior

The code above should return `0` when passed the address of an externally owned account.

Please see geth results from [here](https://github.com/Dexaran/ERC23-tokens/issues/2)

## Current Behavior

It returns `1` on TestRPC.  Could possibly cause problems with other contracts 

## Steps to Reproduce (for bugs)

1. Deploy the code.
2. Pass it the address of an externally owned account.

## Your Environment

* Version used: `3.0.3`
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): `node v7.5.0`
* Server type and version: Tried on OSX, Linux, FreeBSD

**Comment by cds-amal** [comment]
Closing for issue maintenance. If this is still a problem for you please open a new issue. Thanks!
