### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by izqui** [trufflesuite/ganache#1036]
Hi there! 

Sorry if this is a dup or has been discussed before, but what would be the blocker (if any) for running `testrpc` directly in the browser (without server)?

From my research I found out `ethereumjs-vm` needed to be run in node, so i compiled it and imported it directly and tried to run it, but Meteor would get stuck while building when trying to compile it when including testrpc.

Thanks for your work!

**Comment by cds-amal** [comment]
Closing as this is available in `ganache@7.0.0-alpha.1`. Please see https://trufflesuite.github.io/ganache/ for an example of it running in the browser
