### ISSUE TITLE
0x80073CFD error in windows 10

### ISSUE THREAD

**Issue by srijithsrk** [trufflesuite/ganache#1049]
I downloaded ganache from your website and after getting the .appx file i used these steps https://www.howtogeek.com/285410/how-to-install-.appx-or-.appxbundle-software-on-windows-10/
lastly, after following  all the steps i got a message as "A Prerequisite for an install could not be satisfied."
![screenshot 305](https://user-images.githubusercontent.com/30682653/50018864-acbe7200-fff6-11e8-95c7-af228566490f.png)

**Comment by davidmurdoch** [comment]
You may need to run Windows update. Can you try that and let me know if it works for you?

**Comment by srijithsrk** [comment]
okay, will try then!

**Comment by davidmurdoch** [comment]
Closing due to age. @srijithsrk, please feel free to open a new issue if the problem occurs with the latest version of Ganache.
