### ISSUE TITLE
Download button redirects to release page

### ISSUE THREAD

**Issue by ShubhankarKG** [trufflesuite/ganache#1053]
Earlier, the download button used to download the relevant file (for eg. AppImage for Linux), but now it just redirects to the releases page, where you can only compile it from source.

**Comment by BhavyaSheth22** [comment]
Yes, there is no way to access the .AppImage file to run the Ganache GUI.

**Comment by HarsimranVirk** [comment]
I think the issue here is with the site, the download button redirects to [ganache release page](https://github.com/trufflesuite/ganache/releases/tag/2.13.2), instead of [ganache-ui release page](https://github.com/trufflesuite/ganache-ui/releases/tag/v2.5.4).

**Comment by davidmurdoch** [comment]
Sorry, the repo url recently changed. This should be fixed now. https://www.trufflesuite.com/ganache
