### ISSUE TITLE
System Error when running Ganache 1.6.11 on darwin

### ISSUE THREAD

**Issue by dylanseago** [trufflesuite/ganache#106]
Received this error while sending multiple transactions (200+) in a loop.

PLATFORM: darwin
GANACHE VERSION: 1.6.11

EXCEPTION:
TypeError: Cannot read property 'get' of undefined
    at dbGet (/Users/dylan/dev/trufflesuite/ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:49973:7)
    at /Users/dylan/dev/trufflesuite/ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:17655:5
    at /Users/dylan/dev/trufflesuite/ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:23327:20
    at iterate (/Users/dylan/dev/trufflesuite/ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:23408:13)
    at /Users/dylan/dev/trufflesuite/ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:23420:29
    at /Users/dylan/dev/trufflesuite/ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:23190:16
    at /Users/dylan/dev/trufflesuite/ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:17660:7
    at /Users/dylan/dev/trufflesuite/ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:49978:9
    at dispatchError (/Users/dylan/dev/trufflesuite/ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:30623:36)
    at /Users/dylan/dev/trufflesuite/ganache/node_modules/ethereumjs-testrpc/build/lib.node.js:22823:14

**Comment by benjamincburns** [comment]
Hi @dylanseago. Thanks for reporting this! We're tracking this issue over on trufflesuite/ganache-core#417. We even have an open bounty for it over there. If you could please subscribe to that issue instead, I'd be much obliged.
