### ISSUE TITLE
Prettify code

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/ganache#1085]
Follow up to the eslint stuff #1080 

Now that we have lint rules, we should enforce them across the repo. This is going to be a one time big bang refactor of the entire codebase to prevent random refactors from popping up in future PRs.

Past `git blame` can be looked at through Github if you need to see the blame for a logical piece of code rather than a cosmetic one. This refactor will probably be overwriting the blames for much of the codebase.

**Comment by adrianmcli** [comment]
Can't wait for the big bang.
