### ISSUE TITLE
[2.0 beta] Tell user to select truffle.js when adding a new project 

### ISSUE THREAD

**Issue by nikita-fuchs** [trufflesuite/ganache#1101]
When adding a new truffle project in Ganache 2.0, the description text should contain additional information to import the ```truffle.js```, without this information it's a bit of a guessing work in the beginning.

**Comment by honestbonsai** [comment]
Thanks for the suggestion @nikita-fuchs !

I agree this is confusing. With Truffle 5, the default is just `truffle-config.js` for both Windows and nix systems. We'll update that to be less confusing.
