### ISSUE TITLE
Not possible install dependencies (v1.3.0)

### ISSUE THREAD

**Issue by Shpionus** [trufflesuite/ganache#1110]
Not possible install dependencies on Ubuntu

### Error message
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/ganache-core/node_modules/eth-tx-summary/node_modules/eth-sig-util/ethereumjs-abi@git+https:/github.com/ethereumjs/ethereumjs-abi.git" as it does not contain a package.json file.
```

## Steps to Reproduce
1. Pull 1.3.0 version (commit 6d9e2fd6d38c21392de01e3dde3585c5fd5a36d4 (HEAD -> master, tag: v1.3.0, origin/master))
3. run `npm install`

**Comment by davidmurdoch** [comment]
This should be fixed in the latest version of Ganache. Try v1.3.1 (https://github.com/trufflesuite/ganache/commit/d0ba080f2b843cf1121e2804169fa2a22933dad9) and please reopen this issue if the issue persists.
