### ISSUE TITLE
Randomize network ID on start

### ISSUE THREAD

**Issue by danfinlay** [trufflesuite/ganache#112]
By default, Ganache should randomize the network ID whenever it is started.

The reason is so that MetaMask can recognize when the network has changed, and nonces are calculated appropriately.

Since Ganache was released, we've seen a spike in developers getting MetaMask locked up b/c it's tracking completed transactions from old networks with the same ID.

**Comment by tcoulter** [comment]
Thanks @danfinlay. We chose to choose the same id to make development easier in the long term. Keeping the same id reduces amount of "garbage data" in your contract artifacts and aides in keeping a consistent development environment (e.g., the host, port, mnemonic, accounts, and network id all stay the same). 

Have you guys considered using blockchain URIs to identify chains? Using blockchain URIs is network id agnostic and able to recognize forks. The URI format EthPM and `truffle-contract` uses is:

```
blockchain://<genesis block hash>/block/<latest block hash>
```

Which implies that by comparing the genesis block and the latest block of the current chain, you'll know you've found a match. Having to make these two requests makes implementation a little bit heavier, but not by too much and you'll know immediately if the user has used a new chain based on the hash of the latest block.

**Comment by tcoulter** [comment]
(As an aside, you don't _really_ need URIs. You could just as easily store the genesis block and the latest block hash for each chain you manage)

**Comment by tcoulter** [comment]
We have code to help you distinguish chains using URIs here: https://github.com/trufflesuite/truffle-blockchain-utils

**Comment by danfinlay** [comment]
I actually did suggest that as an approach to this [here](https://github.com/MetaMask/metamask-extension/issues/1999#issuecomment-345369943), and am using this general strategy a another prong of this network-change-detection [on this branch](https://github.com/MetaMask/metamask-extension/tree/i1999-DetectRemoteProviderChange).

**Comment by benjamincburns** [comment]
@danfinlay if the approach Tim proposed is acceptable to you, are you happy to close this branch?
