### ISSUE TITLE
Ganache not displaying data for Migrations contract

### ISSUE THREAD

**Issue by britalexander4** [trufflesuite/ganache#1128]
Ganache will not display the data for my Migrations.sol file even though the contract appears to have been successfully migrated and the data shows in my terminal. 

 

## Expected Behavior

I would expect Ganache to display the address and set the contract to "Deployed". 

## Steps to Reproduce (for bugs)

1. Create a new directory and run: truffle unbox metacoin
2. In another terminal window locate and run the latest version of Ganache (v2.0.0-rc.0)
3. Attached the newly unboxed truffleconfig.js using the Ganache UI 
4. Navigate back to the truffle metacoin directory and run: truffle migrate --all
5. The data from the migration should be visible on the Ganache UI. However consistently the Migrations.sol file will not display the data shown on the terminal and will be displayed as "Not deployed" despite is being deployed. 

<img width="780" alt="screen shot 2019-02-18 at 8 45 29 am" src="https://user-images.githubusercontent.com/47758017/52973906-b913d200-338d-11e9-8092-423dfb1fde55.png">

## Your Environment

* Version used: v2.0.0-rc.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Darwin 
* Server type and version:
* Operating System and version: macOS 10.13.6
* Link to your project:

**Comment by honestbonsai** [comment]
There is no address field being written to `Migrations` contract for some reason

**Comment by honestbonsai** [comment]
I think this is more of a Truffle issue, the `Migrations.json` that's generated by `truffle migrate` has an empty object for the field `networks`.

**Comment by honestbonsai** [comment]
Will be resolved once trufflesuite/truffle#1743 is merged

**Comment by honestbonsai** [comment]
trufflesuite/truffle#1763 solves this problem. Closing.
