### ISSUE TITLE
Ganache processes do not close when quiting in Mac dock

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache#1129]
Moving this from @balexander4's comment from https://github.com/trufflesuite/ganache/issues/1055#issuecomment-464231304

This is occurring for me again when I close Ganache using the dock on Darwin, (right clicking and hitting quit, instead of using the x). The processes remain open running in the background causing the port error issues mentioned above.

Steps to reproduce:

1. Open Activity Monitor to view open processes for Electron.
2. Open a new instance of Ganache 2.0.0.2 and choice an existing workspace.
3. Right click on the Ganache icon and select Quit to close. Do not use the left hand corner red X to close Ganache.
4. View open processes in the Activity Monitor. You should still see Electron processes running on the Activity Monitor even after Ganache has been closed.
5. Reopen Ganache and notice that there is an error about ports being already open on the Server tab. "The port is used by another application; please change it"

Running:
Mac High Sierra 10.13.6
Ganache 2.0.0.2

**Comment by honestbonsai** [comment]
Can reproduce the issue

**Comment by honestbonsai** [comment]
Wild guess based on https://electronjs.org/docs/api/app#event-window-all-closed

Listen for `will-quit` event rather than window-all-closed` to capture closing from dock
