### ISSUE TITLE
Sending ether to contract using metamask out of gas error

### ISSUE THREAD

**Issue by billtlee** [trufflesuite/ganache#1146]
I wanted to deploy a contract to ganache with some ether from remix.  however I forgot to enter it into the value field.  So, the contract was created with 0 balance.  i then tried to send some ether directly from metamask using the contract address.  I received an out of gas error.  I am not sure if this is a bug, but I am thinking I should be able to send ether to a deployed contract.  I am using ganache 1.3.0
 

 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: 1.3
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: OSX mojave
* Link to your project:

**Comment by davidmurdoch** [comment]
@billtlee, can you provide more details about the contract itself?

**Comment by billtlee** [comment]
Hi David,

Thanks for getting back.  I  am trying to play with the withdrawal pattern highlighted in the solidity doc by sending in some ether into a contract, changing the state to reject and basically issuing a refund (transfer the contract balance) back to the requestor. The contract deploys fine in remix and most of the functions and the getters are functioning. However, when I try to call the refund function within remix, I am getting a json-rpc error saying out of gas on eth_sendRawTransaction. I am trying to do this on ganache 1.3 using injected web3 on chrome with metamask.  Here is the contract code.

```
pragma solidity >=0.5.4 <0.6.0;

contract TestContract {
  uint public value;
  address payable public requestor;
  enum State { Requested, Approved, Rejected, Completed }
  State public state;

  mapping (address => uint) pendingWithdrawals;

  constructor(
    address payable _requestor
  ) public payable {
    requestor = _requestor;
    state = State.Requested;
    value = msg.value;
  }

  modifier onlyRequestor() {
    require(
      msg.sender == requestor,
      "Only requestor can call this."
    );
    _;
  }

  modifier inState(State _state) {
    require(
      state == _state,
      "Invalid state."
    );
    _;
  }

  event Rejected();
  event Approved();
  event DataReceived();

  function reject() public inState(State.Requested) {
    emit Rejected();
    state = State.Rejected;
    pendingWithdrawals[requestor] += address(this).balance;
  }

  function refund() public onlyRequestor inState(State.Rejected) {
    uint amount = pendingWithdrawals[msg.sender];

    pendingWithdrawals[msg.sender] = 0;
    msg.sender.transfer(amount);
  }
```

**Comment by billtlee** [comment]
I was able to get everything working if I switch to javascript vm on remix.  Very odd...

**Comment by davidmurdoch** [comment]
@thanks @billtlee! I'll look into it!

**Comment by nikita-fuchs** [comment]
This seems related to https://github.com/trufflesuite/ganache/issues/977, high priority bug since November '18.. ;)

**Comment by davidmurdoch** [comment]
This should now be fixed in the latest beta of ganache-cli and ganache-core.
