### ISSUE TITLE
For mac to build from source code, where can i get a Truffle's signing keys? 

### ISSUE THREAD

**Issue by PeterTsungYu** [trufflesuite/ganache#1161]
In the README, 
https://github.com/trufflesuite/ganache#on-mac
it requires a Truffle's signing key.
What is it? 
and where can I get it?

## Expected Behavior
I tried to find any sign up on the truffle website, but only found one for the mailing list.

**Comment by davidmurdoch** [comment]
The `Building for All Platforms` instructions is for internal use at Truffle; the section outlines the steps for publishing a signed release. These code signing certificates are not public or shared.

For contributing you'll just need to:

0. Clone this repo
1. Run npm install
2. Run npm start

If you want to sign the build for trusted distribution you'd need to purchase a code signing certificate. For personal use you could also generate a self-signed certificate that is marked as trusted in your keychain.
