### ISSUE TITLE
Add scroll bar to accounts page

### ISSUE THREAD

**Issue by bmmpxf** [trufflesuite/ganache#117]
## Issue Type

Feature

## Description

Please add a scroll bar to the main list of accounts, so that you can more easily see the contents. Right now the only way to see all of the accounts is by using the arrow keys (which is nice, but so is a scroll bar).

![image](https://user-images.githubusercontent.com/506694/33104182-a3e5e25a-cedb-11e7-91ae-2236f80128d6.png)

# Versions

Windows 10
Ganache v1.0.1

**Comment by benjamincburns** [comment]
I think it was a conscious stylistic choice to exclude the scrollbar here, as you can still scroll with a scroll wheel, touchscreen, or touchpad gestures. As such, I think you should ping @tcoulter about it if you want to see it change.

**Comment by bmmpxf** [comment]
I don't mind advocating for this. I believe that users expect scroll bars on pretty much everything (as they _have_ scroll bars on pretty much everything), so this isn't a wild request. It can be narrow or even hidden, but it should be an option so that (at the very least) people know where they are looking in the listing.

**Comment by seesemichaelj** [comment]
This was fixed in #649. In the next release
