### ISSUE TITLE
Code signing error during update to 2.0.0

### ISSUE THREAD

**Issue by CruzMolina** [trufflesuite/ganache#1170]
When attempting to update from Ganache 2.0.0-beta.2 (2.0.0-beta.2.398)
to Ganache 2.0.0 within the application, a code signature error appears.

<img width="493" alt="Screen Shot 2019-03-22 at 8 55 49 AM" src="https://user-images.githubusercontent.com/7537712/54838641-55c7d900-4c86-11e9-953a-0ab41ed14332.png">

OS: macOS 10.13.6 (High Sierra)

**Comment by DiscRiskandBisque** [comment]
If you close and re-open after that error, does it persist?

**Comment by CruzMolina** [comment]
Let me check... 

Yup. Same error.

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
