### ISSUE TITLE
Remix with Ganache: VM Exception while processing transaction: out of gas 

### ISSUE THREAD

**Issue by simibac** [trufflesuite/ganache#1171]
Running the following simple contract on Ropsten works fine. But on Ganache it results in a VM Exception that states that it ran out of gas. I played around with setting to gas price manually but it still ended up in the same exception. I know that this issue has been submitted before but I could not find a solution that worked for me.

````
pragma solidity >=0.4.25 <0.6.0;

contract EtherContract{
    function send() payable public {}
    
    function getBack() public{
        msg.sender.transfer(address(this).balance);
    }
    
    function getContractBalance() public view returns(uint){
        return address(this).balance;
    }
}
````

 

## Expected Behavior

The amount of ether stored in the contract should be refunded.

## Current Behavior

Results in a VM Exception.
> transact to EtherContract.getBack errored: VM Exception while processing transaction: out of gas 

## Steps to Reproduce (for bugs)

1. copy and past the smart contract into Remix
2. connect it to Ganache
3. compile
4. use the send function to send some ether to the contract (set value)
5. send the Ethers back to your account using the getBack function

## Context

A smart contract that can send Ethers to an address.

## Your Environment

* Version used: Compiler 5.3
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): Remix IDE on Brave
* Server type and version: Ganache 1.3
* Operating System and version: MacOS 10.14.3
* Link to your project:

**Comment by davidmurdoch** [comment]
This should now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.
