### ISSUE TITLE
Impossible to launch Ganache 2.0.0 on MacOS 10.14.4

### ISSUE THREAD

**Issue by sarbogast** [trufflesuite/ganache#1185]
## Expected Behavior
When I launch Ganache, I expect the main window to appear to let me choose my workspace.

## Current Behavior
The application launches, I can see it active in the dock, but no window appears, no error message, nothing. And the node doesn't seem to be running either since I can't attach a Truffle console to it.
I'm not 100% it's related, but this started happening after I upgraded MacOS to version 10.14.4 yesterday. To be sure, I would need to test it on another machine with 10.14.4 but I'm afraid to lose Ganache again as I really need it to work right now.
By the way, I tried with Ganache 2.0.0 final and I have exactly the same thing.
I checked the system console and here are all the messages related to Ganache:

```
default	13:38:03.074212 +0700	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Ganache, ready, updating active tracking timer
default	13:38:03.074359 +0700	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Ganache
default	13:38:04.469226 +0700	launchservicesd	CHECKIN:0x0-0x32032 573 org.trufflesuite.ganache
default	13:38:04.473631 +0700	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Ganache
default	13:38:04.498942 +0700	Ganache	Current system appearance, (HLTB: 2), (SLS: 1)
default	13:38:04.506509 +0700	Ganache	Post-registration system appearance: (HLTB: 2)
default	13:38:04.531724 +0700	Ganache	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 1
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600001e2adf0
 (
    "<NSAquaAppearance: 0x6000025ab1c0>",
    "<NSSystemAppearance: 0x6000025aacc0>"
)>
default	13:38:04.805856 +0700	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Ganache, ready, updating active tracking timer
error	13:38:04.824467 +0700	tccd	Failed to copy signing info for 573, responsible for file:///Applications/Ganache.app/Contents/MacOS/Ganache: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
error	13:38:04.836464 +0700	Ganache	        AEGetDescData of non-desc type 'reco' not a good idea
default	13:38:04.839114 +0700	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier org.trufflesuite.ganache, type: 0: 0x7f9c9b70dd30 at /Applications/Ganache.app
default	13:38:04.840522 +0700	hidd	Connection added: IOHIDEventSystemConnection uuid:42378ACE-FEBB-427A-B367-9A4950DB33EC pid:573 process:Ganache type:Monitor entitlements:0x0 caller:GameController: _GCHIDEventCallback + 86 attributes:(null) inactive:1
default	13:38:04.859947 +0700	hidd	Connection added: IOHIDEventSystemConnection uuid:FE82D2A2-2EF0-441D-BE57-E9E86E889B44 pid:573 process:Ganache type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1
error	13:38:04.888584 +0700	Ganache	nw_path_close_fd Failed to close guarded necp fd 31 [9: Bad file descriptor]
default	13:38:09.810378 +0700	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Ganache
default	13:38:09.810413 +0700	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Ganache
default	13:38:09.810869 +0700	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Ganache
default	13:38:09.821641 +0700	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Contents:(
        {
        BackgroundState = 2;
        BundleID = "org.trufflesuite.ganache";
        Hide = 0;
        Path = "/Applications/Ganache.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    }
)
default	13:38:14.847321 +0700	Ganache	LSExceptions shared instance invalidated for timeout.
default	13:38:15.558235 +0700	Ganache Helper	LSExceptions shared instance invalidated for timeout.
```

## Context
I'm simply not able to use Ganache anymore, which delays me in the production of my Udemy course covering Ganache, Truffle and all of that.

## Your Environment
* Version used: 2.0.0-beta.2 or 2.0.0 final
* Operating System and version: MacOS 10.14.4

**Comment by sarbogast** [comment]
I just had to upgrade my main Mac to 10.14.4 and there, Ganache launches without any issue.
Might the issue be related to the fact that the first machine I had it on in a virtual one (VMWare Fusion)?

**Comment by davidmurdoch** [comment]
@sarbogast, hmmm, interesting... and very frustrating! Sorry about these issues!

We have an issue with code signing getting skipped in our Travis automated build for mac that has caused in-app upgrades of Ganache to not work on Mac, this looks like it could be related to that (https://github.com/trufflesuite/ganache/issues/1170). Have you tried (uninstalling then) reinstalling Ganache?

**Comment by sarbogast** [comment]
@davidmurdoch I just did, and it didn't change anything.

**Comment by seesemichaelj** [comment]
Hey @sarbogast! If Ganache 2.0 isn't required for your class, we don't want to delay you! You can still grab the [latest 1.x build](https://github.com/trufflesuite/ganache/releases/tag/v1.3.1) which most tutorials/classes are based around. However, we definitely consider this a high priority and work at this diligently!

As @davidmurdoch said, we do have signing issues with our build (#1170) for mac. You may not be seeing the popup that's saying "This is an unidentified developer", but you can still see if you can try the mitigation anyway. [This link](https://truefire.zendesk.com/hc/en-us/articles/200200566-Open-Program-from-Unidentified-Developer-Mac-) goes into more detail, but the gist is:
1. Go to `System Preferences`
1. Click on `Security & Privacy`
1. Under the `General` tab, in the second section, does it say something like `"Ganache" was blocked from opening because it is not from an identified developer.`? If so there should be an `Open Anyway` button. You should only have to do this once (and maybe on updates until we fix the signing issue).
1. I forget (I'm usually a Linux user, but I've had to do these steps when testing on Mac) if the app just opens up, or you have to go open it. But it's possible there may be another popup from Mac saying "Are you sure you want to open this anyway?". To find the popup, you may need to right-click on the Ganache icon in the dock to see if there is a window you can press to focus.

**Comment by sarbogast** [comment]
No no that’s not a signature problem. I had to go to the Security and Privacy thing and « open anyway » indeed. And that made it possible for the app itself to launch. I can see Ganache appear in the MacOS menu bar, and the icon in the dock gets the launched indicator. But the main window never appears.

About the tests I made, I had MacOS 10.14.3 on my MacBook Pro, on top of which I have a VMWare Fusion VM with MacOS 10.14.4. I installed Ganache 2 on the VM when it was still using MacOS 10.14.3 and it worked just fine. And since I upgraded the VM to 10.14.4, I have this weird problem where the app launches but the main window does not appear (and apparently the node is not started in the background either since I can’t attach a Truffle console to it). A couple of days ago, I upgraded the host machine to 10.14.4 and there, Ganache 2 continued launching fine. So I guess it’s harder to reproduce than I thought. 

The problem is that I use those VMWare Fusion VMs a lot while teaching because it allows me to start from a clean environment, assuming as little as possible about my students’ environment. That’s why I need it to work in the VM too.

**Comment by seesemichaelj** [comment]
Ah ok, I understand now. We'll try to reproduce and discuss this to see if we can figure out the cause of the error. Thanks again!

**Comment by davidmurdoch** [comment]
@sarbogast Have you tried installing in a clean 10.14.4 VM (that's never had Ganache installed)?

**Comment by sarbogast** [comment]
@davidmurdoch  It seems to work fine in a clean 10.14.4 VM

**Comment by davidmurdoch** [comment]
@sarbogast can you back-up (so we can try to reproduce if this directory is the culprit) and then delete Ganache's config directory located at `~/Library/Application Support/Ganache` and let me know if that works?

If that works do you mind zipping up your `~/Library/Application Support/Ganache` folder and sending it to us to use for debugging?

**Comment by sarbogast** [comment]
Indeed, once I removed this directory out of the way, Ganache launched fine once again.
You can download the compressed directory from there: https://d.pr/f/0D0lYC

**Comment by sarbogast** [comment]
Could not reproduce in 2.0.1-beta.0

**Comment by josescasanova** [comment]
Hey ya'll, I'm running into a similar issue on MacOS 10.15.7. I cleared out the Ganache directory in Application Support and tried re-installing a few different Ganache versions.

Are there any other directories or files I should be removing for a clean install? 

Thanks!
