### ISSUE TITLE
Accounts not showing in GUI

### ISSUE THREAD

**Issue by stevechen** [trufflesuite/ganache#1222]
<img width="1216" alt="Ganache_and_CleanMyMac_and_LaunchAgents" src="https://user-images.githubusercontent.com/497347/55677643-15bb5400-591e-11e9-97c9-e8a43a54acce.png">

## Expected Behavior
In the main window,  accounts showing.

## Current Behavior
In the main window, accounts are not showing. I can see MNEMONIC, HD PATH, but below them is just a blank window.
Tried to uninstall (delete all related files) and reinstall, tried restarting, tried with Quickstart and New workspace, all the same. The accounts seems to be working because when I use the console, I can get all the accounts by calling web3.eth.getAccounts(), it's just not displaying them on the UI.

In the console, I see 2 related problem types:

1. tccd: Failed to copy signing info for 2739, responsible for file:///Applications/Ganache.app/Contents/MacOS/Ganache: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"

2. Ganache: nw_path_close_fd Failed to close guarded necp fd 25 [9: Bad file descriptor]

## Context
It's extra steps I have to take everytime I try to access account info.

## Your Environment
* Version used: 2.0.0
* Operating System and version: Mac OS X 10.14.4

**Comment by davidmurdoch** [comment]
This may now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.

**Comment by stevechen** [comment]
> This may now be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Let me know if you have any issues or if the fix doesn't work for you.

2.0.1-beta.0 fixed it, thank you.
