### ISSUE TITLE
System Error when running Ganache 2.0.0 on darwin

### ISSUE THREAD

**Issue by vermi** [trufflesuite/ganache#1231]
Attempting to establish a websocket connection from python-web3 using WebsocketProvider, receive the following error:

PLATFORM: darwin
GANACHE VERSION: 2.0.0

EXCEPTION:
```
TypeError: connection.reject is not a function
    at WebSocketConnection.<anonymous> (/node_modules/ganache-core/lib/webSocketServer.js:49:18)
    at emitOne (events.js:115:13)
    at WebSocketConnection.emit (events.js:210:7)
    at WebSocketConnection.processFrame (/node_modules/ganache-core/node_modules/websocket/lib/WebSocketConnection.js:529:26)
    at /node_modules/ganache-core/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":8545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false}
T+48ms: Ganache started successfully!
T+48ms: Waiting for requests...
T+54ms: eth_subscribe
T+55ms: eth_getLogs
T+55ms: eth_subscribe
T+2904ms: eth_blockNumber
T+7369ms: eth_blockNumber
T+8375ms: eth_blockNumber
T+9382ms: eth_blockNumber
T+10309ms: eth_unsubscribe
T+10310ms: eth_unsubscribe
T+10311ms: eth_unsubscribe
T+10312ms: eth_unsubscribe
T+10312ms: eth_unsubscribe
```

**Comment by davidmurdoch** [comment]
Thanks for opening the issue, @TheRealPOTUS. We don't _currently_ support binary data over websockets. Is it possible for you to transmit via utf8 instead?

**Comment by TheRealPOTUS** [comment]
I'm not super knowledgeable about python websockets, but there doesn't appear to be a kwarg that can change the encoding from binary to utf-8.

I attempted to switch to HTTPProvider instead of WebsocketProvider, but ganache throws a 403 on those requests.

**Comment by davidmurdoch** [comment]
Can you share the exact output for the 403 error response here?

**Comment by TheRealPOTUS** [comment]
`self.web3.eth.defaultAccount = web3.eth.coinbase` returns the following error:
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://127.0.0.1:8545/

**Comment by davidmurdoch** [comment]
Hmm. I didn't think Ganache itself ever returns a 403 status code. Are there any logs showing in Ganache's `Logs` tab when you receive this error?

**Comment by TheRealPOTUS** [comment]
No, no logs showing there when this error pops.

**Comment by davidmurdoch** [comment]
Hm. I'm not sure what is sending that 403 response.

I've opened a PR to add binary websockets here to our core library: https://github.com/trufflesuite/ganache-core/pull/410

Assuming our CI passes and code review goes well, it'll likely be another week (or two) until this is released in the next beta of Ganache UI.

**Comment by TheRealPOTUS** [comment]
Awesome, thanks for that info -- I'll keep an eye on the PR and test it out as soon as it's released. Much prefer ganache to geth for testing on Mac.
