### ISSUE TITLE
Error in connection establishment: net::ERR_SOCKS_CONNECTION_FAILED

### ISSUE THREAD

**Issue by ademenev** [trufflesuite/ganache#1234]
After creating a workspace, transactions, logs and account tabs are all empty. 

Javascript console shows the following:

/private/tmp/Ganache.app/Contents/Resources/app.asar/node_modules/web3-providers-ws/src/index.js:33 WebSocket connection to 'ws://127.0.0.1:7545/' failed: Error in connection establishment: net::ERR_SOCKS_CONNECTION_FAILED

The above is in version 1.31, but same error occurs in 2.0.0 and 2.0.1 beta

**Comment by davidmurdoch** [comment]
@ademenev Thanks for the opening issue!

Can you try backing up and then deleting the config directory: `~/Library/Application Support/Ganache`?

**Comment by ademenev** [comment]
@davidmurdoch Thanks! After removing that directory, I was able to create a workspace
