### ISSUE TITLE
Ganache GUI account is empty

### ISSUE THREAD

**Issue by TaibiaoGuo** [trufflesuite/ganache#1241]
The `Ganache GUI V2.0.0` does not display account details.My OS is `MacOS Mojave 10.14‘` and the `CLI version` is useful.

I tried to uninstall and modify MacOS's system security settings and make sure it wasn't a MacOS problem. 

I also tried QuickStart and the new WorkSpace, but it didn't work.

![image](https://user-images.githubusercontent.com/34874132/56034783-f035ac80-5d5a-11e9-9dbc-b789384e051c.png)

**Comment by davidmurdoch** [comment]
Thanks @TaibiaoGuo for opening the issue. Can you try our latest release, https://github.com/trufflesuite/ganache/releases/tag/v2.0.1, and let me know if this is still an issue?

**Comment by TaibiaoGuo** [comment]
THANKS！The V2.0.1 can be  WORK in the same ENV!

**Comment by pkumarasr** [comment]
Hi,
Even i am facing same issue. Currently downloaded Ganache-2.0.1 (1).dmg version still i am not seeing the accounts ??
Btw, truffle console i can see the accounts.

Thanks,
Praveen

**Comment by TaibiaoGuo** [comment]
> 嗨，
> 即使我面临同样的问题。目前下载的Ganache-2.0.1（1）.dmg版本仍然没有看到账号？
> 顺便说一句，松露控制台，我可以看到帐户。
> 
> 谢谢，
> Praveen

You can try the following steps:

**step 1: Enable Gatekepper's Anywhere setting**
Open Terminal.Type the following command:
 `sudo spctl --master-disable`

Gatekeeper's "Anywhere" setting will now be restored. It will also be selected by default. You can confirm the changes by opening System Preferences and selecting Security & Privacy.

**step 2: Delete ganache**

**step 3: Reinstall ganache GUI Version 2.0.1 in your MacOS**
