### ISSUE TITLE
Ganache hangs when starting, if there is another application uses the same port!

### ISSUE THREAD

**Issue by Muhammad-Altabba** [trufflesuite/ganache#126]
## Issue Type

Bug

## Description
When trying to run Ganache, it just hangs showing the following screen with no more actions.

![ganache hangs](https://user-images.githubusercontent.com/24407834/33328240-84600ca0-d46a-11e7-9be5-a51bc0d0666a.PNG)

Ganache just hangs forever! Without showing any error message.
## Steps to reproduce
After investigation, I found that there was an application that uses the same default port of Ganache 7545.
Ganache should show error message clarifying that there is another application that uses the default running port. And better to suggest another port to start running with OR open Ganache settings page and notify to change the running port
So steps to reproduce is:

- Have any application that uses the running port of Ganache (port 7545 is the default if not changed).
- Run Ganache
- Ganache will hang with no error message or options to overcome.

# Versions
I verified the bug on both: Windows 10 and Ubuntu. And it is most likely on all OSs.
One of my systems is:
- Ubuntu 17.10 64bit
- node v6.11.4
- npm 3.5.2
- Truffle v4.0.1 (core: 4.0.1)
- Solidity v0.4.18 (solc-js)

**Comment by iinstances** [comment]
I had to deal with the same problem and I agree.

**Comment by JackBekket** [comment]
I've found something interesting - if you are using a **window** Ganache application - it is not kill Ganache process itself when you close window (which is obviously a bug).

So when you start it once, then close, then try to start it once again - it is **hanging** because old instance is **still running** on the same port. 

Possible solution - open terminal and type ```top``` to check this, then try to kill process manually via ``` killall Ganache```

But in fact there is definetly a bug with a window app, so I hope developers will fix it.

**Comment by FollowJack** [comment]
How to solve this with Mac OS? 
Please help. Awesome tool. Shitty bug.

**Comment by benjamincburns** [comment]
@JackBekket not closing when the window is closed is only an OSX bug, and I just fixed it yesterday in the current `develop` branch.

When that happens you'll still see the Ganache icon down in your dock. You can click that icon and hit Cmd-Q to exit Ganache, or go to Ganache -> Quit in the top menubar.

@FollowJack - I suspect you're likely running into the same issue.

**Comment by benjamincburns** [comment]
Just a heads up that this is actually a two part issue. I've opened #344 to capture the problem which I intend to address ahead of the next beta. Addressing the issue of what to do when the port is in use (or when Ganache can't listen on a specific interface) will require some UI/UX work. I intend to get that done before the next stable release.

**Comment by seesemichaelj** [comment]
We moved tracking this to #665. The PR #712 fixes this and it will be in the next release

**Comment by pedroduartecosta** [comment]
For anyone who may run into this in the future. My problem was that I was **loading a truffle.js config** file and it was getting stuck on the loading screen.

Running `npm install` inside my project folder, where the truffle.js file is, **fixed** the problem.
