### ISSUE TITLE
Ganache GUI account is empty

### ISSUE THREAD

**Issue by pkumarasr** [trufflesuite/ganache#1276]
Ganache UI accounts are not showing up.

I just downloaded Ganache and started with quickstart workspace. Accounts are not displaying the default account screen and also there are no transaction showing up after running sample contract.  I can see in the gui logs all the accounts information when i run the smart contract. 

Mac version 10.13.6
Ganache-2.0.1.dmg.

Can you suggest me what can be done to get this accounts/transactions/blocks ??
Thanks in advance for the help.

Thanks,
Praveen

**Comment by kumar80** [comment]
same issue on Windows 10 ,Ganache-2.0.1.appx

**Comment by Patralekha** [comment]
Same issue.Error pops up.

**Comment by davidmurdoch** [comment]
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
