### ISSUE TITLE
serve Ganache as web application instead of electron app

### ISSUE THREAD

**Issue by drandreaskrueger** [trufflesuite/ganache#129]
Your 

ganache frontend application looks as if it could be a webpage - right?

As a workaround for my main question https://github.com/trufflesuite/ganache/issues/108 I could also start 2 instances of ganache each in their own docker machine, and then map their ports (7545, and I suppose ... 80 ? for the frontend?) to two different port tuples on the host machine.

Then 2 instances could coexist without changing much of the inner workings.

Anyone got a dockerfile for the ganache gui ?

**Comment by roderik** [comment]
Was looking for the same thing!

**Comment by benjamincburns** [comment]
This is an interesting idea, @drandreaskrueger and @roderik.

You're correct that Ganache is a React app running in an electron container. It's true that electron does use an embedded browser for rendering its UI, but it's not simply just running an embedded web server under the hood, meaning it's not a given that you can just pop an electron app out of its container and expect to serve it up over the interwho.

The good news is that given the way Tim likes to code, I'd suspect any direct coupling to Electron outside of application startup code is fairly minimal if any exists at all, meaning that most of the work necessary to make this possible would be in the application initialization phase.

At the moment we're a lot more focused on how we can improve the way Ganache can present things like contract state change, transaction traces, etc, than we are in how we might repackage it. That said, we certainly don't have anything planned which would be at odds with such an effort, so if you're interested in making this happen, I'd encourage you to give it a try.

**Comment by drandreaskrueger** [comment]
Thanks a lot, benjamincburns. Unfortunately, I am very limited in time, so I cannot look into it now. And we have moved on to simply spinning up our own private chains, instead of ganache. A pity, in a way, I would have liked to try it out.

The above docker route would be a workaround already (it allows to map any port to any port) - but it would have general advantages. "Dockerize everything" ;-)

Alternatively, just look at https://github.com/trufflesuite/ganache/issues/108 again - I don't think that adding one or two more config variables (that allow to freely choose all ports) to ganache would be difficult at all for you.

Thanks.

**Comment by dylanseago** [comment]
I've got a work in progress solution here https://github.com/trufflesuite/ganache/pull/401

**Comment by drandreaskrueger** [comment]
Fantastic, @dylanseago - kudos, compliments, applause, and a big thank you.

I have subscribed to the pull request, let's see how that goes.

**Comment by drandreaskrueger** [comment]
I see there was progress on the pull request?

**Comment by Asone** [comment]
@drandreaskrueger : unfortunately it seems that update of master created new conflicts on the PR :(

**Comment by seesemichaelj** [comment]
@benjamincburns's comment from #401:

I'm really sorry to do this, but I'm afraid I need to close this one. The way we'd go about this feature would be to make the ganache UI capable of pointing at an arbitrary provider URL, and then users could run ganache-cli as a daemon (e.g. using our docker image) if they like. Otherwise we've discussed internally and for the moment at least we have no immediate plans on supporting a web-based Ganache UI.
