### ISSUE TITLE
ganache doesn't open on ubuntu 19.04

### ISSUE THREAD

**Issue by oiagh** [trufflesuite/ganache#1297]
ganache wont run on ubuntu 19.04

## Expected Behavior

once I've downloaded ganache from the site https://truffleframework.com/ganache I right clicked on the downloaded file -> properties -> permissions -> allow executing file as program
After that I tried to open ganache but nothing happened, ganache does not run.
expected behavior: the gui should be opened.

## Current Behavior

when i lunch ganache using the icone al ganache, it doesn't run

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by oiagh** [comment]
I reinstalled ubuntu (v18.04 LTS) and now it works. Thanks.

**Comment by dngani** [comment]
Hello, 
i had the same problem on Ubuntu 19.04

In my case, some librairies (libgtk and libcanberaa-gtk) were missing. I could see following message in the logs : "error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory".

After installing the 2 librairies, ganache run without any other problem.
