### ISSUE TITLE
White screen when clicking 'CONTRACTS' (Cannot read property 'to' of null)

### ISSUE THREAD

**Issue by Avantgarde95** [trufflesuite/ganache#1332]
When I run 'Quickstart', link my truffle project to Ganache, migrate the contracts and click 'CONTRACTS' tab in Ganache, Ganache sometimes raises `TypeError: Cannot read property 'to' of null` and gives a white screen.

![Screen 1](https://i.imgur.com/QXy6ciW.png)
![Screen 2](https://i.imgur.com/Z0mMYhc.png)

 

## Expected Behavior

Show the contracts' information.

## Current Behavior

Raises an exception `TypeError: Cannot read property 'to' of null` and gives a white screen.

## Possible Solution

I think that when I run 'New workspace' instead of 'Quickstart', I don't get such error.

## Steps to Reproduce (for bugs)

Since this bug occurs randomly, I can't find the exact condition of generating this bug.

## Your Environment

* Version used: v2.0.1

* Operating System and version: Windows 10

**Comment by xxANONYMxx** [comment]
I too suffer from the same bug.
My version of Ganache is: 2.1.2
Operating System is: Windows 10

**Comment by Jshanks21** [comment]
Same here.
Ganache: 2.1.2
OS: Windows 10

**Comment by davidmurdoch** [comment]
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
