### ISSUE TITLE
System Error when running Ganache 2.0.3 on win32

### ISSUE THREAD

**Issue by GuoLLL** [trufflesuite/ganache#1361]
PLATFORM: win32
GANACHE VERSION: 2.0.3

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:276:18)
    at Timeout._onTimeout (C:\Program Files\WindowsApps\Ganache_2.0.3.0_x64__zh355ej5cj694\app\resources\app.asar\node_modules\web3-providers-ws\src\index.js:261:19)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
    at listOnTimeoutNT (timers.js:340:26)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server (version 2.0.3) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"C:\\Users\\Mr.L\\AppData\\Roaming\\Ganache\\workspaces\\kindhearted-animal\\chaindata"}
T+92ms: Ganache started successfully!
T+92ms: Waiting for requests...
```

**Comment by tsavercool** [comment]
Came to report same exact error.

This problem occurs when you do not have a network interface in the connected state. 

I tried to use Ganache on the go without network connectivity and ran into this.

To replicate this issue:
1.Download / install Ganache
2.run it
3.verify it is working
4. stop Ganache
5. Disable all network devices ( I left my bluetooth device active and it still crashed )
6. Start Ganache
7. Either choose quick start or an existing workspace
8. Either will result in a crash with details provided in GuoLLL's post above.

It would be great if this did not happen as I would like to be able to do development on the go.

I suspect there is logic that is parsing for active connections and than indexing into those connections. If that is the case than a solution would be to start the collection off as containing the loop back connection so the loopback can be used if nothing else is available.

**Comment by tsavercool** [comment]
verbose output:

 "error": {
 <       "message": "Subscription ID 0x2 not found.",
 <       "code": -32000,
 <       "data": {
 <         "stack": "Error: Subscription ID 0x2 not found.\n    at SubscriptionSubprovider.eth_unsubscribe (C:\\Program Files\\WindowsApps\\Ganache_2.0.3.0_x64__zh355ej5cj694\\app\\resources\\app.asar\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\subproviders\\subscriptions.js:77:8)\n    at SubscriptionSubprovider.handleRequest (C:\\Program Files\\WindowsApps\\Ganache_2.0.3.0_x64__zh355ej5cj694\\app\\resources\\app.asar\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\subproviders\\subscriptions.js:133:12)\n    at next (C:\\Program Files\\WindowsApps\\Ganache_2.0.3.0_x64__zh355ej5cj694\\app\\resources\\app.asar\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:116:18)\n    at DelayedBlockFilter.handleRequest (C:\\Program Files\\WindowsApps\\Ganache_2.0.3.0_x64__zh355ej5cj694\\app\\resources\\app.asar\\node_modules\\ganache-core\\lib\\subproviders\\delayedblockfilter.js:31:3)\n    at next (C:\\Program Files\\WindowsApps\\Ganache_2.0.3.0_x64__zh355ej5cj694\\app\\resources\\app.asar\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:116:18)\n    at RequestFunnel.handleRequest (C:\\Program Files\\WindowsApps\\Ganache_2.0.3.0_x64__zh355ej5cj694\\app\\resources\\app.asar\\node_modules\\ganache-core\\lib\\subproviders\\requestfunnel.js:32:12)\n    at next (C:\\Program Files\\WindowsApps\\Ganache_2.0.3.0_x64__zh355ej5cj694\\app\\resources\\app.asar\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:116:18)\n    at Web3ProviderEngine._handleAsync (C:\\Program Files\\WindowsApps\\Ganache_2.0.3.0_x64__zh355ej5cj694\\app\\resources\\app.asar\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:103:3)\n    at Timeout._onTimeout (C:\\Program Files\\WindowsApps\\Ganache_2.0.3.0_x64__zh355ej5cj694\\app\\resources\\app.asar\\node_modules\\ganache-core\\node_modules\\web3-provider-engine\\index.js:87:12)\n    at ontimeout (timers.js:469:11)\n    at tryOnTimeout (timers.js:304:5)\n    at Timer.listOnTimeout (timers.js:264:5)",
 <         "name": "Error"
 <       }
 <     }
 <   }
[2019/07/20 11:54:27.040] - Warning: stopMining called when miner was already stopped

**Comment by davidmurdoch** [comment]
Closing in favor of #1238.
