### ISSUE TITLE
Add support for EIP-712: eth_signedTypedData RPC endpoint

### ISSUE THREAD

**Issue by fubuloubu** [trufflesuite/ganache#1375]
## Issue
Ganache doesn't implement [EIP-712](https://eips.ethereum.org/EIPS/eip-712) yet

## Expected Behavior
Given the following JSON-RPC call:
```
method = 'eth_signTypedData'
params = [
  <local account's address>,
  <EIP-712 Object>
]
```
ganache's web3 instance should have the specified local account sign the specified structured data according to the EIP-712 specification, which is a Draft standard on the path to finalization.

## Motivation
People will begin using EIP-712 for off-chain message signing once more functionality is available in Web3/Ethereum clients and popular languages such as Solidity and Vyper. It would good to have it available in testing infrastructure sooner rather than later.

**Comment by davidmurdoch** [comment]
Closed in https://github.com/trufflesuite/ganache/releases!
