### ISSUE TITLE
macOS 10.14.6 - Ganache only opens when run with sudo from Terminal

### ISSUE THREAD

**Issue by boyuanx** [trufflesuite/ganache#1377]
## Expected Behavior
Ganache 2.1.0 should launch.

## Current Behavior
Ganache doesn't launch. Its icon appears in the dock but then stops responding.
Output from Console.app:
```
error	15:53:51.787660 +0800	Ganache	        AEGetDescData of non-desc type 'reco' not a good idea

default	15:53:51.794709 +0800	hidd	Connection added: IOHIDEventSystemConnection uuid:69AD9926-C4E6-415E-8B9C-9EB156C9C7DE pid:2502 process:Ganache type:Monitor entitlements:0x0 caller:GameController: _GCHIDEventCallback + 86 attributes:(null) inactive:1

default	15:53:51.806902 +0800	hidd	Connection added: IOHIDEventSystemConnection uuid:5C8101DB-CEAC-47AD-9C20-F268F29CB9B9 pid:2502 process:Ganache type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:1

error	15:53:51.826035 +0800	Ganache	nw_path_close_fd Failed to close guarded necp fd 32 [9: Bad file descriptor]

default	15:53:51.858292 +0800	Ganache Helper	GVA info: preferred scaler idx 1

default	15:53:53.949211 +0800	Ganache	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 198, 513, <private>

default	15:54:01.676050 +0800	Ganache	LSExceptions shared instance invalidated for timeout.

default	15:54:01.731752 +0800	Ganache Helper	LSExceptions shared instance invalidated for timeout.
```

## Possible Solution
Running Ganache with sudo from Terminal fixes the issue.

## Steps to Reproduce (for bugs)
1. Launch Ganache 2.1.0
2. Its icon appears in the dock and then nothing happens.

## Context
Unusable unless I launch it from the Terminal with sudo. I was using it just fine two days ago and it wouldn't open today. Did nothing to the Mac.
BTW ~/Library/Application Support/Ganache does not exist. There is no "Ganache" folder.

## Your Environment
* Version used: 2.1.0
* Operating System and version: macOS 10.14.6

**Comment by boyuanx** [comment]
Also Ganache has become very sluggish and unresponsive ever since the incident. It has started to randomly freeze and unfreeze itself.

**Comment by jamesmorgan** [comment]
I also get this problem, I tried to upgrade from 1.2 and Ganache installed then just shows dock icon and no app - had to force kill it. `sudo ./Ganache.app/Contents/MacOS/Ganache` this opened Ganache - any better to do this, not keen on giving sudo access or launching from command line?

**Comment by eloudsa** [comment]
I have the same issue since my update to macOS 10.14.6.
Ganache 2.1.0 doesn't launch using my account.

To solve this, I had to run Ganache as sudo.

**Comment by yyh1102** [comment]
Same problems. I cannot even open the Ganache GUI~

**Comment by eloudsa** [comment]
@yyh1102 
On macOS, I have removed the folder **~/Library/ApplicationSupport/Ganache**
Then I've reinstalled Ganache. Now Ganache launches without sudo command.

**Comment by boyuanx** [comment]
@eloudsa Unfortunately there is no such folder for me...

**Comment by davidmurdoch** [comment]
@yyh1102, @eloudsa, @boyuanx What version of Ganache is causing the issue?

**Comment by davidmurdoch** [comment]
@boyuanx 	hm, when did this issue start for you?

**Comment by boyuanx** [comment]
@davidmurdoch As far as I can remember, ever since my upgrade to macOS 10.14.6

**Comment by boyuanx** [comment]
@davidmurdoch Do I just drag it into the bin? What other files should I delete?

**Comment by davidmurdoch** [comment]
@boyuanx That should work. If you don't have anything related to Ganache in `~/Library/ApplicationSupport` (or `~/Library/Application Support`) then that's all there is. Let me know if it works for you or not!

**Comment by yyh1102** [comment]
@eloudsa It works for me. @davidmurdoch 2.1.0 and 2.1.1 cause this issue since i update macOS to 10.14.6

**Comment by boyuanx** [comment]
@davidmurdoch Nope, tried it, still the same issue...

**Comment by jamesmorgan** [comment]
Yep same for me, I have removed, checked `~/Library/Application Support` and then reinstalled - no good - still requires sudo to launch

**Comment by davidmurdoch** [comment]
@jamesmorgan and @boyuanx can you check the following directories:

`/Applications/Ganache.app/Contents/Frameworks/Electron`
`/Applications/Ganache.app/Contents/Frameworks/Ganache`
`/Applications/Ganache.app/Contents/Frameworks/Mantle.framework/Versions/A/Mantle`
`/Applications/Ganache.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/A/ReactiveCocoa`
`/Applications/Ganache.app/Contents/Frameworks/Squirrel.framework/Versions/A/Squirrel`
`/Applications/Ganache.app/Contents/MacOS/Ganache`
`/Applications/Ganache.app/Contents/Resources/app.asar`
`/Applications/Ganache.app/Contents/Resources/electron.asar`
`~/Library/Application\ Support`
`~/Library/Saved\ Application\ State`

Your user should have `drwx------` permissions (read, write and execute permissions and no one else has any permissions) on all of those directories.

Because some of these directories are within `Ganache.app`, you may just need to ensure `Ganache.app` has the appropriate read/write/execute permissions.

**Comment by boyuanx** [comment]
@davidmurdoch I've made sure the permissions are in order, but the issue persists.

**Comment by jamesmorgan** [comment]
Its a real pain tbh, is there any resolution to this?

**Comment by davidmurdoch** [comment]
I haven't been able to find a way to work around this (I don't currently have Mac to test on, but am getting one very soon). Once you use `sudo` to open an application the directories and files it touches may have their permissions changed, which is only part of the problem here.

Can you try installing https://github.com/trufflesuite/ganache/releases/tag/v2.1.2-alpha.0 and see if this resolves the problem?

**Comment by jamesmorgan** [comment]
Just tried the latest alpha and the same issue

**Comment by jamesmorgan** [comment]
The last version which works is 1.3.1 for me anyways

**Comment by boyuanx** [comment]
Latest 2.1.2 still has the same problem.

**Comment by christophergunadi** [comment]
Same issue for me.

**Comment by jamesmorgan** [comment]
Is there any solution to this? Seems to be impacting several users and no progress being made?

**Comment by jamesmorgan** [comment]
Is there any solution to this? Seems to be impacting several users and no progress being made?

**Comment by davidmurdoch** [comment]
@jamesmorgan can you try following the steps in the Issue description on: https://github.com/microsoft/vscode/issues/74782?

**Comment by jamesmorgan** [comment]
Hi @davidmurdoch - tried that an no look. I did however managed to get it working this morning by force removing the folder at `~/Library/ApplicationSupport/Ganache` as well as deleting the installing application. After I did both of these I was able to reinstall and it works without using sudo command. 

Feels like something left in the `~/Library/ApplicationSupport/Ganache` was stopping it from launching.

**Comment by davidmurdoch** [comment]
This should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! You might have to delete `~/Library/Application Support/Ganache` and the Application itself in order to restore proper permissions. Please let me know if you are still experiencing problems!
