### ISSUE TITLE
saved work space is not opening

### ISSUE THREAD

**Issue by pavankmr853** [trufflesuite/ganache#1383]
i created a work space in ganache of my project when i created it works good but from day 2 the work space is not opening its just loading but not opening in my pc my work i stopped in the middle of it. see it from last  1 hour, its loading like this only, please sol ve this issue
![2019-08-04](https://user-images.githubusercontent.com/10452082/62420585-4637b280-b6b2-11e9-9f44-14a9c066089a.png)

**Comment by pavankmr853** [comment]
can anyone respond please

**Comment by shawnkd** [comment]
did you find a solution?  i am on macOS with the same issue.

**Comment by davidmurdoch** [comment]
This issue should now be handled properly in the latest beta, https://github.com/trufflesuite/ganache/releases/tag/v2.1.1-beta.3.
