### ISSUE TITLE
Mining spinner should only spin when mining a new block

### ISSUE THREAD

**Issue by madvas** [trufflesuite/ganache#142]
I don't know if this is intentional or bug, but loader is constantly spinning, even if nothing is being loaded. This is pretty annoying to be honest

![image](https://user-images.githubusercontent.com/3857155/33711150-41975a24-db43-11e7-9cbd-8ad4baad2af4.png)

Thank you, UI is otherwise very nice!

**Comment by benjamincburns** [comment]
Thanks for reporting this, @madvas - right now this is intended behaviour, but it's probably an indicator that we only want this animation to happen when we're actually mining a new block.

**Comment by benjamincburns** [comment]
Actually, I didn't mean to close this - will keep it open for the UI improvement

**Comment by vrde** [comment]
Fixing this would also fix #114.

**Comment by seesemichaelj** [comment]
We decided to remove the mining spinner in the upcoming 2.0 release (#1008 removed it).

#1009 is a new issue to determine a better UI/UX for indicating things are happening.
