### ISSUE TITLE
Ganache GUI installation error

### ISSUE THREAD

**Issue by devpavan04** [trufflesuite/ganache#1422]
node version - v8.16.1

followed all the commands :
1. cloned the repo 
2. npm install
3. npm start

I'm getting this :

npm ERR! path /home/pavansoratur/Desktop/ganache-folder/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/pavansoratur/Desktop/ganache-folder/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pavansoratur/.npm/_logs/2019-08-30T12_06_56_092Z-debug.log

**Comment by davidmurdoch** [comment]
Sounds like an npm-related issue. Can you try the tips at: https://github.com/visionmedia/debug/issues/261#issuecomment-207623445 ?

**Comment by devpavan04** [comment]
still throws the same error for me, tried all other ways too. any other reference of this isuue to resolve it?
