### ISSUE TITLE
Ganache generates blocks without an author.

### ISSUE THREAD

**Issue by MicahZoltu** [trufflesuite/ganache#1476]
When fetching a block with `eth_getBlockByNumber('latest')`, ganache will return a block that is missing the `block.author` field.  Such a block is not valid within the Ethereum ecosystem as all blocks have an author.

### Possible Solution
Either use `eth_coinbase` as the author (I believe this is the most correct solution) or at least set it to `0x000...`.

### Context
I have a library that decodes the blocks into a concrete and strongly typed in-memory datastructure and it is failing to decode blocks from ganache due to the missing author.

**Comment by davidmurdoch** [comment]
Thanks Micah. Do you mean `miner` instead of `author`?

**Comment by MicahZoltu** [comment]
https://wiki.parity.io/JSONRPC-eth-module#eth_getblockbynumber
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbyhash

Hmm... auctially, maybe `author` isn't standard... it is part of parity's return, but now that I dig deeper it isn't part of Geth's return.
