### ISSUE TITLE
Release notes tag link is wrong

### ISSUE THREAD

**Issue by wbt** [trufflesuite/ganache#1480]
Under How To Upgrade, the release notes for v2.1.2 say:
>choose the appropriate download binary from the Assets section of the [GitHub release](https://github.com/trufflesuite/ganache/releases/tag/2.1.2).

That link is HTTP 404 because it's missing a v before the version number.
404: https://github.com/trufflesuite/ganache/releases/tag/2.1.2    
200: https://github.com/trufflesuite/ganache/releases/tag/v2.1.2

**Comment by davidmurdoch** [comment]
Fixed! Thank you so much!
