### ISSUE TITLE
npm install && npm start not working, Script "Start" Missing?

### ISSUE THREAD

**Issue by stephenlucas600** [trufflesuite/ganache#1501]
when I ran npm install && npm start, I got "npm ERR! missing script: start"

Was using the 10/30/19 of the developer version of ganache and version 6.12.0 of npm on a Mac Ver 10.11.6

**Comment by alchemist107** [comment]
Can you provide the package.json of your truffle project and which command you have used to create the project cause npm install only install the dependencies of a given node project and npm start cmd runs a script inside called script inside of the package.json

**Comment by stephenlucas600** [comment]
Not sure which package.json. I  did run "npm run dev" and the program did open. I was trying to run "npm install && npm start"  in my copy of the Ganache folder.

**Comment by stephenlucas600** [comment]
was fixed when installing the newest version of ganache.
