### ISSUE TITLE
openzeppelin_kit tutorial - deployed contract does not render on its specific page

### ISSUE THREAD

**Issue by datgrog** [trufflesuite/ganache#1517]
Using ganache GUI, Contract page, click on newly deployed Contract and the it render a blank window.

## Steps to Reproduce

https://github.com/OpenZeppelin/starter-kit-tutorial
**but** instead of #run just:
- start ganache GUI and link to the project `truffle-config.js` and set port to 8545
- `openzeppelin init`
- `openzeppelin compile`
- `openzeppelin create Counter` (with or without calling a fn on the contract instance, it does not change behaviour)

Then go on contract page, see your newly Counter contract and click on it to see the bank page

**Comment by abcoathup** [comment]
Hi @datgrog,

Would you mind posting this question in the OpenZeppelin Community Forum: https://forum.openzeppelin.com/ as this relates to the OpenZeppelin Tutorial Starter Kit.

Thanks.  This issue can then be closed.
