### ISSUE TITLE
Feature-request: add db path to save and restore db

### ISSUE THREAD

**Issue by vsdigitall** [trufflesuite/ganache#152]
Hello, 

Please add db path to application as sometimes people need to keep data on blockchain and restore it when ganache strats.

Thanks a lot!

**Comment by seesemichaelj** [comment]
We implemented this feature in the upcoming version 2.0. While we didn't enable a feature to specify an existing `db_path`, we have introduced workspaces which save their chain state by using the `db_path` option behind the scenes.

If you want to get notified when 2.0 is released, you should checkout Github's new "watch Releases Only option":
![image](https://user-images.githubusercontent.com/549323/49690518-85503c80-fb00-11e8-8104-a954e0410525.png)
You'll get notified when new releases are made if you select that `Releases Only` option. The auto updater should also notify you when a release is ready too!
