### ISSUE TITLE
Running BUGs

### ISSUE THREAD

**Issue by gustavoparedes1978** [trufflesuite/ganache#153]
# Zircon

Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/trufflesuite/zircon/blob/master/.github/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

**Before opening a new issue, you may find an answer in already closed issues**:
https://github.com/trufflesuite/zircon/issues?q=is%3Aissue+is%3Aclosed

## Issue Type

- [ ] Bug (https://github.com/trufflesuite/zircon/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [ ] Feature (https://github.com/trufflesuite/zircon/blob/master/.github/CONTRIBUTING.md#feature-requests)

If your issue is related to building Ganache on your platform, please make sure you have a correctly setup build environment
on your platform, and that you have carefully read any error output for instructions that may fix your situation.

## Description

(Add images if possible - but absolutely no images of terminal output please.)

## Steps to reproduce

(Please be thorough)

# Versions

- Platform: (macOS / Windows / Linux)
- Node:
- Npm:

**Hi, this is what I  get when running "NPM START", I'm not able to watch anything.**
![image](https://user-images.githubusercontent.com/13125861/33900136-20604b4c-df33-11e7-963e-bd7733f40256.png)

node --version v9.2.0
node --version 5.5.1

**Comment by benjamincburns** [comment]
From the console output it appears that you have a syntax error. Check `git diff` to see any modifications you might've inadvertently made.

If you aren't intending to develop or debug ganache, I highly recommend using one of our prebuilt releases from the [release](https://github.com/trufflesuite/ganache/releases) page.
