### ISSUE TITLE
Ensure ganache supports precompiled contracts

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/ganache#154]
A user mentioned in ConsenSys slack that ganache doesn't support the `ecrecover` precompiled contract. My understanding is that precompiled contract support comes "for free" with the ethereumjs-vm, but I realized we don't have any tests which guard this from breaking.

Please also make sure that the precompiled contract addresses behave as expected for RPC calls like `eth_getCode` and the like.

**Comment by balexander4** [comment]
For reference.  https://github.com/ethereum/go-ethereum/issues/16193

**Comment by davidmurdoch** [comment]
@balexander4, have you validated this?

**Comment by seesemichaelj** [comment]
any progress @balexander4?

**Comment by davidmurdoch** [comment]
Closing for issue maintenance :dagger:
