### ISSUE TITLE
System Error when running Ganache 1.0.1 on darwin

### ISSUE THREAD

**Issue by marryton007** [trufflesuite/ganache#155]
Why send below request to ganache, it's crash...

{ 
  "jsonrpc": "2.0", 
  "method": "eth_getBalance", 
  "params": [{
	"from": "0x627306090abaB3A6e1400e9345bC60c78a8BEf57",
  	"to": "0xf17f52151EbEF6C7334FAD080c5704D77216b732",
  	"gas": "0x76c0",
  	"gasPrice": "0x9184e72a000",
  	"value": "0x9184e72a",
  	"data": "0x0"
	}],
  "id": 3 
}

PLATFORM: darwin
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment]
Hi @marryton007 - could you please try this with our latest release, v1.0.2, and raise a new issue if it's still a problem? That release will have better error reporting so that I can actually diagnose the problem.

Thanks!
