### ISSUE TITLE
v2.3.0-beta.1 Windows, event expansion shows blank screen

### ISSUE THREAD

**Issue by fancellu** [trufflesuite/ganache#1573]
Logs show nothing

I have linked to truffle project, I click on an event and it shows a blank screen

![image](https://user-images.githubusercontent.com/4273247/71478688-c806b480-27e8-11ea-8c74-0f1524ca74c5.png)

**Comment by davidmurdoch** [comment]
Fixed in https://github.com/trufflesuite/ganache/commit/f45aeb0b28a4a4e975bcbadabb20189119deff8a
