### ISSUE TITLE
System Error when running Ganache 2.3.0-beta.1 on darwin

### ISSUE THREAD

**Issue by malengatiger** [trufflesuite/ganache#1574]
Trying Ganache with Corda for the first time

PLATFORM: darwin
GANACHE VERSION: 2.3.0-beta.1

EXCEPTION:
```
Error: corda.jar child process exited with code 1
    at e.exports.closeHandler (/webpack:/src/integrations/corda/main/utils/network/corda.js:82:26)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by davidmurdoch** [comment]
Thanks @malengatiger for opening this issue. Does this issue happen on every start up for you?

**Comment by davidmurdoch** [comment]
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
