### ISSUE TITLE
What version of Corda is being/has been launched?

### ISSUE THREAD

**Issue by guyho** [trufflesuite/ganache#1575]
I cannot tell, except from looking in the log files, what version of Corda is running. 

## Expected Behavior
I expect indicators at time of platform choice "Corda vx.x", and after it launches to see somewhere in the screens.
## Current Behavior
No indication of Corda version.

## Steps to Reproduce (for bugs)
Just launch a default Corda network.

## Context
Cannot determine which version of a Cordapp to add if I don't know what version of Corda is running.

## Your Environment
MacOS

**Comment by nicholasjpaterno** [comment]
@guyho Thanks for opening this issue!  Ganache is running corda v4.3 right now.  In future releases you can expect to see the current version indicated clearly within the UI.

**Comment by davidmurdoch** [comment]
Fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.4.0-alpha.0
