### ISSUE TITLE
Splash page isn't clear that there is a Corda choice

### ISSUE THREAD

**Issue by guyho** [trufflesuite/ganache#1578]
Ganache launch makes it appear it's Ethereum specific. At first I thought maybe I had downloaded the wrong Ganache. Then realized it’s a single Ganache with drop down list of choices, but wondered why Corda comes last.

## Expected Behavior
Making it obvious that Ganache is platform agnostic and there are multiple choices.

## Current Behavior
Ethereum is selected by default.

## Possible Solution
Empty set in platform selection, forcing user to select among the choices.

## Steps to Reproduce (for bugs)
Initial launch of Ganache

## Your Environment
MacOS

**Comment by nicholasjpaterno** [comment]
@guyho Thanks for raising this issue.  Ganache has been an Ethereum tool for several years prior to our corda beta that released last week.  Keeping Ethereum as the default option was very much a conscious design decision.  Our current users expect no change in their experience from previous versions of ganache to newer versions of Ganache.  As an extension of this feature, you might have noticed that Ganache will remember your previous selection of Corda on relaunch!  And, as you might expect, upgrading to newer releases of Ganache will remember your flavor of choice.

We're thrilled that you're using our corda flavor and look forward to your continued support in this endeavor!  Im going to close this issue for now.  Thanks again!
