### ISSUE TITLE
No node runtime interaction

### ISSUE THREAD

**Issue by guyho** [trufflesuite/ganache#1579]
How do I interact with the node? No way to launch Corda’s CRaSH shell? After locating the node.conf's I see that no ssh port has been set. Also, how will developers know the rpc user/pwd that is buried in the node.conf? I solved this manually by reading the node.conf and added `sshd { port = 12203}` where I just add 2200 to the rpcSetting.address port (somewhat emulating a default ssh port 22). (Ugh! That didn't work. Apparently "Restart" recreates everything from scratch. So there is no way to restart nodes? Nor a way to modify the <Node name>_node.conf files that the bootstrapper uses to create the nodes?) 

## Expected Behavior
Enough information in the gui to interact with the nodes over both rpc and ssh, which means setting the ssh port and exposing the required user/pwd.

## Current Behavior
No ssh port set. No user/pwd info to the user.

## Possible Solution
Add ssh port into your node.json and notary.json in your templates folder. Also indicate to the Ganahche user in the UI or in a doc what the default rpc user/pwd is.

## Steps to Reproduce (for bugs)
Launch a default Corda workspace configuration and try to interact with the node.

## Context
Unable to interact with the node.

## Your Environment
MacOS

**Comment by davidmurdoch** [comment]
Thanks for this @guyho! This was just an oversight on our part! We'll add the ssh port and make it's config is customizable in a future release.

We'll also make sure to expose the username and password in the UI!

**Comment by davidmurdoch** [comment]
SSH enabled in https://github.com/trufflesuite/ganache/commit/d2001c33907594319b104fd7cd22800312b6af72

SSH and user/password added to the UI in https://github.com/trufflesuite/ganache/commit/679120264265cc839e9e3591a23b27e5229ee0d0

I hope to get another beta out this week or next with many more of the issues you've opened in the release. Thanks!
