### ISSUE TITLE
Corda Node start/stop autonomy

### ISSUE THREAD

**Issue by guyho** [trufflesuite/ganache#1581]
Once a Corda network (workspace) is launched, it's important to permit autonomous node control. This relates to Issue #1579 but here I will separate the "ssh" requirement from the start/stop. While it's extremely helpful to quickly launch a network of nodes, once the nodes are started it is helpful to grant the nodes admin autonomy including starting/stopping. That is especially useful for testing, e.g., testing the scenario, what happens with my Cordapp if the other party is unavailable?

## Expected Behavior
Ability to start/stop nodes individually once the network (workspace) is launched.

## Current Behavior
Restart causes a complete rebuild of the workspace.

## Possible Solution
No specific advice on how to do this. I think a different path than rerunning bootstrapper is needed. Once bootstrapper runs to "seed" the network of node configurations, it is done. Follow-on steps are merely for starting/stopping nodes until the enduser desires to delete that network (workspace).

## Steps to Reproduce (for bugs)
Create a Corda workspace and try to stop and restrart and individual node.

## Context
Individual node control.

## Your Environment
MacOS

**Comment by nicholasjpaterno** [comment]
@guyho Thanks for opening this issue!  Apologies for the late response.  I'll be out of the office until ~Jan 6th so I may be slow to respond until then.  I definitely agree tat ganache needs this feature, and while it is on the roadmap, I'll see what I can do to bump it to a higher priority so we can ship this quicker.

All the best

**Comment by davidmurdoch** [comment]
@guyho, Once a node has been stopped, what mechanism is used to start it again by the node admin?

**Comment by davidmurdoch** [comment]
@guyho, Once a node has been stopped, what mechanism is used to start it again by the node admin?

**Comment by guyho** [comment]
Simply `java -jar corda.jar` from within the directory of each node.

**Comment by davidmurdoch** [comment]
Ah, so it'd be best if we just provided a way to restart the node from the GUI directly. Thanks!

**Comment by davidmurdoch** [comment]
the latest release adds SSH support and exposes the username and password in the UI. 

However, remote shutdown (via SSH or otherwise) will likely cause a crash. It is on my list to gracefully handle node removal and to add a button in the UI to restart the node when it detects that it's been shut down.

Latest release: https://github.com/trufflesuite/ganache/releases/tag/v2.3.0-beta.2

**Comment by guyho** [comment]
Good to see! :) Stay safe out there Dave.

On Mar 24, 2020, at 7:02 PM, David Murdoch <notifications@github.com<mailto:notifications@github.com>> wrote:



Closed #1581<https://github.com/trufflesuite/ganache/issues/1581>.
