### ISSUE TITLE
Error: Cannot find module in C:\Users\User\AppData\Local\Temp\ganache120016-10280-afgrd8.xzq\index.js

### ISSUE THREAD

**Issue by sumreenali** [trufflesuite/ganache#1595]
I am trying to connect my truffle project with ganache GUI but it is not picking up the project, please help

An error occurred while running D:\project\BLOCKCHAIN\election\truffle.js! Did you forget to `npm install` your project?

module.js:550
    throw err;
    ^

Error: Cannot find module 'C:\Users\Sumreen\AppData\Local\Temp\ganache120016-10280-afgrd8.xzq\index.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by davidmurdoch** [comment]
Hey @sumreenali. Make sure you've run `npm install` inside the directory where your truffle project exists (`D:\project\BLOCKCHAIN\election\`). Let me know if that solves the problem for you.

**Comment by davidmurdoch** [comment]
Closing due to no response
