### ISSUE TITLE
FR: eth_fund: a custom RPC method to add arbitrary balance given account address

### ISSUE THREAD

**Issue by xinbenlv** [trufflesuite/ganache#160]
Per https://github.com/trufflesuite/ganache-cli/issues/562#issuecomment-416353312
We would like to suggest implementing a `eth_fund` interface to add arbitrary balance given account address. This will enable downstream features like "faucet". People can then run their own independent testnet completely with ganache-cli without needing to restart instance to get and change more ETH.

**Comment by haltman-at** [comment]
Note: this would probably done instead by adding optional parameters to `evm_mine`, to control the block reward and coinbase.

**Comment by davidmurdoch** [comment]
You can now do this via `evm_setAccountBalance`
