### ISSUE TITLE
Code 137: System Error when running Ganache 2.3.0-beta.1 on linux

### ISSUE THREAD

**Issue by munivk** [trufflesuite/ganache#1600]
I  tried to run the Ganache for the first time (with several attempts), I get the following error. Please have a look. The details are  below.

PLATFORM: linux
GANACHE VERSION: 2.3.0-beta.1

EXCEPTION:
```
Error: corda.jar child process exited with code 137
    at e.exports.closeHandler (/webpack:/src/integrations/corda/main/utils/network/corda.js:82:26)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by davidmurdoch** [comment]
Exit code `137` appears to be an "Out of Memory" error. Corda nodes consume roughly 1GB of memory each. Is it possible you ran out of memory?

**Comment by davidmurdoch** [comment]
Closing due to no response
