### ISSUE TITLE
MacOS 10.14.5: Ganache 2.1.2 or below GUI starts up but won't display a screen

### ISSUE THREAD

**Issue by santdeleon** [trufflesuite/ganache#1603]
Downloaded Ganache 2.1.2. Everything downloads correctly but when I open the app, it opens with no GUI shown. Checking the activity monitor, it also shows Ganache and various Ganache helpers running.

There are also no other open windows hiding the GUI.

<img width="1440" alt="Screen Shot 2020-01-27 at 7 34 47 PM" src="https://user-images.githubusercontent.com/22578527/73228525-75e4e600-413c-11ea-91f2-2ad4fa861a93.png">

**Comment by davidmurdoch** [comment]
@santdeleon, what OS version are you on?

**Comment by santdeleon** [comment]
@davidmurdoch Hey David, i'm on Mojave 10.14.5

**Comment by santdeleon** [comment]
Issue Resolved:

To anyone who experiences the same issue in the future.. My instance of Ganache GUI stopped working properly after excessive logging of unit tests of my truffle project. Initially the Ganache GUI froze and then became unresponsive altogether.

Reinstalling the app didn't work. To fix this issue I went into my **/Library** folder and deleted any folders or files **related** to Ganache or trufflesuite (This may be a step you want to take with caution) but for me it was not an issue. This includes **.plist** files, files with in the **/Caches** folder and most importantly (for me) the **/Application Support** folder. 

Hope this helps.
