### ISSUE TITLE
NO PROJECTS IN WORKSPACE displayed on the Contracts tab

### ISSUE THREAD

**Issue by DontCallMeLarry** [trufflesuite/ganache#1614]
I've successfully migrated a project and can see the transactions but the contracts tab does claims there are no projects in the workspace.

## Steps to Reproduce (for bugs)
Work through any HelloWorld tutorial. 

## Your Environment

* Version used: v2.3.0-beta.2
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Operating System and version: Windows 10, npm 6.13.7, node v13.7.0

**Comment by SvenMeyer** [comment]
I had problems with the 'CONTRACTS' page as well, see 
- https://github.com/trufflesuite/ganache/issues/1616
- https://github.com/trufflesuite/ganache/issues/1617
- and I just had another issue with v2.1.2 Appimage on Linux (which was the only recent version I could get to work with 'CONTRACTS' page displaying something when **not** using the 'Quickstart) : suddenly my deployed contract were not displayed any more at all, just some other not deployed ones. I will post an issue if that happens again and I can better describe the circumstances.

**Comment by davidmurdoch** [comment]
Fixed by 73a5df8abf3d8378cbaac2ba69768b57147d14a9
