### ISSUE TITLE
System Error when running Ganache 2.3.0-beta.2 on linux - Crash after chosing Quickstart

### ISSUE THREAD

**Issue by SvenMeyer** [trufflesuite/ganache#1619]
PLATFORM: linux
GANACHE VERSION: 2.3.0-beta.2

- started the Appimage
- chose [new workspace]
- got a blank screen (ERROR)
- closed Windows

Maybe the AppImage still had the old state (CONTRACTS page = blank) from one of the other versions / issues ? (https://github.com/trufflesuite/ganache/issues/1616 and/or https://github.com/trufflesuite/ganache/issues/1617)

- started the Appimage again
- chose [Quickstart]
- CRASH

EXCEPTION:
```
Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at Server.close (net.js:1517:12)
    at Object.onceWrapper (events.js:288:20)
    at Server.emit (events.js:205:15)
    at emitCloseNT (net.js:1570:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by davidmurdoch** [comment]
Should be fixed in https://github.com/trufflesuite/ganache/releases/tag/v2.3.0! Please let me know if you are still experiencing problems!
