### ISSUE TITLE
Erroneous transaction

### ISSUE THREAD

**Issue by BudVic** [trufflesuite/ganache#1654]
Good afternoon!
I made a global error when I wanted to test local sending of ether in my system, I did not switch the sending source from the real wallet to the local one and sent it to the wallet 0x994ba537fA20e13c996954d1A0286e7c9170181a  - 7.106511852580896768 Ether . I really hope that you, as the developers who placed these addresses in the ganache app, have access to this wallet and can help me with the refund of my funds. I will be very grateful to you for any help!

**Comment by davidmurdoch** [comment]
If you still have access to the Ganache workspace that automatically and randomly generated those addresses specifically for you, you can copy the private key for the address from within Ganache and use it to import that account into your own wallet.

Let me know if you have questions!

**Comment by BudVic** [comment]
Thank you very much! I was able to get my money back! Still, the amount is not small, very worried! God grant you health)

**Comment by BudVic** [comment]
> If you still have access to the Ganache workspace that automatically and randomly generated those addresses specifically for you, you can copy the private key for the address from within Ganache and use it to import that account into your own wallet.
> 
> Let me know if you have questions!

Thank you very much! I was able to get my money back! Still, the amount is not small, very worried! God grant you health)
