### ISSUE TITLE
Mac error: "Disk image cannot be opened: Corrupt image"

### ISSUE THREAD

**Issue by vedtam** [trufflesuite/ganache#167]
Hi, 

Just downloaded the desktop installer for mac, while trying to open the image after downloading the following popup shows up and stops the install process:

![screen shot 2017-12-17 at 14 28 28](https://user-images.githubusercontent.com/4981592/34079477-f6e58504-e336-11e7-9cc9-1c760690979e.png)

System used:
imac, osx 10.10.5

Regards.

**Comment by bmmpxf** [comment]
Hi @vedtam . Please try downloading again. Perhaps the download cut out halfway through. The file should be 82.2MB. If you still get the same issue, let us know and we'll investigate.

**Comment by okalex** [comment]
I was getting this error consistently on OS X Yosemite. Upgraded to High Sierra and the problem went away.

**Comment by ajhurliman** [comment]
Same experience as okalex; was getting this bug on Yosemite, upgrading to High Sierra fixed it.

**Comment by msp** [comment]
Same with Ganache-1.1.0-beta.0 (88.3 MB) and Ganache-1.0.2 (90.7 MB). I'm on OS X 10.10.5 also. So 10.11 is minimum spec required? Can't upgrade immediately :(

**Comment by sargonpiraev** [comment]
+
