### ISSUE TITLE
System Error when running Ganache 1.0.1 on Linux 4.13.12-1-ARCH

### ISSUE THREAD

**Issue by xoryouyou** [trufflesuite/ganache#168]
Running Truffle Test with a few mocha tests, always gives this Error.

PLATFORM: Linux 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux
NODE VERSION: v9.2.0
NPM VERSION: 5.6.0
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment]
Thanks for reporting this. The lost heartbeat crash should be fixed as of our latest release, v1.0.2, which is out just now!

Unfortunately, you may also be running afoul of trufflesuite/ganache-core#417. I'd suggest subscribing to that case for updates.
