### ISSUE TITLE
I am having issues running truffle test and keep on getting "No events were emitted"

### ISSUE THREAD

**Issue by drao13** [trufflesuite/ganache#1696]
<img width="566" alt="Screen Shot 2020-04-06 at 12 52 47 AM" src="https://user-images.githubusercontent.com/49698884/78524155-21e02880-77a1-11ea-854f-927f807280ce.png">
 

It should just pass all three but here it is clearly passing just two

Cant tell what is really wrong here:

var DappToken = artifacts.require("./DappToken.sol");

contract('DappToken', function(accounts) {
    var tokenInstance;

    it('The right values are assigned', function() {
        return DappToken.deployed().then(function(instance) {
            tokenInstance = instance;
            return tokenInstance.name();
        }).then(function(name) {
            assert.equal(name, 'Token', 'Correct Name');
            return tokenInstance.symbol();
        }).then(function(symbol) {
            assert.equal(symbol, 'TOKEN', 'Correct Symbol');
            return tokenInstance.standard();
        }).then(function(standard) {
            assert.equal(standard, 'Token Version 1', 'Correct Standard');
    });
        });

    it('Tokens is set upon Deployment', function() {
        return DappToken.deployed().then(function(instance) {
            tokenInstance = instance;
            return tokenInstance.tokens();
        }).then(function(tokens) {
            assert.equal(tokens.toNumber(), 1000000, 'Tokens is set to 1,000,000');
            return tokenInstance.balanceOf(accounts[0]);
        }).then(function(MyBalance) {
            assert.equal(MyBalance.toNumber(), 1000000, 'Starting Supply to MyBalance');
        });
    });

    it('Tokens Transferred', function() {
        return DappToken.deployed().then(function(instance) {
            tokenInstance = instance;

        return tokenInstance.transfer.call(accounts[1], 99999999999999999999999999999);
    }).then(assert.fail).catch(function(error) {
      assert(error.message.indexOf('revert') >= value, 'Error message must contain revert');
    })
});
        });

pragma solidity >=0.4.2;

contract DappToken {

string public name = "Token";
string public symbol = "TOKEN";
string public standard = "Token Version 1";

    uint256 public tokens;

    mapping(address => uint256) public balanceOf;

    constructor(uint256 StartingSupply) public {
        balanceOf[msg.sender] = StartingSupply;
        tokens = StartingSupply;
    }

    function transfer(address to, uint256 value) public view returns (bool works) {
        require(balanceOf[msg.sender] >= value);
    }
}

What changes can I make to this, to pass it?

**Comment by davidmurdoch** [comment]
Can you try a number smaller than `Number.MAX_SAFE_INTEGER` (`9007199254740991`)? `99999999999999999999999999999` is too large a number for JavaScript's number type.

**Comment by drao13** [comment]
> Can you try a number smaller than `Number.MAX_SAFE_INTEGER` (`9007199254740991`)? `99999999999999999999999999999` is too large a number for JavaScript's number type.

It still doesnt work :/

**Comment by gnidan** [comment]
Looks like you have a `value` variable in your assert statement that's not defined

**Comment by drao13** [comment]
> Looks like you have a `value` variable in your assert statement that's not defined

How would that look like? and where is that variable thats not assigned?

**Comment by drao13** [comment]
How would that look like? and where is that variable thats not assigned?

**Comment by gnidan** [comment]
At the very end:
```
}).then(assert.fail).catch(function(error) {
  assert(error.message.indexOf('revert') >= value, 'Error message must contain revert');
})
```

`value`  there is not defined. I think just replace that with `0`

**Comment by drao13** [comment]
Thank you that works!
