### ISSUE TITLE
Truffle Integration process exited prematurely due to signal 'SIGSEGV'.

### ISSUE THREAD

**Issue by HolmanHuang** [trufflesuite/ganache#1700]
when i execute the command "nmp run dev", i got this information.

      Entrypoint mini-css-extract-plugin = *
      [./node_modules/css-loader/dist/cjs.js?!./node_modules/sass-loader/dist/cjs.js!./src/renderer/styles/normalize.scss] ./node_modules/css-loader/dist/cjs.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js!./src/renderer/styles/normalize.scss 8.44 KiB {mini-css-extract-plugin} [built]
      [./node_modules/css-loader/dist/runtime/api.js] 2.61 KiB {mini-css-extract-plugin} [built]

┏ Renderer -------------------

  ℹ ｢wdm｣: Compiled successfully.

┗ ----------------------------
┏ Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/0c61e7d1-649e-4190-a7a8-acb798b52e37
  For help, see: https://nodejs.org/en/docs/inspector

┗ ----------------------------
┏ Electron -------------------
### 
  **Truffle Integration process exited prematurely due to signal 'SIGSEGV'.**

┗ ----------------------------

 

## Expected Behavior

I expect the command should running correctly.

## Current Behavior

but this error come and the program is stopped.

## Steps to Reproduce (for bugs)

1. git clone
2. npm install --> success
3. npm run dev -> error happen
4.

## Your Environment

* Version used:
> ganache@2.2.1-internal.3 dev /home/king/projects/ganache
   Version: webpack 4.41.0
   npm --version 6.14.4
   node --version v10.15.2
   uname -a Linux debian 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

**Comment by davidmurdoch** [comment]
Try updating to node to v12.9.0, then remove your `node_modules` folder in the root, as well as in `./static/node/`
