### ISSUE TITLE
Cannot run Ganache in Linux Ubuntu

### ISSUE THREAD

**Issue by leeboss82** [trufflesuite/ganache#1701]
Hi,

I cannot run Ganache 2.1.2.  I'm using an Ubuntu Linux virtual drive with VirtualBox.  I've checked "allow executing file as program" in permissions.  I've also tried running it through the terminal.  I've also tried downloading "appimagelauncher" but that didn't work either.  Nothing happens when I double click, or if I right-click and select "run."

I did have Ganache working in Windows 7 before I started using Ubuntu.  I've uninstalled it from windows, but I'm not sure if this is causing a problem running it in Linux.  Please help!

-Lee

 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by davidmurdoch** [comment]
When you run it from the command line do you get any output?

**Comment by leeboss82** [comment]
No, nothing happens.  I navigate to the Downloads folder, then type
chmod a+x ganache-2.1.2-linux-x86_64.AppImage

**Comment by leeboss82** [comment]
Got it,

First moved I moved the AppImage file to the Applications folder, then checked "allow executing file as program" in permissions

then navigated to the Applications folder in the terminal, and entered this...
./ganache-2.1.2-linux-x86_64.AppImage

then I got this...
/tmp/.mount_ganachEpkTm2/Ganache: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory

to solve that I did this...
sudo apt install libgtk2.0-0:i386

then entered this again and it worked!
./ganache-2.1.2-linux-x86_64.AppImage
