### ISSUE TITLE
running testrpc and ganache at the same time

### ISSUE THREAD

**Issue by bruciebruce** [trufflesuite/ganache#171]
This is a general question...
I want to run the 'old' testrpc and have the 'new' ganache attach to the blockchain created by testrpc.  How can I do this?

**Comment by bruciebruce** [comment]
Not important at this time.

**Comment by benjamincburns** [comment]
The forking feature in `ganache-cli` is not yet available in the Ganache UI. This will take us some time, because we need to make it possible/efficient to display the forked chain.
