### ISSUE TITLE
Wrong return value for web3.eth.call() when running with --fork

### ISSUE THREAD

**Issue by nikita-fuchs** [trufflesuite/ganache#173]
## Issue Type
- [x] Bug 

## Description

When `--fork`ing and performing `web3.eth.call()` on a non-latest block, data from the latest block is being returned.

## Steps to reproduce

1.
```
 ganache-cli -f https://mainnet.infura.io/:yourApiKeyOptional

blocks = [4741999, 4742245];
```

2. 
 ```

//prepare the data
var address = "0x748fb0064c4238c447e6b8d0b99fefcbc6c6fb21"
var theContractAddress = "0xd780ae2bf04cd96e577d3d014762f831d97129d0"
var theData = "0x9b96eece000000000000000000000000" + address.substr(2);

        var theCallObject= {
            data: theData,
            to: theContractAddress
        }

//perform the call
        web3.eth.call(theCallObject, blocks[0|1], function(error, result){
            if (error) {
                console.log("Failed");
                reject(error);
            } else {
                //console.log("Success !!");
                let theResult = hexToDec(result);
                //console.log(theResult);
                resolve(theResult);
            }
        })

```
When directly setting infura as the web3 provider, `theResult` will be different for the two blocks, whereas ganache returns always the latest value, no matter which blocknumber you provide.

# Versions
6.0.3 (core 2.0.2)

- Platform: Ubuntu
- Node: 7.0.0
- Npm: 3.10.8

**Comment by benjamincburns** [comment]
Hi @nikita-fuchs! Thanks for reporting this. Unfortunately, I think it duplicates trufflesuite/ganache-cli#249. If you disagree please let me know and I'll be happy to reopen and investigate further.
