### ISSUE TITLE
Not a bug- Trouble finding terminal commands for Ganache/Linux.

### ISSUE THREAD

**Issue by metaverde** [trufflesuite/ganache#1753]
I always have trouble finding the commands to use the terminal to run Ganache 
 If the commands are on the Ganache page at Truffle suite, I can't ever seem to find them,
and I know it's my own fault for not saving them where I can find them or for not using Ganache more often,

But it would sure be swell if there were a list of commands I could find handily.

Thank-you for all you do.

**Comment by davidmurdoch** [comment]
Ganache UI can't be configured from the terminal.

If you are using [ganache-cli](https://github.com/trufflesuite/ganache-cli) you can view the documentation in the [README.md](https://github.com/trufflesuite/ganache-cli/blob/develop/README.md) or run `ganache-cli --help` in your terminal.
