### ISSUE TITLE
Windows 10  defender blocks Ganache.appx as possible trojan

### ISSUE THREAD

**Issue by ETHMOONBASE** [trufflesuite/ganache#176]
Im sure this is in error, but why would defender think this?

**Comment by benjamincburns** [comment]
Thanks for telling us about this, @ETHMOONBASE! Virus detection is an exercise in pattern matching, and unfortunately false positives are far more common than anyone would like. We've had at least one similar false positive report over on `ganache-cli`. Given the way we build and distribute releases it seems quite unlikely that something would've become infected downstream, as this would have broken the application signature.

Still, we'll have a look just to make sure there's no funny business going on.

**Comment by ETHMOONBASE** [comment]
oh well i just did my usual logic in my head and installed it anyway

"hmm well the github has tons of forks and there are >100 issues, none of which are people saying they were hacked"

so i just installed it

**Comment by ETHMOONBASE** [comment]
but of course now im getting the same crash error when signing a contract  as everyone else.

**Comment by benjamincburns** [comment]
@ETHMOONBASE we have a bounty open for that: see trufflesuite/ganache-cli#450

**Comment by ETHMOONBASE** [comment]
Yea, i double  checked my code was correct, i even tried deploying other contracts bytecodes already existing on the eth network so i know its not a programming error.

This essentially renders the entire application useless, and it seems to be affecting nearly most people using this.

Any idea how to troubleshoot?

**Comment by ETHMOONBASE** [comment]
Actually I found a work around by setting automine to 60 seconds, deploying the contract right after. then it went through fine.

**Comment by benjamincburns** [comment]
I think I misunderstood the problem you were having before - I'm not aware of any issues having been reported which are specific to contract signing. Could you raise one for me w/ some simple repro steps and I'll have a look?

**Comment by benjamincburns** [comment]
@ETHMOONBASE does this still happen for you with v1.0.2? If not, can you please close this issue?

**Comment by benjamincburns** [comment]
I've scanned v1.0.2 with Windows Defender (Antivirus version 1.259.1531.0) and it reports no threats.
