### ISSUE TITLE
how to connect ganache to json rpc?

### ISSUE THREAD

**Issue by js-abc007** [trufflesuite/ganache#1760]
how to connect ganache to json rpc?

**Comment by davidmurdoch** [comment]
Ganache doesn't _send_ Ethereum JSON RPC commands, it acts as a server that receives them. Ganache acts as a personal/local Ethereum node. Check out https://www.trufflesuite.com/docs/truffle/overview for information on how you can interact with an Ethereum node, like Ganache.

If you just want to send an RPC command via the command line to a running Ganache UI instance you can do so using curl (available on linux and mac). Here is an example:

```shell
curl -H "Content-Type: application/json" -X POST --data '{"id":1,"jsonrpc":"2.0","method":"eth_accounts","params":[]}' http://localhost:7545
```
