### ISSUE TITLE
Update Ganache to use websockets support from ganache-core

### ISSUE THREAD

**Issue by nisdas** [trufflesuite/ganache#178]
For most of the event logging facilities in Web3 using Http has been deprecated. The only way to use them has been through a websockets port.  I have not seen anything that allows a connection over websockets instead of http. Are there any plans to add it soon ?

**Comment by benjamincburns** [comment]
This depends on trufflesuite/ganache-cli#257. Once that issue is fixed, we'll be able to update ganache's dependency on ganache-core, and websockets will be available with very minimal code change. I'm hoping this work will be on branch in the next week or so.

**Comment by benjamincburns** [comment]
This is actually duplicating trufflesuite/ganache-cli#457. @nisdas please track that issue for progress updates.

**Comment by nisdas** [comment]
@benjamincburns Alright,  sure thing.
