### ISSUE TITLE
Restarting a workspace doesn't reset account balances

### ISSUE THREAD

**Issue by superkruger** [trufflesuite/ganache#1826]
## Expected Behavior
When restarting a workspace, I expect the account balances to be reset to 100 ETH

## Current Behavior
Account balances stay as they are

## Context
When developing and testing, you're always depleting account balances.
It's a pain to have to create new workspaces and configure new accounts each time you want to run tests in your dev environment

## Your Environment
* Version used: 2.4.0
* Operating System and version: MacOS 10.15.4

**Comment by chrc** [comment]
Question : What is the task of `RESTART` button?

**Comment by superkruger** [comment]
@chrc Perhaps you didn't read properly...
"When restarting a workspace..."

**Comment by chrc** [comment]
@superkruger 
Sorry, I thought you were talking about restarting workspace from the ganache deskstop
<img width="1297" alt="Capture d’écran 2020-07-10 à 21 27 52" src="https://user-images.githubusercontent.com/88607/87191398-a092b780-c2f4-11ea-9278-82eedcac8f35.png">
.

**Comment by chrc** [comment]
See #1275

**Comment by superkruger** [comment]
@chrc Thanks. I remember it used to work this way previously. (Like the --deterministic flag in the cli).
Anyway, closing this one as there's a duplicate.

Cheers
