### ISSUE TITLE
hd path unclear and possibly doesn't exist

### ISSUE THREAD

**Issue by jordanglassman** [trufflesuite/ganache#193]
Is this a relative path to something?

![image](https://user-images.githubusercontent.com/1238718/34384623-533a6e30-eaeb-11e7-9296-92b00e0eaa59.png)

find can't find it:

```
$ find / -name "*account_index*" 2>/dev/null
$
```

## Expected Behavior
If this is a path to something on my HD, it should be more clear what/where it is.

## Current Behavior
Not sure what it's pointing to, or if it exists at all.

## Your Environment
ganache 1.0.1
```
$ uname -a
Darwin Jordans-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by bmmpxf** [comment]
Hi @jordanglassman . You would certainly be forgiven for thinking that "HD" and "path" are referring to a path on your hard drive, but HD actually stands for "hierarchical deterministic". It refers to the type of generated list of accounts that show up in Ganache (as they are all generated from the mnemonic).

The structure is:

```
m / purpose' / coin_type' / account' / change / account_index 
```

So, for Ganache:
```
m/44'/60'/0'/0/account_index
```

`44` means that it follows the standard (linked below), while `60` refers to Ethereum (as opposed to another coin type). Typically, the other two numbers are `0` with Ethereum.

You can read more about this path in the following documents:

[BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)
[BIP43](https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki)
[BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) (This is where the `44` comes from, though it's only stated as such in BIP43.)

Hope this helps. I'm going to close this issue, but if you have follow up questions on this, please feel free to ask here.
