### ISSUE TITLE
Confusing Menu button[minor][ui]

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/ganache#20]
# Minor UI style issue 
<img width="138" alt="screen shot 2017-06-01 at 8 07 45 pm" src="https://cloud.githubusercontent.com/assets/9360827/26709249/33812716-4706-11e7-9f87-26ab4e7b4162.png">

Since Menu is not a button, I believe it should have a different style. Otherwise, my first impression was that it's a button, not a label

**Comment by johnmcdowall** [comment]
Closing for #24
