### ISSUE TITLE
Cannot view previous blockhash in constant function.

### ISSUE THREAD

**Issue by beether** [trufflesuite/ganache#205]
block.blockhash(<previous block>) will not work from a constant function. It does work from within a transaction, though.

Note: `block.blockhash(block.number-1)` will work, but that is because `block.number` refers to the latest block, and not the next block. The expected behavior is for `block.number` to refer to the next block, even from within constant calls.

See #204

**Comment by benjamincburns** [comment]
Thanks for reporting! This will be fixed in the next release.
