### ISSUE TITLE
System Error when running Ganache 1.0.1 on darwin

### ISSUE THREAD

**Issue by mandys** [trufflesuite/ganache#208]
When I leave Ganache running on my Mac and step out for sometime the Mac goes into sleep mode.

On returning, I always see this error which requires me to restart it.

Not an issue ( just inconvenient ) but couple with Metamask bugs this is a major issue.

I need to uninstall and reinstall metamask as on restarting Ganache new accounts are generated and Metamask gets confused and unless reinstalled doesn't work.

So, seems like every day I need to restart Ganache and reinstall Metamask several times.

Thanks.

PLATFORM: darwin
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by benjamincburns** [comment]
Thanks for reporting this. The lost heartbeat crash (especially on sleep/wake) should be fixed as of our latest release, v1.0.2, which is out just now!
