### ISSUE TITLE
Ganache can't be opened because it's from an unidentified developer

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/ganache#21]
Adding this here for tracking purposes:

<img width="445" alt="screen shot 2017-06-02 at 8 18 49 am" src="https://cloud.githubusercontent.com/assets/92629/26732359/36d18f30-476c-11e7-8408-6951f1a1f9fe.png">

Not sure what we need, but if it costs money I/we can pay it and expense it.

**Comment by johnmcdowall** [comment]
Closing in favour of #30
