### ISSUE TITLE
win64 GUI - New Install doesn't override the old version

### ISSUE THREAD

**Issue by drbullock** [trufflesuite/ganache#2124]
## Expected Behavior
After installing the new version, it will override the old version, so only one version of Ganache is available

## Current Behavior
After installing the new version, In Windows Start only the old version is visible.

## Possible Solution
Delete the old Version of Ganache before or after installing the new Version

**Comment by davidmurdoch** [comment]
What two versions do you have installed?

**Comment by drbullock** [comment]
`Ganache-2.4.0-win-x64` and `Ganache-2.5.4-win-x64`

**Comment by davidmurdoch** [comment]
Is it possible one of your installations is the .exe version, and the other the .appx? These are separate installation technologies that would allow you to install both types simultaneously.

**Comment by drbullock** [comment]
Yes, I think that is the case, I just remember now that I have downloaded different installations of GUI because I had a problem installing it weeks ago. I think you can close this for now :)
