### ISSUE TITLE
Am I missing required fonts?

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/ganache#22]
It looks like I could be missing some fonts, or they're not loading for some reason. 

<img width="264" alt="screen shot 2017-06-02 at 8 24 08 am" src="https://cloud.githubusercontent.com/assets/92629/26732680/456fcd62-476d-11e7-8a87-e4e4d059b903.png">

**Comment by johnmcdowall** [comment]
@tcoulter What platform?

**Comment by tcoulter** [comment]
OS X

**Comment by johnmcdowall** [comment]
Very strange. Looks like some styling is not loading as the checkbox should be a slider, not just a native element...

**Comment by johnmcdowall** [comment]
Closing in favour of #33
