### ISSUE TITLE
Can't run Ganache on Win7

### ISSUE THREAD

**Issue by mveljko78** [trufflesuite/ganache#221]
Is it possible to create a Win7 executable? 
Appx files cannot be installed on Win7

**Comment by benjamincburns** [comment]
Sorry, but for now I'm afraid we only distribute Windows binaries for Windows 10. If you'd like to take a crack at building it yourself, you may still be able to get it running.

**Comment by mveljko78** [comment]
I'd like to try! I assume there isn't anything Win8 specific about Ganache that cannot run on Win7 ... Is there some documentation where I can  see what goes into Ganache build? Then I can make auto installer  for Win7.

**Comment by benjamincburns** [comment]
@mveljko78 Please check the `README.md` and the `scripts` in `package.json`. It's all in there.

**Comment by benjamincburns** [comment]
@mveljko78 - sorry - I forgot to mention that you should still be able to clone and build locally...

If you want a one-liner for that, `git clone git@github.com:/trufflesuite/ganache; cd ganache; npm install -g windows-build-tools; npm install; npm start` ought to do it.

**Comment by BelieveCoin** [comment]
you fucken assholes im trying to create a new bitcoin on my windows 7 and i cant. fuck ganache!!!!!

**Comment by BelieveCoin** [comment]
DAMNITTTTTT i dont have windows 8!!!!
