### ISSUE TITLE
Change ETH name in a forked private blockchain

### ISSUE THREAD

**Issue by yehia67** [trufflesuite/ganache#2219]
Hey,
I want to fork mainnet using ganache then rename the "ETH " & "ether" currency to anything else. Is that possible in ganache? if no is that even possible in general? 
Thanks in advance.

**Comment by davidmurdoch** [comment]
No, that is not possible without editing the Ganache application itself; these values are [hardcoded into the UI](https://github.com/trufflesuite/ganache/blob/b69c2ca3aba44551fe66b0166f0c540b1edfe764/src/integrations/ethereum/renderer/components/formatted-ether-value/FormattedEtherValue.js#L30).
