### ISSUE TITLE
How to change host and port before launching

### ISSUE THREAD

**Issue by mlennie** [trufflesuite/ganache#229]
I updated the host and port and now I'm getting the following errors. I'm using `Ubuntu`

```
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/tmp/.mount_ganach0rQujE/app/resources/app/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

```

I would like to change the host and port back to original settings before launching the appImage. Where can I update these settings without having the app launched?

Where does the ganache GUI store the host and port before it restarts?

**Comment by mlennie** [comment]
I found it in `~/.config/Ganache/Settings` Works now

**Comment by benjamincburns** [comment]
@mlennie thanks for posting your fix here! If you wanted to submit a PR to add this to the `README.md` that'd be amazing.
