### ISSUE TITLE
Trouble With Installation on Mac OS

### ISSUE THREAD

**Issue by ClairvoyantAlliance** [trufflesuite/ganache#2290]
<!-- found 0 vulnerabilities
$ npm install -g truffle
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 144 packages, and audited 145 packages in 12s

37 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by ClairvoyantAlliance** [comment]
found 0 vulnerabilities
Glenns-MacBook-Pro:~ glennmlittleii$ npm install -g truffle
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

added 144 packages, and audited 145 packages in 12s

37 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by davidmurdoch** [comment]
What's the problem?

**Comment by ClairvoyantAlliance** [comment]
$ npm install -g truffle
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

changed 144 packages, and audited 145 packages in 14s

37 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


This is the issue the program Truffle will not install due to deprecated warnings ?? Could really use some help here with this small issue.

npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

**Comment by ClairvoyantAlliance** [comment]
@davidmurdoch Truffle is not installing successfully on my mac. I am assuming there is something I must fix internally or maybe I am just green to this whole front end code process.

**Comment by ClairvoyantAlliance** [comment]
@davidmurdoch I will give a $20 credit to my website [www.clairvoyantalliance.art ](url) for the 1st person to help me fix this.

**Comment by davidmurdoch** [comment]
That message doesn't list any errors; it appears to be installing just fine to me.

Also, this is the ganache repo, not the truffle repo. You might want to head over to https://github.com/trufflesuite/truffle

**Comment by ClairvoyantAlliance** [comment]
Hmm.... I must be an idiot. Because when I go to open truffle it doesn't work.

**Comment by davidmurdoch** [comment]
What happens when you type `truffle --version` on the command line?

**Comment by ClairvoyantAlliance** [comment]
When I typed this into the command line. >>> -bash: truffle: command not found

**Comment by davidmurdoch** [comment]
What version of node are you using?

**Comment by ClairvoyantAlliance** [comment]
This is what is coming up when I search node.. 

node: '14.15.4'

**Comment by ClairvoyantAlliance** [comment]
Double checked version.. node: '14.15.4' Confirmed...

**Comment by davidmurdoch** [comment]
can you paste the complete output when you run in a single terminal command:

`npm --version && node --version && npm uninstall -g truffle && npm install -g truffle@latest && truffle version`

**Comment by ClairvoyantAlliance** [comment]
Alright here is what I am seeing now... Still not sure what step is next.
Any help is greatly appreciated .. !! This is such a pain in my neck.


npm --version && node --version && npm uninstall -g truffle && npm install
-g truffle@latest && truffle version

6.14.10

v14.15.4

removed 144 packages in 1.286s

npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4
<4.3.1 have a low-severity ReDos regression when used in a Node.js
environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (
https://github.com/visionmedia/debug/issues/797)

npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"

/Users/glennmlittleii/.npm-global/bin/truffle ->
/Users/glennmlittleii/.npm-global/lib/node_modules/truffle/build/cli.bundled.js


> truffle@5.1.62 postinstall
/Users/glennmlittleii/.npm-global/lib/node_modules/truffle

> node ./scripts/postinstall.js


- Fetching solc version list from solc-bin. Attempt #1

+ truffle@5.1.62

added 144 packages from 66 contributors in 13.91s



   ╭─────────────────────────────────────────────────────────────────╮

   │                                                                 │

   │      New patch version of npm available! 6.14.10 → 6.14.11      │

   │   Changelog: https://github.com/npm/cli/releases/tag/v6.14.11   │

   │                Run npm install -g npm to update!                │

   │                                                                 │

   ╰─────────────────────────────────────────────────────────────────╯


-bash: truffle: command not found

**Comment by davidmurdoch** [comment]
I'm going to venture a guess that your `npm` is misconfigured and all global npm installs don't work for you?

Maybe try uninstalling node from your system, and then use use [nvm](https://github.com/nvm-sh/nvm) to install it going forward.

I don't think this is a Truffle issue, but if you still think it is let me know and i'll transfer this issue to the Truffle repository, otherwise I'll close it.

**Comment by ClairvoyantAlliance** [comment]
Hey Y'all !!! I figured it out !!! Coding world hurrrrr I come !!!!

**Comment by ClairvoyantAlliance** [comment]
NPM was in a weird place.... Created reroute Path to fix the issue. Truffle is looking sexy.
