### ISSUE TITLE
System Error when running Ganache 1.0.1 on win32 - windows installer

### ISSUE THREAD

**Issue by printlnBTC** [trufflesuite/ganache#230]
Using Windows Installer.
-Create code in Remix
-Use myetherwallet
-Attempt to deploy contract
-The instance I deploy Ganache crashes.  
-Uninstall/reinstall
-Same issue

Previously the same sequence was working.
------------------- bytecode
6908373ffffffffffffffffffffffffffffffffffffffff16021790555081600060146101000a81548161ffff021916908361ffff1602179055506001600060166101000a81548160ff021916908315150217905550600090505b8161ffff168161ffff1610156101ac57600180548060010182816100ce91906101b3565b916000526020600020906003020160006060604051908101604052807f454d505459000000000000000000000000000000000000000000000000000000600019168152602001600073ffffffffffffffffffffffffffffffffffffffff168152602001600081525090919091506000820151816000019060001916905560208201518160010160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff1602179055506040820151816002015550505080806001019150506100aa565b505061023b565b8154818355818115116101e0576003028160030283600052602060002091820191016101df91906101e5565b5b505050565b61023891905b80821115610234576000808201600090556001820160006101000a81549073ffffffffffffffffffffffffffffffffffffffff02191690556002820160009055506003016101eb565b5090565b90565b6104418061024a6000396000f30060606040526004361061006d576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806307da68f5146100725780636235781c14610087578063b1b0be2f14610100578063be9a65551461012d578063e0a41cf214610142575b600080fd5b341561007d57600080fd5b6100856101b2565b005b341561009257600080fd5b6100a8600480803590602001909190505061022b565b6040518084600019166000191681526020018373ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff168152602001828152602001935050505060405180910390f35b341561010b57600080fd5b610113610284565b604051808215151515815260200191505060405180910390f35b341561013857600080fd5b61014061029a565b005b341561014d57600080fd5b610155610314565b6040518083151515158152602001806020018281038252838181518152602001915080516000925b818410156101a0578284906020019060200201518152602001926001019261017d565b92505050935050505060405180910390f35b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff168073ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff1614151561020e57600080fd5b60008060166101000a81548160ff02191690831515021790555050565b60018181548110151561023a57fe5b90600052602060002090600302016000915090508060000154908060010160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff16908060020154905083565b60008060169054906101000a900460ff16905090565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff168073ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415156102f657600080fd5b6001600060166101000a81548160ff02191690831515021790555050565b600061031e610401565b600060169054906101000a900460ff1691506001805480602002602001604051908101604052809291908181526020016000905b828210156103f75783829060005260206000209060030201606060405190810160405290816000820154600019166000191681526020016001820160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200160028201548152505081526020019060010190610352565b5050505090509091565b6020604051908101604052806000815250905600a165627a7a723058201fcb0eba7a85079fe7ab1240b436244e889eeef88da5ca720ceebf3499d553450029
------------------------
Tried prefixing with 0x in myetherwallet.

PLATFORM: win32
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by printlnBTC** [comment]
Note, there is a more detailed stack trace behind the crash window.  Where is that log file on Windows?

**Comment by benjamincburns** [comment]
@printlnBTC we've just released Ganache v1.0.2 which reports more detailed stack trace info in github reports.

**Comment by benjamincburns** [comment]
@printlnBTC can you please test this on v1.0.2 and repoen if this is still a problem? Also please be aware of trufflesuite/ganache-core#417 - my strong suspicion is that you're running afoul of this issue.
