### ISSUE TITLE
System Error when running Ganache 1.0.1 on win32

### ISSUE THREAD

**Issue by jbrady89** [trufflesuite/ganache#233]
Following this tutorial: https://medium.com/crypto-currently/build-your-first-smart-contract-fc36a8ff50ca

Error occurs when I tried to deploy contract using the local version of MEW.

PLATFORM: win32
GANACHE VERSION: 1.0.1

EXCEPTION:
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

**Comment by jbrady89** [comment]
Let it sit for a while and tried it again from local MEW. Worked that time and transaction is now reflected in Ganache.

**Comment by benjamincburns** [comment]
Thanks for reporting this. Chances are you're running into trufflesuite/ganache-core#417.

In the mean time the heartbeat issue should be fixed as of our latest release, v1.0.2, which is out just now!
