### ISSUE TITLE
The menu title ("menu") caused me some confusion

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/ganache#24]
On the left panel after starting Ganache, there are four items:

1. Menu
2. Dashboard
3. Block Explorer
4. Repl

The first, Menu, is actually a label, denoting that the next three items are part of the Menu panel. I was initially confused when I first used Ganache, thinking that "Menu" was a clickable item that would get me back to the initial screen before Ganache was started. 

Couple reactions:

- We do need _some_ way to get back to that initial screen, and stop Ganache. I'm not sure the best way to do that.
- If Menu is meant to be unclickable, I think we can likely remove it. The theme on the left panel is good enough to show the user that those are the available options, without needing a label.

**Comment by johnmcdowall** [comment]
Closing in favour of #32
