### ISSUE TITLE
Copy fields from transaction details

### ISSUE THREAD

**Issue by wbt** [trufflesuite/ganache#251]
On the Accounts view, there are public and (click to popup) private keys, and balances, as well as a mnemonic and HD path. When viewing a block there's a block hash and gas total. When viewing transaction details, there are fields like Transaction ID, Sender Address, To/Created Contract Address, Tx Data, Gas Used, etc.  

One can right-click on any of these, with or without first double-clicking to select the whole field, and see a single option: Inspect Element.  It would be helpful to have "Copy" as an option too.

This is similar to #66 but I think #66 is requesting a specific button shown in the interface which is just for that copy function; the present issue seeks to add Copy to the right-click menu that currently just has Inspect Element. 

Testing on Win10.

**Comment by cds-amal** [comment]
This module may offer a solution. https://github.com/sindresorhus/electron-context-menu
