### ISSUE TITLE
OpenZepplin-Solidity tests fail after the State Trie and VM refactor

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache#255]
Even with the fix in https://github.com/trufflesuite/ganache-core/commit/4a641cddde21779421a09407aa6b3f34f0dfbc97 openzeppelin-solidity tests as of commit https://github.com/OpenZeppelin/openzeppelin-solidity/tree/70e616db7c2bcce9d3a3fbbab83b7fe64a54fcd1 fail.

Original refactor commit: https://github.com/trufflesuite/ganache-core/commit/56153af1eefba36d1221e55cc060aba49728c2de

```
1891 passing (6m)
  1 pending
  2 failing

  1) Contract: balanceDifference
       returns balance increments:

      AssertionError: expected '422589324399999999999' to equal '1000000000000000000'
      + expected - actual

      -422589324399999999999
      +1000000000000000000
      
      at Context.<anonymous> (test/helpers/test/balanceDifference.test.js:14:27)                                                                                                                                    
      at process._tickCallback (internal/process/next_tick.js:68:7)                                                                                                                                                 
```

**Comment by nventuro** [comment]
Hey, @nventuro from OpenZeppelin here, trying to fix that very same test while migrating to truffle 5. Does this issue being open mean the error was not fixed in the 2.3.2 release? Thanks!

**Comment by nventuro** [comment]
I've updated [`openzeppelin-test-helpers`](https://github.com/OpenZeppelin/openzeppelin-test-helpers) (where this functionality has been extracted to) [to use `ganache-core` 2.3.3](https://github.com/OpenZeppelin/openzeppelin-test-helpers/blob/master/scripts/test.sh) (via `ganache-cli` 6.2.5), which made [that very same test pass](https://travis-ci.com/OpenZeppelin/openzeppelin-test-helpers/jobs/167868295), so I think this can be closed.

**Comment by davidmurdoch** [comment]
Thanks @nventuro for following up on this. I'm going to keep this open until we can open until we can look into https://github.com/trufflesuite/ganache-core/commit/56153af1eefba36d1221e55cc060aba49728c2de a bit further to see what originally went wrong in that commit and then file an appropriate issue for that when we do.

**Comment by davidmurdoch** [comment]
Closing this one for issue maintenance, as Ganache has been rewritten since this issue was first opened.
