### ISSUE TITLE
brew cask checksum error

### ISSUE THREAD

**Issue by jhoogeboom** [trufflesuite/ganache#260]
The checksum doesn't seem to match anymore, leading to errors when trying to install using brew cask.

```brew cask install ganache                                                 
==> Satisfying dependencies
==> Downloading https://github.com/trufflesuite/ganache/releases/download/v1.0.2/Ganache-1.0.2.dmg
Already downloaded: /Users/myuser/Library/Caches/Homebrew/Cask/ganache--1.0.2.dmg
==> Verifying checksum for Cask ganache
==> Note: running "brew update" may fix sha256 checksum errors
Error: Checksum for Cask 'ganache' does not match.

Expected: fd79850eb2a7a6b28022cdf31724873c225817fdb06d00315aab50719bd69394
Actual:   80ccdf1a7da83912c38af35bcdb325f971b56474afb6d1b9e5502831a0593026
File:     /Users/myuser/Library/Caches/Homebrew/Cask/ganache--1.0.2.dmg
```

**Comment by benjamincburns** [comment]
Doh! Thanks for reporting this, @jhoogeboom! It's a pet peeve of mine when package maintainers go and replace binaries but leave the same file number, and here I've gone and done exactly that!

I wasn't aware that there was a homebrew cask for Ganache. I'll submit a PR to them to correct the hash.

**Comment by benjamincburns** [comment]
Jeez, I wish it closed the issue when the PR was accepted, but whatevs, I'll take it on faith.  Thanks again for this, @jhoogeboom!

**Comment by jhoogeboom** [comment]
Thanks for the quick fix!
