### ISSUE TITLE
[enhanchment] On contract deploy transaction , allow empty "to" field

### ISSUE THREAD

**Issue by stormsson** [trufflesuite/ganache#264]
When deploying a contract using MEW  3.11.2.1 in local environment towards Ganache, the transaction is created including an empty "to" field:

`{"nonce":"0x00","gasPrice":"0x098bca5a00","gasLimit":"0x021506","to":"","value":"0x00","data":"[....bytecode here...]","chainId":1}`

In this circumstance, Ganache does not allow the contract to be deployed because there shouldn't be a "to" field.

As per indication in #257 comment by @benjamincburns , I log this issue to handle the contract deployment with the empty "to" field

## Expected Behavior
Ganache ignores the empty to field

## Current Behavior
Ganache ignores the transaction

## Context
Testing solidity contracts in local env

**Comment by benjamincburns** [comment]
I’ll probably do something to fix ganache to be more tolerant to this, but after sleeping on it I feel it’s an MEW bug to be setting the ‘to’ field to an empty string. It surprises me a little that this works on other clients.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stormsson** [comment]
@benjamincburns is there a reference somewhere that defines the fields that must be sent to deploy the contract? i could use that to open an issue to mew team

**Comment by stormsson** [comment]
after checking a bit, a user on stackoverflow stated that MEW shows the empty transaction in the left side , but in the encoded transaction it should be "0"

**Comment by cserb** [comment]
@stormsson are able to deploy a contract with the current MEW?

**Comment by stormsson** [comment]
@cserb just tested with MEW 3.11.2.4 , ganache 1.0.2.

no, i have not been able.
Ganache crashes when i try to sign the transaction, so the step before deploying the contract...

this is the new application log 


APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","network_id":5777,"port":7000,"total_accounts":10,"unlocked_accounts":[]}
T+242ms: Ganache started successfully!
T+242ms: Waiting for requests...
T+24075ms: eth_sendRawTransaction
T+39736ms: eth_blockNumber
T+51628ms: eth_estimateGas
T+65262ms: eth_estimateGas
T+71396ms: eth_getBalance
T+71396ms: eth_gasPrice
T+71396ms: eth_getTransactionCount
T+71440ms: eth_getBalance
T+71440ms: eth_gasPrice
T+71440ms: eth_getTransactionCount
T+71499ms: eth_estimateGas
T+71505ms: 
T+71505ms: /node_modules/ganache-cli/build/lib.node.js:63898
T+71505ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_W
T+71505ms: AssertionError: The field to must have byte length of 20
T+71505ms:     at FakeTransaction.setter [as to] (/node_modules/ganache-cli/build/lib.node.js:7366:9)
T+71505ms:     at /node_modules/ganache-cli/build/lib.node.js:7416:63
T+71505ms:     at Array.forEach (native)
T+71505ms:     at Object.exports.defineProperties (/node_modules/ganache-cli/build/lib.node.js:7415:14)
T+71505ms:     at FakeTransaction.Transaction (/node_modules/ganache-cli/build/lib.node.js:78121:13)
T+71505ms:     at FakeTransaction (/node_modules/ganache-cli/build/lib.node.js:20454:5)
T+71505ms:     at /node_modules/ganache-cli/build/lib.node.js:80343:14
T+71505ms:     at /node_modules/ganache-cli/build/lib.node.js:21924:5
T+71505ms:     at /node_modules/ganache-cli/build/lib.node.js:55954:5
T+71505ms:     at /node_modules/ganache-cli/build/lib.node.js:56320:14
```

**Comment by cserb** [comment]
@stormsson the crash has been fixed already. There is a new version (1.1.0) out.
Unfortunately it still doesn't work with MEW - most likely because of the same reason - but this time fails silently

**Comment by benjamincburns** [comment]
The fix for this bug wasn't included in `1.1.0-beta.0`, however it is in the current `develop` branch of `ganache-core`. Apologies, it's been reported numerous times so I forgot to come back to this specific issue to update it.

The simplest way to work around the problem in the mean time is to drop the empty `to` field from the request.

**Comment by benjamincburns** [comment]
I've also submitted a PR to MEW to address this: kvhnuke/etherwallet/pull/1550

**Comment by stormsson** [comment]
hello @benjamincburns  thank you for your support, may i ask why drop the "to" field? in eth yellow paper is not indicated as an optional field

**Comment by benjamincburns** [comment]
@stormsson happy to help!

From memory, I think the yellow paper is in conflict on this point. Further, I don't think it's meant to define the RPC protocol, just the consensus mechanism.

From first principles:

* The `to` field is meant to be a valid hex-encoded address.
* Transactions which create new contracts must have `data`, and must not specify a destination address.
* The null address `0x0000000000000000000000000000000000000000` is technically a valid destination address
* An empty string is not a valid hex-encoded address.
* Therefore, on contract deployment, the `to` field must not be specified.
