### ISSUE TITLE
Already have a metamask account cannot import with ganache seed, needs json or privkey

### ISSUE THREAD

**Issue by ilanoh** [trufflesuite/ganache#273]
So where can I find the privkey or json connected to the ganache test seed ?

Metamask won't let me import a wallet with the seed,

Thank you

**Comment by aleybovich** [comment]
Ganache GUI has a key icon next to every account - click on that key to reveal the account's private key. You can use that private key to import the account to Metamask (make sure metamask is pointing to your custom network)

**Comment by benjamincburns** [comment]
Closing this, as @aleybovich answered the question. @ilanoh you're best bet is to ask questions like these on [gitter](https://gitter.im/ConsenSys/truffle) first - you're likely to get a response there in 7 minutes instead of 7 days.
