### ISSUE TITLE
Remove default mnemonic

### ISSUE THREAD

**Issue by kapsteur** [trufflesuite/ganache#275]
Following this post on reddit : https://www.reddit.com/r/ethtrader/comments/7qily1/my_eth_disappeared_from_my_metamask_account/

I think we need to avoid to set a default mnemonic and always generate a random one.

**Comment by ChosunOne** [comment]
Either that or change it to "developers developers developers developers developers developers developers developers developers developers developers developers".  That is pretty obviously not randomly generated.

**Comment by ChosunOne** [comment]
Here is some evidence of people using the default mnemonic on the main net: 
https://www.reddit.com/r/ethereum/comments/7z4n6a/people_are_using_the_hardcoded_ganache_seedphrase/

**Comment by danfinlay** [comment]
This seems pretty awful to me. Such a small change to cause loss of funds and confusion. And for what? Some slightly more convenient tests? It’s not worth it. Add the seed to a test file later if it’s so important. User loss of funds should be a cardinal rule to avoid.

**Comment by benjamincburns** [comment]
@danfinlay,

Thanks for the reminder! We agree that it's terrible that people are losing their funds, and we're taking the following steps to remove ourselves from the equation:

 1. Before the end of the week we'll add a highly visible warning to the Ganache UI and `truffle develop` cautioning people against using dev/test accounts on mainnet. We've already placed a similar warning in our tutorials.
2. As part of the stable Ganache 1.1.0 release we'll make Ganache generate persistent random mnemonics for new users by default, keeping the visible warning and random mnemonic on start switch in place.

As for _why_ this is happening, my working assumption is that users configured MetaMask for dev/test, then either didn't realize the cryptographic significance of the mnemonic, or realized but forgot they'd reset MetaMask, and then one way or another caused funds to be sent to what they mistook to be their own private account. However, I realize that this assumption is just a made up story until we have some user experience to back it up, so I intend to get on a call or three with some users who've run folly of this problem to understand in detail how it keeps happening.

In the mean time, I strongly encourage the MetaMask team to look at metamask/metamask-extension#3131, as unless the above assumption entirely misses the mark, I think that change could go a long way toward preventing this problem from happening in the future.

**Comment by benjamincburns** [comment]
Don't know why I missed this one - it has been fixed and released as part of Ganache 1.1.0.

**Comment by kamescg** [comment]
I know this is a pretty old thread, but it would be great to BE ABLE to set a default mnemonic phrase every time a new environment is setup. It's laborious to have to switch out wallets each time the development environment is reset.

Especially since it's not possible to reset the state without actually creating a new mnemonic phrase as mentioned in https://github.com/trufflesuite/ganache/issues/1275
