### ISSUE TITLE
Need better UI/UX for users returning from standby 

### ISSUE THREAD

**Issue by wbt** [trufflesuite/ganache#282]
I use ganache on a development machine that I sometimes put into standby.  When I return from standby, I'm always presented with a grayed-out window and the following popover, "System Error when running Ganache 1.0.1 on win32:"

![ganache bug ui](https://user-images.githubusercontent.com/563406/34998962-6e3afe84-faae-11e7-819b-0c8896a29ce3.PNG)

The details are: 
```
Error: Lost heartbeat from server process!
    at Timeout.setInterval [as _onTimeout] (/src/Services/Chain.js:86:30)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

The core of the message is "lost heartbeat," probably measured by subtracting the timestamp of the last heartbeat received from the current timestamp and comparing that to some threshold.  Since the system was in standby, the last heartbeat sent (or received) was a while ago (where "a while" can be seconds).  

The user is instructed to file an issue here (here it is!) and/or relaunch.  

**Workaround 1:**
Never use standby while developing smart contracts and testing with Ganache.  This may be impractical for other reasons, such as not wanting to physically move a machine with a spinning hard disk. 

**Workaround 2:**
Ignore the popover's message about this being a bug, and hit Relaunch.  

Requiring either of these workarounds is poor UI/UX design.

**Quick improvement:**
Make a better UI for users who are coming back from standby.

**Better improvement:**
Detect standby periods.  The process listening for server heartbeats can periodically keep track of the last timestamp it was itself running, and when a gap in that larger than the typical period is detected, add that same amount of time to the threshold for heartbeat timeout.  Then the user might not have to relaunch and lose everything that was on the chain on every return from standby.  

**Even better improvement:**
Both of the above, the first one to help catch failures of the second.

**Comment by benjamincburns** [comment]
Hi @wbt - thanks for reporting this. Fortunately, this error is fixed in Ganache 1.0.2. Search issues for "heartbeat" and you'll see duplicitous other reports of this issue.

**Comment by wbt** [comment]
I did search, but forgot to remove the is:open which GitHub includes by default.  I'm glad to hear it's fixed for the next version!

**Comment by benjamincburns** [comment]
:laugh: No problem at all, and apologies - I didn't mean to chastise.
