### ISSUE TITLE
Bad line number reports on test failure

### ISSUE THREAD

**Issue by elenadimitrova** [trufflesuite/ganache#287]
Since upgrading `ganache-core` to version 2.3.2 back in [mid December](https://github.com/JoinColony/colonyNetwork/commit/23e89d310bcbdcdeeae86244711d52eec6c80153), we started experiencing incorrect reports by `truffle` test runs upon failures. 

## Expected Behavior
When a truffle test run fails, mocha reports the correct line number in test source where the failure occurred. Below are a set of sample failed builds quoting test line numbers that are **correct**:
https://circleci.com/gh/JoinColony/colonyNetwork/5051
https://circleci.com/gh/JoinColony/colonyNetwork/5287
https://circleci.com/gh/JoinColony/colonyNetwork/5493
https://circleci.com/gh/JoinColony/colonyNetwork/5505

## Current Behavior
Incorrect line number is reported when a test fails. 
Below are a set of sample failed builds quoting test line numbers that are **INcorrect**:
https://circleci.com/gh/JoinColony/colonyNetwork/5553
https://circleci.com/gh/JoinColony/colonyNetwork/5582
https://circleci.com/gh/JoinColony/colonyNetwork/5636
https://circleci.com/gh/JoinColony/colonyNetwork/5721

## Possible Solution
Although not a solution, @area suspects [this change](https://github.com/trufflesuite/ganache-core/commit/22e3af697dcd1ee68e7f671ad3bdc128b7c5f1bc#diff-168726dbe96b3ce427e7fedce31bb0bc) might be the cause of our woes.

We did test with `ganache-core` v2.2.1 where this issue isn't present.

## Context
Resolving any test failures has become rather laborious as you never know where in the test file the error comes from. This makes for some horrendous developer experience.

## Your Environment
* Version used: 2.3.2
* Operating System and version: MaxOS High Sierra
* Link to your project: https://github.com/JoinColony/colonyNetwork

**Comment by elenadimitrova** [comment]
I've just tested upgrading to 2.5.3 and I can no longer reproduce this issue so closing. Reviewing the release notes it doesn't seem like it was directly addressed 🤷‍♀️ .

**Comment by davidmurdoch** [comment]
@eggplantzzz thinks this may have been resolved on the Truffle side. We still need to investigate a bit more before closing.

**Comment by eggplantzzz** [comment]
Can anyone confirm that this is still or is no longer an issue?

**Comment by davidmurdoch** [comment]
Closing for issue maintenance.
