### ISSUE TITLE
System Error when running Ganache 1.6.11 on linux

### ISSUE THREAD

**Issue by leochan007** [trufflesuite/ganache#288]
PLATFORM: linux
GANACHE VERSION: 1.6.11

EXCEPTION:
```
Blockchain process exited prematurely with code '7', due to signal 'null'.
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"gasLimit":3000000000000000,"gasPrice":1,"hostname":"127.0.0.1","mnemonic":"coast laptop basket bring remember sorry else element inmate visual bring visit","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[]}
T+547ms: Ganache started successfully!
T+547ms: Waiting for requests...
T+25968ms: eth_estimateGas
T+27318ms: eth_getBalance
T+27318ms: eth_gasPrice
T+27318ms: eth_getTransactionCount
T+27341ms: eth_getBalance
T+27341ms: eth_gasPrice
T+27341ms: eth_getTransactionCount
T+27552ms: eth_estimateGas
T+27563ms: 
T+27563ms: /home/leo/Documents/src_codes/dapp/bcgrp/ganache/node_modules/ganache-cli/build/lib.node.js:63898
T+27563ms: var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Module["ENVIRONMENT"]){if(Module["ENVIRONMENT"]==="WEB"){ENVIRONMENT_IS_WEB=true}else if(Module["ENVIRONMENT"]==="WORKER"){ENVIRONMENT_IS_WORKER=true}else if(Module["ENVIRONMENT"]==="NODE"){ENVIRONMENT_IS_NODE=true}else if(Module["ENVIRONMENT"]==="SHELL"){ENVIRONMENT_IS_SHELL=true}else{throw new Error("The provided Module['ENVIRONMENT'] value is not valid. It must be one of: WEB|WORKER|NODE|SHELL.")}}else{ENVIRONMENT_IS_WEB=typeof window==="object";ENVIRONMENT_IS_WORKER=typeof importScripts==="function";ENVIRONMENT_IS_NODE=typeof process==="object"&&"function"==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMEN
T+27563ms: AssertionError: The field to must have byte length of 20
T+27563ms:     at FakeTransaction.setter [as to] (/home/leo/Documents/src_codes/dapp/bcgrp/ganache/node_modules/ganache-cli/build/lib.node.js:7366:9)
T+27563ms:     at /home/leo/Documents/src_codes/dapp/bcgrp/ganache/node_modules/ganache-cli/build/lib.node.js:7416:63
T+27563ms:     at Array.forEach (native)
T+27563ms:     at Object.exports.defineProperties (/home/leo/Documents/src_codes/dapp/bcgrp/ganache/node_modules/ganache-cli/build/lib.node.js:7415:14)
T+27563ms:     at FakeTransaction.Transaction (/home/leo/Documents/src_codes/dapp/bcgrp/ganache/node_modules/ganache-cli/build/lib.node.js:78121:13)
T+27563ms:     at FakeTransaction (/home/leo/Documents/src_codes/dapp/bcgrp/ganache/node_modules/ganache-cli/build/lib.node.js:20454:5)
T+27563ms:     at /home/leo/Documents/src_codes/dapp/bcgrp/ganache/node_modules/ganache-cli/build/lib.node.js:80343:14
T+27563ms:     at /home/leo/Documents/src_codes/dapp/bcgrp/ganache/node_modules/ganache-cli/build/lib.node.js:21924:5
T+27563ms:     at /home/leo/Documents/src_codes/dapp/bcgrp/ganache/node_modules/ganache-cli/build/lib.node.js:55954:5
T+27563ms:     at /home/leo/Documents/src_codes/dapp/bcgrp/ganache/node_modules/ganache-cli/build/lib.node.js:56320:14
```

**Comment by leochan007** [comment]
using myetherwallet connect to local rpc served by ganache.
deploy the bytecode which is generated by "truffle compile". then local ganache crash.

**Comment by benjamincburns** [comment]
Sorry, but we haven’t released a 1.6.11 yet.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by benjamincburns** [comment]
Also thanks for reporting, but this bug is fixed in develop. I can’t remember if the fix made it into the last beta or not, but it will definitely be in the next one.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leochan007** [comment]
@benjamincburns 1.6.11 is auto generated from bug report function of ganache.

**Comment by benjamincburns** [comment]
@leochan007 where did you download `ganache` from? Which version were you expecting to get? I promise that we haven't released `v1.6.11` yet. Our lates beta is only `v1.1.0-beta.0`.

**Comment by leochan007** [comment]
@benjamincburns git clone -> npm i -> npm start.

**Comment by benjamincburns** [comment]
@leochan007 Thanks for responding! What version is displayed on startup? Also which OS do you use? I'll check the releases to make sure we aren't publishing bad version numbers.

Otherwise someone may have added some cheeky logic somewhere to report a "magic" version when people are running debug builds locally. I'll look for that, too.

Speaking of which, unless you're making modifications, you're best off using the prebuilt binaries from https://github.com/trufflesuite/ganache/releases rather than cloning & building your own. Saves a bunch of time.

**Comment by leochan007** [comment]
@benjamincburns either master(1.0.2) or develop(1.1.0-beta.0) shows correct version but it change to 1.6.11 when bug reporting.  "PLATFORM: linux
GANACHE VERSION: 1.6.11...." these info r auto generated. i didn't change anything. 

my OS: ubuntu gnome 16.04.  x64

**Comment by benjamincburns** [comment]
@leochan007 thanks! Unfortunately version numbers don't really mean much for us when you're running code you've built yourself, so I think this might be a magic number to indicate that fact. I'll look into it.
