### ISSUE TITLE
Problems when configuring Ganache to listen on invalid interface, or interface upon which it doesn't have permissions to listen

### ISSUE THREAD

**Issue by NextZeus** [trufflesuite/ganache#289]
When I set up an error of the host, after restart the ganache, client will never see any interface.

**Comment by benjamincburns** [comment]
Thanks for reporting this! Just to be sure I understand, you are saying that if the host name you set is not valid for your machine (example: IP address that doesn’t exist), Ganache fails to load after restart?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NextZeus** [comment]
The IP address is exists, but unaccessible. @benjamincburns

**Comment by FollowJack** [comment]
Same problem here :( 
IP Address is inaccessible. 
Looked into the inspector.
Ganache is not responding. No errors thrown. Not responding with opening a view. @benjamincburns

**Comment by benjamincburns** [comment]
Thanks, @NextZeus - I'll be tackling this issue and the "hanging on used port" issue very soon - hopefully in advance of the stable 1.1.0 release (early beta out now, but won't have these fixes yet).

**Comment by seesemichaelj** [comment]
This is a duplicate of #666 and will be in the next release (hopefully next week). The solution will at a minimum gracefully handle the error and allow you to fix it.

**Comment by rescobarm** [comment]
in my case, same problem was because my ip local address was automatically changed. So, I'm turn back old configuration, and turn off automatic dhcp.
