### ISSUE TITLE
Request: please provide v, r, s parameters in transaction

### ISSUE THREAD

**Issue by alex-miller-0** [trufflesuite/ganache#294]
## Expected Behavior

Both Parity and Geth provide `v, r, s` signature parameters in the return data of `eth.getTransaction()`. This allows the user to verify transactions and blocks. 

## Current Behavior
TestRPC does not provide this data. This is because it is not in the official web3 [function API](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransaction).

## Context
I am building a Solidity library to verify a transaction was in a tx root via a Merkle proof. In production, each node (in the tree) will be hashed with the signature parameters. This means forming the proof is different in production vs testing, which is bad.

**Comment by benjamincburns** [comment]
Hi @alex-miller-0 - this will need to be implemented in `ganache-core` and I'm afraid I just cut the a new beta on that one. I'll do my best to get it done in time for the next drop, however.

**Comment by alex-miller-0** [comment]
No worries.

For anyone who may stumble onto this, I have a work around CLI [script](https://github.com/GridPlus/trustless-relay/blob/master/parity/boot.js) that auto-generates any number of separate parity instances with instant-seal. It takes about 1s per blockchain-write, so as long as your test files are fairly short it shouldn't be a big deal.

**Comment by lazaridiscom** [comment]
Is this v-r-s compliancy a **must** requirement to to Ethereum tools (like Ganache and web3) ?

Or asked differently: what does the relevant standard say about v-r-s ?

**Comment by seesemichaelj** [comment]
@balexander4 validated that this is still an issue

**Comment by lazaridiscom** [comment]
@nicholasjpaterno , was this solved?

**Comment by nicholasjpaterno** [comment]
Hello @lazaridiscom, this should be all set!  However, I do not believe it has made its way into a release just yet.  If you'd like to test this now, checkout the [develop](https://github.com/trufflesuite/ganache-core/tree/develop) branch!

**Comment by lazaridiscom** [comment]
very nice - (https://github.com/trufflesuite/ganache-core/commit/36870a19d5980cd42f8b6eb96ebe03dce42943b9)
