### ISSUE TITLE
Searching for an existing transaction while viewing another transaction does not update the current page

### ISSUE THREAD

**Issue by benjamincburns** [trufflesuite/ganache#298]
## Expected Behavior
While viewing one transaction, if I search for another, existing, transaction - I expect that the current view will update to show me the transaction I've just searched for.

## Current Behavior
While viewing one transaction, if I search for another, existing, transaction - the current view **does not** update to show me the transaction I've just searched for.

## Possible Solution
Uncertain, need to diagnose further.

## Steps to Reproduce (for bugs)
1. Run two transactions, call them A and B. Write down their hashes.
2. From the accounts page, search for transaction A by its hash, verify that you see the correct transaction data
3. From the accounts page, search for transaction B by its hash, verify that you see the correct transaction data
4. From the accounts page, search for transaction A by its hash, then without going back to the accounts page search for transaction B by its hash. Observe that you still see information for transaction A.

## Context
Discovered while testing web3 1.0 updates.

## Your Environment
It's possible that this was introduced by the web3 1.0 updates, however I believe this is not the case and that this affects all versions released to date, up to and including 1.1.0-beta.0.

**Comment by DiscRiskandBisque** [comment]
On reproduction, the console displays an error referencing block searching: `Block search error:  Error: Returned error: Key not found in database`. On the tx pages the search box seems to default to only finding block hashes.

**Comment by honestbonsai** [comment]
Odd you get `Block search error: Error: Returned error: Key not found in database`, even when it does display a tx properly.

1. Start on Transactions (note: plural) page
1. Search for a tx
1. Will show Transaction (singular) page fine
1. Check console for error

**Comment by honestbonsai** [comment]
Issue is in `TxCard`, specifically https://github.com/trufflesuite/ganache/blob/develop/src/renderer/screens/transactions/TxCard.js#L24

So searching for `txHash` works from any other screen except `TxCard` since it will always mount the `TxCard` screen, but if you search from `TxCard`, it's already mounted, so this code never fires. I'm guessing if we add a `componentDidUpdate` handler for this it should work.

Will test it out.
