### ISSUE TITLE
Acquire publishing certificates for the App

### ISSUE THREAD

**Issue by johnmcdowall** [trufflesuite/ganache#30]
In order to not have security alerts when trying to run the app, we'll need to acquire developer signing ceritificates for Windows and macOS. 

For Windows: https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/get-a-code-signing-certificate

For Apple: https://developer.apple.com/programs/enroll/

**Comment by tcoulter** [comment]
Both of these are in process. 

- Apple needs my driver's license, and needs to go through the approvals process.
- Digicert (Windows) needs an actual company on file with some state (any state) so I have to go through Consensys's legal team for that.
