### ISSUE TITLE
Ganache won't launch after changing to network it can't connect to

### ISSUE THREAD

**Issue by peterhn** [trufflesuite/ganache#306]
I was able to set a RPC server in ganache to a TestRPC which worked initially, but after setting the RPC server to a private network that I had setup, ganache no longer launches, it is stuck on the launch splash (even after removing the package and installing again). 

## Expected Behavior
Popup error indicating that it cannot connect to such network and ask to change the network

## Current Behavior
Stuck on splash screen after not able to connect to a private network

## Possible Solution
I am assuming that there is another setting file that I can remove / update? I just can't find it.

## Steps to Reproduce (for bugs)
1. Enter settings
2. Enter IP address without RPC Server
3. Connect
4. Restart app

## Your Environment

* Version used: 1.1.0 beta.0
* Operating System and version: Mac OSX 10.13.1

**Comment by peterhn** [comment]
I tried running in dev and I get this error in the console:
`Blockchain process exited prematurely with code '7', due to signal 'null'.`

**Comment by benjamincburns** [comment]
> but after setting the RPC server to a private network that I had setup

Hi @peterhn - can you please clarify the above for me? Are you saying that you're configuring Ganache to point listen on a different network interface, and it's then hanging on start? If so, I think this case duplicates #289. Would you agree?

**Comment by peterhn** [comment]
@benjamincburns Not quite the same. Actually this is probably a better question: Can you connect to non localhost networks using ganache? Or does ganache only create an localhost RPC server?

**Comment by peterhn** [comment]
@benjamincburns I set `Hostname` in settings to non localhost address (ex. 192.168.1.3). Ganache restarts and then it's stuck on splash, even when I restart, or reinstall.

**Comment by benjamincburns** [comment]
> Can you connect to a different networks using ganache? Or does ganache only create an localhost RPC server?

Ganache simulates an Ethereum client like geth or Parity. As a result, it exposes a JSONRPC interface on the host/port specified in settings. Ganache doesn't connect out to any other servers.

**Comment by benjamincburns** [comment]
I think you're likely running into #289. or #85. Either way, the fix necessary for one should also take care of the other, and will likely take care of this problem as well.

The workaround for now is to `rm ~/Library/Application Support/Ganache/Settings`

Going to close this, but please reopen if you feel I've got it wrong.

**Comment by benjamincburns** [comment]
Ah, I also should've pointed out that you can hand edit `~/Library/Application Support/Ganache/Settings` if you don't want to lose your other non-default config. Sorry if I was too late to say that!

**Comment by peterhn** [comment]
@benjamincburns are there plans to allow Ganache to connect other servers?

**Comment by hoanganh25991** [comment]
I guess **persistent config** Ganache reads on each time it launches causing the problem.
On windows, i remove persistent config at `%APPDATA%/Electron`, then Ganache relaunches normally as first time.
(You should rename `Electron` folder instead of deleting it. Ganache will auto generate a new one)
![image](https://user-images.githubusercontent.com/8801188/35484922-2d8e126e-048a-11e8-922f-6b2da99c35c4.png)

**Comment by Keith-CY** [comment]
`rm ~/Library/Application Support/Ganache/Settings` works on macOS High Sierra 10.13.3

**Comment by stoll** [comment]
I simply removed `rm ~/Library/Application Support/Ganache/`, and it solved my problem!
