### ISSUE TITLE
Readme has missing dependencies 

### ISSUE THREAD

**Issue by vaibhavchellani** [trufflesuite/ganache#310]
the readme says to build we need to do 
- npm install
- npm run start
 whereas users who dont have electron-forge installed have to install first , so the instructions can be 
- npm install
- npm install --save electron-forge
- npm run start

**Comment by benjamincburns** [comment]
Hi @vaibhavchellani can you please have a look at our `package.json` once again? You'll see that `electron-forge: ^4.1.2` is listed under `devDependencies`.
