### ISSUE TITLE
Gas Price on interface is not actually used

### ISSUE THREAD

**Issue by nickjm** [trufflesuite/ganache#314]
In the ganache interface there is a "Gas Price" field set by default to 20000000000. I expected this to be the default gas price for all transactions. The actual gas price is 100000000000, which I assume is the default set by the EVM. I'm not sure if this is a UX problem or a software bug, so I apologize if this is the wrong place for posting.

 

## Expected Behavior

Gas price should be the same value that is show in the UI.

## Current Behavior

Gas price is set by default to 10^11 Wei, presumably by the EVM

## Possible Solution

Either change the UI to show the EVM default, or change the software to implement a global default.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Ganache 1.0.1 (I tried latest version but had other problems with it, so apologies for slightly outdated version)
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: MacOS 10.13.3 High Sierra
* Link to your project:

**Comment by benjamincburns** [comment]
Hmm, I’ll have a look. It’s possible/probable that the field which the UI sets doesn’t align with the `options` object expected by ganache-core in `chain.js`

**Comment by nickjm** [comment]
Update: it looks like `web3.eth.getGasPrice(callback)` returns the same price as the ganache UI, but that price is still incorrect, i.e. when I check the account balances a different price is being used

**Comment by nickjm** [comment]
"20000000000" <-- Ganache
"20000000000" <-- Web3
"100000000000" <-- actual
according to the following check:
```
Number(currentBalance) == Number(previousBalance) + amount - (gasUsed * actual)
```

**Comment by benjamincburns** [comment]
Thanks for this, @nickjm!

That's a fairly significant deviation. I'd guess that we're not setting the gasPrice correctly in ganache-core, if that's the case.

**Comment by benjamincburns** [comment]
@nickjm if you get a sec, can you please have a look at the test I added in 0ed962f? It passes for me without changes against ganache-core, which is what powers both ganache-cli and the ganache UI.

If you agree that the test is correct, then it's likely a problem somewhere with how ganache configures its own instance of ganache-core. Can you do me a favour and check your settings file (`~/Library/Application\ Support/Ganache/Settings` on mac) and verify whether `server.gasPrice` is defined?

**Comment by leewi9** [comment]
just report that this problem still exists in the latest version, commander.
```
"ganache-cli": "^6.0.3",
"truffle": "^4.0.6"
```

**Comment by giaset** [comment]
Still an issue for me as well in Ganache 1.0.2.

@benjamincburns I went and looked at `~/Library/Application\ Support/Ganache/Settings` and my `server.gasPrice` there was set to the proper value (4 Gwei, which shows up fine in the UI), but every transaction I make still uses 100 Gwei as the gas price...

**Comment by infinityCounter** [comment]
I'm also having this issue with the Gas Price being set to 100 Gwei despite me setting it to 20 Gwei.

**Comment by michaeljohnbennett** [comment]
whats the best way to set this on a transaction to transaction basis, say if I had a gas limit set on a method and wanted to up or down the gasPrice to simulate this behaviour in a test?

```
contract.send(ethAmount, {gasPrice: ???, from: addr});
```

I've tried this and it doesn't respect any kind of value in here. It will set the gasPrice from the config only in truffle.js.

```
development: {
            // GANACHE settings
            host: "localhost",
            port: 7545,
            network_id: "*", // Match any network id
            gas: 4000000,
            gasPrice: 80000000000 // 80 Gwei
        },
```

and I have a test contract that has a payable method and just emits an Event with the values.

```
    // 500,000 max gas
    uint256 constant public gasLimit = 50000000000;
    event DepositReceived(address indexed beneficiary, uint256 amount, uint256 gas, uint256 gasprice, uint256 gasLimit);

    function () payable public {
        if (contractStage == CONTRACT_OPEN) {
            emit DepositReceived(msg.sender, msg.value, msg.gas, tx.gasprice, gasLimit);
            // other code omitted
        }
    }
```


When I run this test which has a bunch of variants of gasPrice:
```
let value = ether(10);
        // when I add money to the pool I should do that ok
        let result = await poolContract.send(value, {from: anyone, gasPrice: "49000000000", gasprice: "123456", gas: "654321"})
            .should.be.fulfilled;
        console.log(result);
        console.log(result.logs[0].args);
```

I get : 

```
{ tx: '0x3fd733ffa45be404e25094f4f0d2a2809ea49248225fbe4dd5608f69f1d815d4',
  receipt:
   { transactionHash: '0x3fd733ffa45be404e25094f4f0d2a2809ea49248225fbe4dd5608f69f1d815d4',
     transactionIndex: 0,
     blockHash: '0xd5619d17a0fc7d43da10dd1a089379096996bdb65ac2d6a37204ac0bc0cb159e',
     blockNumber: 24,
     gasUsed: 23899,
     cumulativeGasUsed: 23899,
     contractAddress: null,
     logs: [ [Object] ],
     status: 1 },
  logs:
   [ { logIndex: 0,
       transactionIndex: 0,
       transactionHash: '0x3fd733ffa45be404e25094f4f0d2a2809ea49248225fbe4dd5608f69f1d815d4',
       blockHash: '0xd5619d17a0fc7d43da10dd1a089379096996bdb65ac2d6a37204ac0bc0cb159e',
       blockNumber: 24,
       address: '0xbaaa2a3237035a2c7fa2a33c76b44a8c6fe18e87',
       type: 'mined',
       event: 'DepositReceived',
       args: [Object] } ] }
{ beneficiary: '0x627306090abab3a6e1400e9345bc60c78a8bef57',
  amount: BigNumber { s: 1, e: 19, c: [ 100000 ] },
  gas: BigNumber { s: 1, e: 6, c: [ 3978672 ] },
  gasprice: BigNumber { s: 1, e: 10, c: [ 80000000000 ] },
  gasLimit: BigNumber { s: 1, e: 10, c: [ 50000000000 ] } }
```

As you can see gasprice (tx.gasprice) is being set to the 80... number from config and not being passed in via the method call to `send(...)`. 

I'm sorry If I'm doing something incredibly dumb here but I'm trying to emulate a test where I can see how much people are paying to mine their transactions to limit a gas war and give everyone a fair field.

I can't see how I can test this in truffle at all and if I add this requirement into my code I would need to be able to test it.

Any help would be greatly appreciated.

**Comment by michaeljohnbennett** [comment]
@benjamincburns or @nickjm would you be able to help me answer this issue?

**Comment by michaeljohnbennett** [comment]
ok I think I solved it for myself and hopefully others may find this useful until its fixed in Truffle.

```
let result = await poolContract.sendTransaction({
            from: anyone,
            to: poolContract.address,
            value: value,
            gasPrice: web3.toWei("49", "gwei")
        })
            .should.be.fulfilled;
        console.log(result);
        console.log(result.logs[0].args);

```

Will work and will set correct gasPrice. `send(...)` does not use gasPrice set in params.

Logs:
```
{ tx: '0xd6abccc490263bdb6a987101f3e110a646c7ff4371de27b97f9d70e1357cf36f',
  receipt:
   { transactionHash: '0xd6abccc490263bdb6a987101f3e110a646c7ff4371de27b97f9d70e1357cf36f',
     transactionIndex: 0,
     blockHash: '0x9f104529144c8edf9690e29ec8d9c4219139f226f1f31b6e22ba4206dc239786',
     blockNumber: 12,
     gasUsed: 23899,
     cumulativeGasUsed: 23899,
     contractAddress: null,
     logs: [ [Object] ],
     status: 1 },
  logs:
   [ { logIndex: 0,
       transactionIndex: 0,
       transactionHash: '0xd6abccc490263bdb6a987101f3e110a646c7ff4371de27b97f9d70e1357cf36f',
       blockHash: '0x9f104529144c8edf9690e29ec8d9c4219139f226f1f31b6e22ba4206dc239786',
       blockNumber: 12,
       address: '0x30753e4a8aad7f8597332e813735def5dd395028',
       type: 'mined',
       event: 'DepositReceived',
       args: [Object] } ] }
{ beneficiary: '0xf17f52151ebef6c7334fad080c5704d77216b732',
  amount: BigNumber { s: 1, e: 19, c: [ 100000 ] },
  gas: BigNumber { s: 1, e: 6, c: [ 3978672 ] },
  gasprice: BigNumber { s: 1, e: 10, c: [ 49000000000 ] },
  gasLimit: BigNumber { s: 1, e: 10, c: [ 50000000000 ] } }
```

**Comment by benjamincburns** [comment]
@michaeljohnbennett if the issue you're describing is real, it's a problem with web3.js. Please report it there, as that's fundamentally different to the problem which @nickjm reported.

Otherwise I've corrected a problem in ganache-core wherein the `gasPrice` specified in the `options` object is not respected when no other `gasPrice` is specified by the transaction itself. This should go out with the next release of the suite.
