### ISSUE TITLE
Corrupt .dmg for Mac

### ISSUE THREAD

**Issue by RussW** [trufflesuite/ganache#318]
the download Disk Image for Mac appears to be corrupt, have tried downloading throughChrome and Safari and both observe popup messages stating they are corrupt

**Comment by benjamincburns** [comment]
@RussW what version? Can you please check the md5sum for me? You can also check signature validity with `signtool -vd Ganache-$VERSION.dmg`

**Comment by benjamincburns** [comment]
Also what version of OS X?

**Comment by RussW** [comment]
The Image download was from through the website and tried again through the releases tab
v1.2.0-beta.0 - Candy Apple  :  Ganache-1.1.0-beta.0.dmg

OSX Yosemite : 10.10.5

This is the first tool/utility I have downloaded, so have no other utilities to provide any other information I'm afraid.  Clicking on the .dmg file produces a small window stating the image is corrupt with no other information

![screen shot 2018-01-31 at 8 19 36 am](https://user-images.githubusercontent.com/871931/35594631-9745259a-065f-11e8-9b86-97ca28b5e99a.jpg)

**Comment by benjamincburns** [comment]
Of course it'd be Yosemite :laughing: -- during release I tested on El Capitan, Sierra, and High Sierra.

Other users have reported that images signed on later OS X versions are treated as corrupt by earlier versions, but I really have no idea why this happens. All I can really do is suggest updating your version of OS X.

**Comment by RussW** [comment]
Thank you for looking it to this and spending the time on it...
HaHaaa, yes, that would be just about typical, not a problem, I cant update this machine at the moment until another library I use is updated, so I will just have to look for an alternative until that time.  Thanks again for your efforts and assistance, much appreciated.

**Comment by RussW** [comment]
As a work-around;
I can confirm that if Ganache installed on a high-sierra machine, then the application copied from the applications folder to the Yosemite machines application folder, it appears to run quite happily with out any errors or issues so far.

**Comment by benjamincburns** [comment]
If I can get my hands on a Yosemite installer I can set up a vm easily enough to build and sign ganache, but it's just One More Thing to add to our build process. Next time I do a build for release I'll look into this.

**Comment by zersoon** [comment]
The Image download was from through the website and tried again through the releases tab
v1.2.0-beta.0 - Candy Apple : Ganache-1.0.0-rc.1.dmg is corropt when I install... please solve this problem as soon as possible. My MacOS is Yosemite 10.10.5

**Comment by benjamincburns** [comment]
@zersoon for the time being, signed installs are not supported on Yosemite. To work around this disable the signing checks or update to a later version of OS X.

**Comment by seesemichaelj** [comment]
Ah. I'm sorry for reopening this (and then closing). I'm going to create a new issue to track the lack of support on OSX versions < 10.11
