### ISSUE TITLE
RPC error when submitting transactions

### ISSUE THREAD

**Issue by vmandal** [trufflesuite/ganache#333]
## Current Behavior
The following error occurs when you pay via MetaMask for Ganache local (127.0.0.1:7545)

Error: Error: [ethjs-query] while formatting outputs from RPC 'undefined' for method 'sendRawTransaction' Error: [ethjs-format] hex string 'undefined' must be an alphanumeric 66 utf8 byte hex (chars: a-fA-F) string, is 0 bytes

This same error has been reported for Ganache app on Mac, Windows, Linux. See https://github.com/MetaMask/metamask-extension/issues/3125

## Steps to Reproduce (for bugs)
Executing truffle pet-shop dapp http://truffleframework.com/tutorials/pet-shop

## Context
Performing a transaction via MetaMask for smart contract created in solidity using truffle 

## Your Environment
* Ganache ganache-1.1.0-beta.0-x86_64.AppImage
* Truffle v4.0.6
* Gogle Chrome Version 64.0.3282.140
* Gogle Chrome MetaMask extension  ver 3.14.1
* CentOS 7.x
* npm 3.10.10
* node v6.12.3

**Comment by vmandal** [comment]
FYI, Resetting account at 127.0.0.1:7545 fixes the issue

**Comment by MacgyverMartins** [comment]
@vmandal how to reset account ?

**Comment by vmandal** [comment]
MetaMask > Settings > Reset Account
