### ISSUE TITLE
Ganache Installer appears to do nothing on Mac

### ISSUE THREAD

**Issue by mcqj** [trufflesuite/ganache#336]
Trying to open Ganache-1.1.0-beta.0.dmg on MacOS does nothing. The installer does not even open a window. It does not create an installer log entry.

## Expected Behavior
Ganache should be installed

## Current Behavior
Ganache does not install and fails silently.

## Steps to Reproduce (for bugs)
Download Ganache-1.1.0-beta.0.dmg and run.

## Your Environment

* Version used: Ganache-1.1.0-beta.0.dmg
* Operating System and version: MacOS High Sierra Version 10.13.3

**Comment by benjamincburns** [comment]
Hi @mcqj,

Normally when you double click the dmg file, after OS X verifies it you'll see a window like the following:

![image](https://user-images.githubusercontent.com/803016/36186633-2d0b3862-11a5-11e8-9700-2cb7b441be67.png)

In this case you can just drag the `Ganache` application file into your `Applications` directory and you're off.

If that window doesn't pop up for some reason you should still see the disk image mounted in your Finder, like in the bottom of the screenshot below. If you click there to open this drive you'll find the `Ganache` application in there, and you can drag that into your `Applications` directory to run it.

![image](https://user-images.githubusercontent.com/803016/36186591-ceea4e80-11a4-11e8-83a9-c236b93d0213.png)

Alternatively, there's a homebrew cask for ganache. We don't officially support it, but assuming you have homebrew installed, I think `brew cask install ganache` generally works nicely.

**Comment by benjamincburns** [comment]
Also in the future you'll likely get answers more quickly if you ask questions like this in the [Truffle Gitter](https://gitter.im/ConsenSys/truffle).

**Comment by mcqj** [comment]
Thanks for the feedback, Benjamin.

Perhaps my report wasn't as clear as it should have been. I do not have a general installation question. Previous versions of ganache do install correctly on MacOS. It is specifically this version (Ganache-1.1.0-beta.0.dmg) that fails to install and just looks like a bug to me.
