### ISSUE TITLE
ganache on Windows 8.1

### ISSUE THREAD

**Issue by eloudsa** [trufflesuite/ganache#337]
Hi

I have some students using Windows 8.1. They have issues to install ganache on Windows 8.1.
What are the minimal requirements on Windows?

Thanks,

Said

**Comment by benjamincburns** [comment]
Hi @eloudsa.

I'm afraid at the moment Ganache is only supported on windows 10. When I do the next release I'll take a crack at building an MSI, but I really can't make any promises. Also if I do this it will still likely be "at your own risk" on older Windows versions, as we already have a very wide testing footprint for Ganache, and I'm not overly eager to expand upon it.

For bookkeeping purposes, relevant comments are on #295, #221.

**Comment by benjamincburns** [comment]
@elodusa, sorry - I forgot to mention that you should still be able to clone and build locally...

If you want a one-liner for that, `git clone git@github.com:/trufflesuite/ganache; cd ganache; npm install -g windows-build-tools; npm install; npm start` ought to do it.

**Comment by MKEkalavya** [comment]
You can download ganache from the following link : 

https://github.com/trufflesuite/ganache/releases

Go to asset section and download the windows version.
I downloaded "Ganache-2.1.1-win-setup.exe" and it worked.

After download, install and launch it.
