### ISSUE TITLE
Not working properly with metamask.

### ISSUE THREAD

**Issue by nihalmpatel** [trufflesuite/ganache#340]
![image](https://user-images.githubusercontent.com/25846004/36096369-1c42950a-101c-11e8-98ed-6cff7f017d1c.png)

Imported MNEMONIC of ganache GUI in MetaMask and then imported another account using private key. Transferred ethers from account 1 to account 2 and I got this error.

**Comment by seesemichaelj** [comment]
I'm closing this as it works now, and I'm guessing this got fixed somewhere in the last few versions. Please open a new issue if you still have problems with `v1.2.1+`

Thanks!
