### ISSUE TITLE
Restructure Accounts card to highlight most important information

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/ganache#38]
Of the information on the accounts card, it seems less important information is highlighted over the more important items. 

<img width="775" alt="screen shot 2017-07-26 at 9 17 27 am" src="https://user-images.githubusercontent.com/92629/28631791-4e5a564a-71e3-11e7-80b0-963d45641db9.png">

I've listed the items from most important to least important:

1. Address
1. Balance 
1. Nonce (should be displayed as "transaction count")
1. Private Key
1. Index > 

Account and Balance are by far more important to a developers day to day; the last three are rarely used. Private key doesn't need to be front an center as it's definitely an advanced option. We could hide it behind a gear box, for instance, for advanced users only.

**Comment by johnmcdowall** [comment]
Closing this now as addressed in latest design changes
