### ISSUE TITLE
Implement `eth_getProof` RPC message

### ISSUE THREAD

**Issue by facuspagnuolo** [trufflesuite/ganache#382]
Would be really amazing to provide support for the [`eth_getProof`](https://github.com/ethereum/EIPs/issues/1186) RPC message. I actually needed to migrate bunch of tests to geth to make them work :)

Please let me know if I can help with it.

**Comment by davidmurdoch** [comment]
Thanks for the feature request, @facuspagnuolo! I'd like to start implementing more of the DRAFT status EIPs into ganache-core sooner than we have been. So if you'd like to put in the effort to make this happen I'd happily review and merge (likely behind a new option/flag we've been wanting to implement: `enable-eips: Array<string>` (we're still working on the name).

The bulk of the code will need to go in https://github.com/trufflesuite/ganache-core/blob/develop/lib/blockchain_double.js

Let me know if you need any help with the code base!

**Comment by simon-jentzsch** [comment]
This would be great, even though I don't have much time right now, I would love to help ( I did the implementation for geth and parity ). So if I can help, just ask!

**Comment by saurik** [comment]
Related: https://github.com/trufflesuite/ganache-cli/issues/725
