### ISSUE TITLE
Ganache immediately crashes when (re)launching after previous crash

### ISSUE THREAD

**Issue by mananz** [trufflesuite/ganache#385]
Ganache crashed while testing a contract on my local machine (unfortunately I didn't save the initial error report). After pressing the relaunch button, Ganache immediately crashes again. Manually terminating and starting Ganache again results in the same behaviour.

PLATFORM: darwin
GANACHE VERSION: 1.1.0-beta.1

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:7545
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"127.0.0.1","mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by sklingler93** [comment]
I was able to fix this by logging out of metamask and restarting ganache

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #665. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
