### ISSUE TITLE
System Error when running Ganache 1.1.0-beta.1 on darwin

### ISSUE THREAD

**Issue by xuleileo** [trufflesuite/ganache#398]
PLATFORM: darwin
GANACHE VERSION: 1.1.0-beta.1

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 192.168.1.193:7545
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"192.168.1.193","network_id":5777,"port":7545,"total_accounts":10,"unlocked_accounts":[],"mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","vmErrorsOnRPCResponse":true}
```

**Comment by hacktar** [comment]
Seems you put a custom IP in settings.
If you changed IP in Settings and now it doesn't start anymore, you could change it to 127.0.0.1 manually editing the Settings file in ~/Library/Application\ Support/Ganache/

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #666. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
