### ISSUE TITLE
Can I know how Ganache was implemented

### ISSUE THREAD

**Issue by galladivya** [trufflesuite/ganache#402]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by benjamincburns** [comment]
Yes, It's open source.

**Comment by galladivya** [comment]
Not the code,How it works
