### ISSUE TITLE
ganache-1.1.0-beta.1 consistently shows "corrupt image"

### ISSUE THREAD

**Issue by jamboj** [trufflesuite/ganache#407]
When downloading https://github.com/trufflesuite/ganache/releases/download/v1.1.0-beta.1/Ganache-1.1.0-beta.1.dmg and trying to open, shows "Corrupt image". This bug exists in previous ganache versions as well. It is not a corrupt download. Mac OS X 10.9.5

![image](https://user-images.githubusercontent.com/36251521/37262083-4f8d872e-2577-11e8-837a-ba3958066768.png)

**Comment by jamboj** [comment]
latest release affected too
![image](https://user-images.githubusercontent.com/36251521/37262299-b1e5f8ec-2578-11e8-907e-209d8b1610ff.png)

**Comment by benefitwith** [comment]
Same here

**Comment by seesemichaelj** [comment]
Thanks for reporting this! Our DMG releases currently only support El Capitan or newer. We'll be tracking this issue in #714
