### ISSUE TITLE
need support personal_signTransaction

### ISSUE THREAD

**Issue by ysqi** [trufflesuite/ganache#407]
need connect mist to ganache by rpc and send tx.

## Expected Behavior
success send.

## Current Behavior
get error: Method personal_signTransaction not supported
 
## Your Environment 
* Version used: Ganache CLI v6.3.0 (ganache-core: 2.4.0)  
* Mist: 0.11.1

**Comment by udartsev** [comment]
[ERROR] ipcProviderBackend - Send request failed { message: 'Method personal_signTransaction not supported.',
  code: -32000,
  data: 
   { stack: 'Error: Method personal_signTransaction not supported.\n    at u.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:515802)\n    at t (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:379433)\n    at a.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:514789)\n    at t (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:379433)\n    at s.f.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:507919)\n    at s.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:505745)\n    at t (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:379433)\n    at c.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:513803)\n    at t (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:379433)\n    at a.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:513250)\n    at t (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:379433)\n    at d._handleAsync (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:379469)\n    at Timeout._onTimeout (/usr/local/lib/node_modules/ganache-cli/build/ganache-core.node.cli.js:52:378894)\n    at listOnTimeout (timers.js:324:15)\n    at processTimers (timers.js:268:5)',
     name: 'Error' } }

**Comment by davidmurdoch** [comment]
Added in Ganache v7. See https://github.com/trufflesuite/ganache/releases/tag/v7.0.0 for details!
