### ISSUE TITLE
eth_signTransaction not supported

### ISSUE THREAD

**Issue by wolever** [trufflesuite/ganache#408]
As of Ganache 6.2.1, using `web3.eth.signTransaction(...)` returns `Method eth_signTransaction not supported`.

We run our test suite against ganache, and some tests can't run because of this.

**Comment by szerintedmi** [comment]
I think it has been fixed.
I'm on Ganache CLI v6.4.2 (ganache-core: 2.5.4) and I can sign using web3js-beta36:
```
web3.eth.accounts.signTransaction(txToSign, privateKey)
```

**Comment by nivida** [comment]
``web3.eth.accounts.signTransaction`` !== ``web3.eth.signTransaction`` :) @szerintedmi

**Comment by szerintedmi** [comment]
hoops :)

**Comment by davidmurdoch** [comment]
`eth_signTransaction` is not currently part of the Ethereum JSON-RPC spec. Here is the EIP issue proposing to add it: ethereum/EIPs#728

With that said, it looks like geth and parity already support it, as well as web3 and MetaMask.

As long as geth and parity agree on the implementation I don't see any harm in adding it to gananche.

**Comment by CJ42** [comment]
I solved this by creating new accounts using `web3.eth.accounts.wallet.create(x)' (where x = number of accounts I want to generate).

I then associated the newly created accounts to some global variables accessible through my tests. See below:

```javascript
contract("My Contract", async (accounts) => {

    let firstAccount,
        secondAccount,
        thirdAccount

    before(async () => {
        await web3.eth.accounts.wallet.create(3) // create 3 accounts

        firstAccount = web3.eth.accounts.wallet[0]
        secondAccount = web3.eth.accounts.wallet[1]
        thirdAccount = web3.eth.accounts.wallet[2]
    })

    // tests here...

})
```

I was then able to sign data within my tests, using either the:
- `privateKey` property 
or 
`sign(...)` method, available in each of these new accounts

I could then sign in two ways

```javascript
// method 1
web3.eth.accounts.wallet[firstAccount].sign("Message To Sign")

// method 2
web3.eth.accounts.sign("Message To Sign", firstAccount.privateKey)
```

See response on Ethereum StackExchange question: [_Sign data with private key inside a truffle test file_](https://ethereum.stackexchange.com/a/106925/21704)

**Comment by MicaiahReid** [comment]
This has been implemented in Ganache v7. See our [Upgrade Guide](https://github.com/trufflesuite/ganache/blob/develop/UPGRADE-GUIDE.md) if you want to use this feature!
