### ISSUE TITLE
Block hash is rarely used to identify blocks; I'd remove it from getting top billing in the block card

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/ganache#42]
<img width="401" alt="screen shot 2017-07-26 at 9 25 27 am" src="https://user-images.githubusercontent.com/92629/28632288-e1f5eb70-71e4-11e7-87f6-9de28aaa04ea.png">

The block hash is less important than block number, gas used and mined on. We shouldn't give it top billing as developers are unlikely to use it day to day. It's likely blockhash should exist when you click into a block to get more information about a specific block.

**Comment by johnmcdowall** [comment]
Closing this now as the new layouts take care of the issues
