### ISSUE TITLE
System Error when running Ganache 1.1.0-beta.1 on darwin

### ISSUE THREAD

**Issue by vveerrgg** [trufflesuite/ganache#422]
was testing the idea of using Ganache on my local network... seems like the IP address is triggering some sort of crash on re-launch.  

PLATFORM: darwin
GANACHE VERSION: 1.1.0-beta.1

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 192.168.2.132:7545
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with configuration: {"hostname":"192.168.2.132","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"mnemonic":"candy maple cake sugar pudding cream honey rich smooth crumble sweet treat","vmErrorsOnRPCResponse":true}
```

**Comment by vveerrgg** [comment]
A bit of context... I was on my home network where I have the network IP for that local network. 

BUT... once I re-launched the app while on my work network... my IP address changed to 172.20.10.2 

Looks like the IP address mis.configuration causes the app to crash with no recovery.  

Was able to reset the network address by finding the Settings file (_~/Library/Application Support/Ganache_) and rewriting it to a **127.0.0.1** state. 

Was a work-around, but the app could DEFINITELY would benefit from a feature/function that checks the IP address of the machine vs. the Settings file and reverts the settings file to 127.0.0.1 when they are not the same.... Or some other way of interrupting the launch and instructing the user to choose their IP address or something.

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #666. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.
