### ISSUE TITLE
Ganache incorrectly sends a "to address" of 0x000...000 when it should return null

### ISSUE THREAD

**Issue by ricmoo** [trufflesuite/ganache#425]
## Expected Behavior

The `getTransaction` response's `to` field should be `null`. The `to` field is allowed to be the zero address, and thus that value does no indicate contract creation, and provides an ambiguous response.

## Current Behavior

The `to` field is `0x0000000000000000000000000000000000000000`.

## Steps to Reproduce (for bugs)

Here is a simple example to reproduce this issue:

https://gist.github.com/ricmoo/c2e5c3edbd951a390eac3177deea84a9

## Context

This issue is affecting ethers.js and it's ability to return a meaningful transaction object.

## Your Environment

- MacOS
- Ganache 1.0.2 (downloaded DMG)
- ethers 3.0.6

**Comment by davidmurdoch** [comment]
Thanks @ricmoo for reporting this. I've confirmed that this is an issue and will have a fix for it shortly!
