### ISSUE TITLE
Debian Package Install Fails on Ubuntu 16.04.3

### ISSUE THREAD

**Issue by DiscRiskandBisque** [trufflesuite/ganache#45]
## Description

The Debian package installer progresses to about 20%, then fails. Does not close/crash Ubuntu Software Center, just resets the installer progress to 0 and returns the button from "Installing..." to "Install".

I'm not sure how Electron compiles this so it may literally only be a Debian-compatible package. Other software I've used will install via a .deb on Ubuntu though so thought I'd mention. Note: The App Image variant works!

## Steps to reproduce

Open the .deb installer in Ubuntu 16.04.3.

# Versions

- OS: Ubuntu 16 LTS (16.04.3)
- Node/NPM: 6.11.2 / 3.10.10

**Comment by seesemichaelj** [comment]
This is out of date; we don't even produce `.deb` binaries anymore. Closing this. We will reopen if it becomes an issue again.
