### ISSUE TITLE
Close, Minimize and Maximize Buttons Unresponsive in Ubuntu 16.04.3

### ISSUE THREAD

**Issue by DiscRiskandBisque** [trufflesuite/ganache#46]
## Description

Clicking the close, minimize or maximize buttons behaves as if I'm just dragging the title bar in an off-button location.

If I double click the title bar to maximize the window, the system close/min/max buttons that appear in the toolbar do function as normal.

## Steps to reproduce

Install Ganache via the App Image, open and click one of the aforementioned buttons.

# Versions

- OS: Ubuntu 16 LTS (16.04.3)
- Node/NPM: 6.11.2 / 3.10.10

**Comment by benjamincburns** [comment]
> You're good to close that issue. It was related to custom buttons used before we decided to keep the OS window frame.

^ Sent to me out of band from @DiscRiskandBisque.
