### ISSUE TITLE
Ganache is really resource-heavy

### ISSUE THREAD

**Issue by macbem** [trufflesuite/ganache#465]
The whole app works fine, but my fans spin up immediately when I open the Ganache interface. When I use it in the background, it's okay.

I'm on macOS Sierra, on a 2015 Macbook Pro - quad core i7, 16 gigs of ram. 

How to reproduce?

Deploy a contract to Ganache-provided RPC. Connect to the contract via web3.js (create a contract instance in JS). Focus on the GUI - your fans will probably get loud in a flash.

**Comment by seesemichaelj** [comment]
Hey @macbem thanks for reporting this! Unfortunately, this one is going to be a little more tough to track down. I am not seeing a noticeable difference in resources consumed by Ganache 1.1.0 when I deploy a contract using injected web3.js.

I'll need more reproducible steps (i.e. which contract to deploy), and I'd like to see a screenshot of your system monitor showing the resources consumed by Ganache. I definitely believe you, but I'll need a little bit more for me to reproduce it and fix it.

Thanks!

**Comment by seesemichaelj** [comment]
Closing this as I'm not sure what we can really do to address this.

Running a bunch of tests with automining immediately turned on can potentially max out the single-threaded process CPU wise. If anything, performance would be in `ethereumjs-vm` rather than ganache.
