### ISSUE TITLE
Ganache chews through storage space. Any way to combat this?

### ISSUE THREAD

**Issue by coreycaplan3** [trufflesuite/ganache#485]
* [x] I asked about this on [gitter](https://gitter.im/ConsenSys/truffle)

* Link to question on [gitter](https://gitter.im/ConsenSys/truffle?at=5d7fdd313cc2b87edf1510cc)

## Current Behavior

I'm running ganache in a docker instance on AWS and it's currently chewing through storage space at an unbelievable pace (about 0.4Gb every hour). The chain currently receives a tx every 15 seconds (no more than 2 to 3 txs). Is there any way to prune the database or slow down the speed at which it grows?

## Expected Behavior

To not grow by 400 megabytes every hour.

## Possible Solution

Either some way to actively prune the database or perhaps there's something I'm not aware of that could help alleviate this. Any and all help/recommendations are welcome!

## Steps to Reproduce (for bugs)

It should be as simple as creating your own chain and sending a steady stream of transactions to it.

## Your Environment
* Version used:
* Version of Truffle/Remix/Other tools used: 6.7.0 (ganache-cli) 2.8.0 (ganache-core)
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [x] 8.x, [ ] 9.x
* Operating System and version (include distro if Linux):
* Link to your project or repro gist: N/A
* Commit hash to use with above link for reproduction: N/A
* I intend to submit a pull request to fix this issue: [ ]

**Comment by coreycaplan3** [comment]
Just an update on this - it didn't help much and actually caused tremendous slow-downs once I had ~40,000+ blocks accumulated. I reverted back to using the standard DB. Thanks for the help though and I'll keep this issue open.

**Comment by davidmurdoch** [comment]
Version 7 uses a new database format that is much more compact than our old file-based storage, so I'm closing this since I believe it to be resolved. Please comment below or open a new issue if you find this to still be a problem.
