### ISSUE TITLE
Can't make a int variable value = 0

### ISSUE THREAD

**Issue by Atreb92** [trufflesuite/ganache#499]
- Setting ganache to mine a block every 30 seconds
- Deploying a smart contract using https://remix.ethereum.org compiler with the following code:

`pragma solidity ^0.4.0;
contract Counter {
    int private count = 2;
    function incrementCounter() public {
        count = count + 1;
    }
    function decrementCounter() public {
        count -= 1;
    }
    function getCount() public constant returns (int) {
        return count;
    }
    function reset() public {
        count = 0;
    }
}`

Whenever i try to decrease the count value to 0 or reset it the operation won't be accepted or the block won't be mined (60 seconds between two blocks instead of 30, the transaction block didn't get mined)

## Expected Behavior
Should be able to set a variable to 0 

## Steps to Reproduce (for bugs)
Using the code i pasted above
1. Deploy the contract to the blockchain
2. Decrease the counter using decrementCount() function (this should make count = 1)
3. Repeat the same operation

## Your Environment
Error happens in both 1.1.0 stable and beta version. I'm using debian as host system and MyEtherWallet to interact with the blockchain.

**Comment by seesemichaelj** [comment]
@davidmurdoch said that he tried to reproduce your steps, and everything seemed fine. Please try again, making sure you have the latest versions of everything. If you still have issues, please open a new issue. Thanks!
