### ISSUE TITLE
how to config ganache to support web3j

### ISSUE THREAD

**Issue by zcc1234567** [trufflesuite/ganache#516]
when I use web3j to observe events which run on ganache,I can not receive callback.
But,when I use geth to create a network,it worked.And I can receive every event I want to get.
Does ganache not support web3j?or other problem?

**Comment by benjamincburns** [comment]
Hi @zcc1234567 - can you please ask support questions like these in our public [gitter channel](https://gitter.im/ConsenSys/truffle)?
