### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by werber** [trufflesuite/ganache#524]
I've been running Ganache in local network having an ip assigned 192.168.20.100 but later I've moved to another place and now having assigned ip 192.168.1.204. When I rerun Ganache, I get message that something wrong happened and I can RELAUNCH application. When I press on Relaunch, it reloads an app and shows that same error. Kinda looping, can't see list of accounts/etc.

PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 192.168.20.100:9545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"192.168.20.100","port":9545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by werber** [comment]
This issue on Mac OS can be solved by removing Ganache config like this:
`rm ~/Library/Application\ Support/Ganache/Settings`
I believe that same can be done on other systems simply either editing config and removing entries with old ip addresses or deleting config completely.

**Comment by karneaud** [comment]
@werber true. But are you able to connect externally?

**Comment by werber** [comment]
@karneaud if you mean to connect externally to Ganache so other people could tests my smart contracts using f.g. MetaMask - No. 
If you mean whether it happens with external IP addresses which are dynamic - yes, the same with them.
