### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by stevenocean** [trufflesuite/ganache#548]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: net::ERR_CONNECTION_RESET
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
T+256ms: Ganache started successfully!
T+256ms: Waiting for requests...
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this! Unfortunately these logs aren't enough for us to track down the specific issue. I'm going to close this for now.

If it happens again, please submit a new issue. It would be helpful if you can add details as to what was happening/what you were doing when the error happened.

Thanks!
