### ISSUE TITLE
bug when running truffle migrate --reset

### ISSUE THREAD

**Issue by etdej** [trufflesuite/ganache#560]
Ganache GUI suggested me to raise a github issue with this error.
OS : OSX 10.11
Context : running truffle migrate --reset to deploy my contracts since the first migration

TypeError: Cannot read property 'pop' of undefined
    at f.m._updateNode (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:369:1)
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:121:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:524:1
    at e (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:478:1)
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:519:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:188:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/util.js:29:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:38:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:287:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/util.js:29:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:170:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/database/levelupobjectadapter.js:41:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/level-sublevel/shell.js:107:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/level-sublevel/nut.js:129:1
    at /node_modules/ganache-cli/build/webpack:/ganache/node_modules/cachedown/index.js:68:1
    at ReadFileContext.callback (/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/database/filedown.js:34:1)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

**Comment by etdej** [comment]
I had a second error when trying to relaunch Ganache because port 7545 did not close properly. 

Error: listen EADDRINUSE 127.0.0.1:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by seesemichaelj** [comment]
Hey @etdej, thanks for reporting this! Sorry it's taken awhile for us to respond.

These are two separate issues.
- The first is the issue in #669. I believe this issue was fixed in `v1.1.0`, and I suspect you are running on `v1.0.2`.
- The second is in #665. This issue has been addressed in `v1.2.0`

I suggest upgrading to the latest version of Ganache. If you still see errors on `v1.2.1+`, please submit a new issue.

Thanks for being patient with us!
