### ISSUE TITLE
Cannot install ganache on Windows 10

### ISSUE THREAD

**Issue by M00nfleck** [trufflesuite/ganache#594]
When installing using Ganache.appx error occurred with reason 
  App installation failed with error message: The system cannot find the file specified. (0x80070002)

## Your Environment

* Version used: 1.1.0.0 or 1.0.2.0
* Operating System and version: Laptop Win10 Pro

**Comment by M00nfleck** [comment]
Was able to fix using chkdsk /r command line
https://www.youtube.com/watch?v=WLETFLXJOPc&t=64s

**Comment by seesemichaelj** [comment]
Well, this sounds like a Windows problem and I'm not sure if there's anything we can do to prevent it :/

Thanks so much for reporting this and looking into it!

**Comment by rachanakhilare** [comment]
I am facing same problem
