### ISSUE TITLE
System Error when running Ganache 1.1.0 on linux

### ISSUE THREAD

**Issue by escursionista** [trufflesuite/ganache#601]
got this error while amending 127.0.0.1 to localhost and port from 7545 to 8545
now ganache shows an error on startup. Have to uninstall and reinstall

PLATFORM: linux
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:8545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at GetAddrInfoReqWrap.doListen (net.js:1493:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"localhost","port":8545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #665. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.

**Comment by seesemichaelj** [comment]
Hey @escursionista, if this happens again, checkout the mitigation instructions in #665 to prevent having to uninstall and install. We're working on a better way to let users change settings when these startup errors happen.

I'm guessing you had another application on port `8545` (maybe Mist/geth/Parity?), which is what caused this error.

Thanks again for the feedback!
