### ISSUE TITLE
App installation failed with error message: The system cannot find the file specified. (0x80070002)

### ISSUE THREAD

**Issue by yaash1** [trufflesuite/ganache#605]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by M00nfleck** [comment]
Hey I had the same error. Able to fix using chkdsk /r See https://www.youtube.com/watch?v=WLETFLXJOPc&t=64s

**Comment by seesemichaelj** [comment]
I'm going to close this due to inactivity, and I'll consider @M00nfleck's solution as the fix to this.

Thanks!
