### ISSUE TITLE
Hex encoding of numbers less than 0x10 incorrect

### ISSUE THREAD

**Issue by GoldenDave** [trufflesuite/ganache#608]
Calling eth_getTransactionByHash (and probably many other functions) pads an extra zero in numbers less than 0x10 (not tested for numbers greater)

The specification says : 
Numbers should be encoded as compactly as possible without leading zeroes.

This causes clients written with geth libraries to fail.

 

## Expected Behavior

Nonce, BlockNumber, transactionIndex all have leading zeroes, they should not have.

```
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "hash": "0xfa24d7d51d451fa592722a3306028ba8eb122279cc0de77b2ef1ea3bd7f6f291",
        "nonce": "0xa",
        "blockHash": "0x515cb1c19fcab23af4e845f45a7a2751aaf0fbe2f69cca7c8fb21e0ad4e205c5",
        "blockNumber": "0xb",
        "transactionIndex": "0x0",
        "from": "0xb772f99f5d1d4e46c2a9a15a2a896c4a9f923a89",
        "to": "0xa65c015c9fc18caa281ff8c407174957751c079b",
        "value": "0x0",
        "gas": "0x6691b7",
        "gasPrice": "0x174876e800",
        "input": "0x5da4a1d30000000000000000000000000000000000000000000000000000000000000005"
    }
}
```
## Current Behavior

```
{
    "id": 1,
    "jsonrpc": "2.0",
    "result": {
        "hash": "0xfa24d7d51d451fa592722a3306028ba8eb122279cc0de77b2ef1ea3bd7f6f291",
        "nonce": "0x0a",
        "blockHash": "0x515cb1c19fcab23af4e845f45a7a2751aaf0fbe2f69cca7c8fb21e0ad4e205c5",
        "blockNumber": "0x0b",
        "transactionIndex": "0x00",
        "from": "0xb772f99f5d1d4e46c2a9a15a2a896c4a9f923a89",
        "to": "0xa65c015c9fc18caa281ff8c407174957751c079b",
        "value": "0x0",
        "gas": "0x6691b7",
        "gasPrice": "0x174876e800",
        "input": "0x5da4a1d30000000000000000000000000000000000000000000000000000000000000005"
    }
}
```

## Steps to Reproduce (for bugs)

1. Run almost any truffle based code that performs transactions
2. 
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["<insert hash here>"],"id":1}'  -H "Content-Type: application/json" -X POST localhost:7545
```
3.
4.

## Your Environment

* Version used: 1.1.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1): n/a
* Server type and version: n/a
* Operating System and version: OSX 10.11.6
* Link to your project: n/a

**Comment by GoldenDave** [comment]
This appears to stem from 

https://github.com/ethjs/ethjs-util/blob/master/src/index.js#L4-L33

I reported it to that library from my personal github account

https://github.com/ethjs/ethjs-util/issues/6

**Comment by seesemichaelj** [comment]
Closing as it looks like it was fixed in recent releases. Thanks @GoldenDave!
