### ISSUE TITLE
System Error when running Ganache 1.1.0 on linux

### ISSUE THREAD

**Issue by terrycmchan** [trufflesuite/ganache#613]
Hi,

I just installed the Ganache and setup for my private ethereum network.
However, it prompted the below error.

PLATFORM: linux
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 10.6.72.151:8545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"10.6.72.151","port":8545,"network_id":1613,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

Best Regards,
Terry

**Comment by seesemichaelj** [comment]
Thanks so much for reporting this! This issue will be tracked using #665. I apologize for the catch-all comment. I will be going back through these issues and make sure I don't miss any specific details and make the appropriate comments.

**Comment by seesemichaelj** [comment]
Hi @terrycmchan! Please note that Ganache currently doesn't support listening to other Ethereum clients/RPC. This means if you're running geth or another Ethereum node, you can't use Ganache to browse it or use it as a wallet.

Ganache runs it's own private blockchain and uses the IP/port in the settings to know where to run the RPC server for that blockchain.

I hope that makes sense! You can see how to change the settings in the work around instructions in #665.

If the above is not your situation, then it's possible you're running another application on that port (i.e. Mist/geth/Parity) and should choose a different port.

Let me know if you have any further questions!
