### ISSUE TITLE
`Cannot get state root with uncommitted checkpoints` error when starting ganache forking with infura RPC endpoint

### ISSUE THREAD

**Issue by mds1** [trufflesuite/ganache#618]
Sometimes when starting ganache an error is thrown, and it's fixed simply by restarting ganache. One of the errors I've seen when this happens is described in #615. The other is described in this issue. The error thrown is:

```
Error: Returned error: Cannot get state root with uncommitted checkpoints
```

Unfortunately I did not save off the stack trace when noting this error, so will update this issue to include the stack trace next time I see this error. As mentioned above, restarting ganache will fix the issue.

## Your Environment

* Version used: ganache-core 2.11.2 (no Ganache CLI, as I'm using ganache-core directly through OpenZeppelin Test Environment)

**Comment by mds1** [comment]
Not super helpful, but here's the output from today (different project than the one where I first saw this the other day)

```
Error: Returned error: Cannot get state root with uncommitted checkpoints
 at Context.<anonymous> (test/batch-zkSync-deposit-test.js:59:54)
 at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

cc @seesemichaelj

**Comment by seesemichaelj** [comment]
Thanks for the CC @mds1 

Is this with forking or happens without forking?

**Comment by mds1** [comment]
Oops forgot to mention, only with forking!

**Comment by gnidan** [comment]
@davidmurdoch is currently working on reimplementing forking in a more robust fashion, for the upcoming Ganache v7.0.0 release. Pinging you David to get this on your radar.

Thanks all!

**Comment by davidmurdoch** [comment]
Closing at forking has been reimplemented and these sorts of issues are likely to have been refactored away. Please open a new issue with details if you experience this with Ganache v7+!
