### ISSUE TITLE
Ubuntu: restart ganache from settings screen not functional

### ISSUE THREAD

**Issue by johnmcdowall** [trufflesuite/ganache#63]

**Comment by cameronrll** [comment]
I often have to close it after restarting from settings, and occasionally it refuses to start back up

**Comment by benjamincburns** [comment]
@cameronrll just to be certain, this is a problem in 1.0.2 as well? (It likely would be, we haven’t done anything to address it that I’m aware of)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cameronrll** [comment]
@benjamincburns Initially I had the issue on v1.0.1, however now downloaded v1.0.2 and it appears to be fixed.

**Comment by benjamincburns** [comment]
That's great news, @cameronrll. Please reopen if this problem resurfaces!
