### ISSUE TITLE
corrupted dmg for mac. OS 10.9.5

### ISSUE THREAD

**Issue by levshin1** [trufflesuite/ganache#655]
Downloaded dmg file, it is corrupted and can't be mounted by the OS

 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by seesemichaelj** [comment]
Thanks for reporting this! Our DMG releases currently only support El Capitan or newer. We'll be tracking this issue in #714
