### ISSUE TITLE
Feature: Copy/paste helper for mnemonic (and perhaps addresses and everything else?)

### ISSUE THREAD

**Issue by johnmcdowall** [trufflesuite/ganache#66]

**Comment by caa1982** [comment]
to be able to copy the private Key easly would be very helpful indeed

**Comment by seesemichaelj** [comment]
@cashlionjp thanks for reaching out before starting! No one is working this currently, but since this has a UI impact, I'm going to CC @DiscRiskandBisque and @adrianmcli if they have any comments/suggestions. As far as I'm concerned, you can give it a shot! Not sure what UI/UX vision Josh and Adrian might have for this however

**Comment by cashlionjp** [comment]
Awesome!  I've always wanted to see the feature.  To be honest, I did start poking around a bit already but I'm sure its wrong in a million ways: https://github.com/cashlionjp/ganache/tree/clipboard

**Comment by zach-is-my-name** [comment]
I'm shaky on what a 'mnemonic' is and if the following aligns with that but a key feature in the GUI would be to highlight any address and have a button to copy it clipboard or have it done automatically (like Mist).  It may not save clicks, but the UI should acknowledge this workflow IMHO

**Comment by DiscRiskandBisque** [comment]
Closing because all data is available for copy/paste since this issues was opened, but please re-open if further comments indicate that the problem persists. Feel free to tag maintainers if there is no reply to further comments.

**Comment by seesemichaelj** [comment]
@DiscRiskandBisque I believe this feature is to add an icon next to the mnemonic to press-to-copy. I don't think this issue is obsolete

**Comment by rfikki** [comment]
Is this in the works? This is a needed feature ASAP

**Comment by seesemichaelj** [comment]
@rfikki No this feature is current not in the works. You definitely can select the mnemonic with your mouse and press Ctrl+C (Command+C for Mac) to copy currently

**Comment by rfikki** [comment]
No problem, just wanted to make sure I was not missing something in my setup.
