### ISSUE TITLE
Handle `EADDRINUSE` Network Startup Error

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache#665]
Several users are experiencing the below error. This issue will serve as the main issue to address this error.

```
Error: listen EADDRINUSE <IP_ADDRESS>:<PORT>
```

## Potential Causes
- There is a possible bug in Ganache where if it restarts quickly, the port isn't unbound before restart.
- There is more than one instance of Ganache running; which is not supported currently
- There is another program using that port

## Mitigations/Work-arounds (aka how to fix the issue until we patch this)
- Stop all instances of Ganache, wait a minute, and then only start one instance of Ganache
- Change the interface and/or port in the `Settings` file as to prevent collisions from another program (be sure to restart Ganache after saving the `Settings` file):
  - MacOS: `~/Library/Application\ Support/Ganache/Settings`
  - Windows: `%APPDATA%\Ganache\Settings`
  - Linux: either `$XDG_CONFIG_HOME/Ganache/Settings` or `~/.config/Ganache/Settings`

## Description
As part of this issue, the following will be addressed:
- Determine why these errors are happening
- Address all causes for this same symptom (and open new issues if the cause is drastically different)
- Add a message instead of the error screen which will say that the IP/Port combo used is conflicting with another process, providing some generic instructions for trying to solve the problem before submitting an issue on GitHub
- Allow users to change settings rather than being stuck on an error page

Work will likely overlap with #666

**Comment by yadav26** [comment]
HI
There were more then two scenerios when issue occur
1. Cygwin mintty.exe consuming exhuberant physical memory on launching
After installing Ganach MetaMask I was trying to run tests on DAPP, when system froze, after multiple trial errors, it is found mintty.exe suddenly started consuming 16 GB memory with in no time
Solution - Reinstalling Cygwin fixed the issue.

2. Switching from Private to Main Network in MetaMask caused sudden system reboot.
There was a single instance of the Ganach running and ran webserver lite-server. While trying to get the candidate data on the explorer window , started playing around with metamask. And suddenly system hard reset occur. Possible a unrecoverable critical system error. Sent the logs and raised a ticket.

3. Till now I am not able to run the voting sample application code, no candidates list. Is it the firewall or need a different port to run server / Ganach.

Thanks
Anshul

**Comment by seesemichaelj** [comment]
@yadav26 By the sound of it, you're having a conflicting port with some other application that is perhaps starting on reboot. I would choose a different port in your settings. If you cannot access the GUI, see the first comment in this issue to find where to change the config file
