### ISSUE TITLE
Handle `EADDRNOTAVAIL` Network Startup Error

### ISSUE THREAD

**Issue by seesemichaelj** [trufflesuite/ganache#666]
Several users are experiencing the below error. This issue will serve as the main issue to address this error.

```
Error: listen EADDRNOTAVAIL <IP_ADDRESS>:<PORT>
```

## Potential Causes
- The hostname/IP address provided was typed incorrectly (i.e. `128.0.0.1` instead of the correct `127.0.0.1`)
- The hostname/IP address provided is a remote host (aka an IP address that doesn't belong to the computer that is running Ganache)
  - This typically happens when users try to point Ganache to another network (i.e. Ropsten, Rinkeby, Mainnet). Ganache currently doesn't support listening/passing-through other networks.
  - It could also happen if someone is trying to instantiate a blockchain that runs on another computer in the network. Ganache also doesn't support this kind of remote activity
- It appears that users notice this error after another error/crash. This makes me think the server process is not stopping cleanly, causing the port to not be unbound.

## Mitigations/Work-arounds (aka how to fix the issue until we patch this)
- Change the hostname/IP address in the `Settings` file as to prevent collisions from another program (be sure to restart Ganache after saving the `Settings` file):
  - MacOS: `~/Library/Application\ Support/Ganache/Settings`
  - Windows: `%APPDATA%\Ganache\Settings`.
  - Linux: either `$XDG_CONFIG_HOME/Ganache/Settings` or `~/.config/Ganache/Settings`.

## Description
As part of this issue, the following will be addressed:

- Determine why these errors are happening
- Address all causes for this same symptom (and open new issues if the cause is drastically different)
- Add a message instead of the error screen which will say that the IP/Port combo used is invalid (and why), providing some generic instructions for trying to solve the problem before submitting an issue on GitHub
- Allow users to change settings rather than being stuck on an error page

Work will likely overlap with #665

**Comment by DiegoEscalonaRodriguez** [comment]
Works!
