### ISSUE TITLE
System Error when running Ganache 1.1.0 on win32

### ISSUE THREAD

**Issue by Umesh2Patel** [trufflesuite/ganache#671]
I am trying to connect to Rinkeby test Network using Ganache.

PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 35.196.1.182:8545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+1ms: Starting server with initial configuration: {"hostname":"35.196.1.182","port":8545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
Hi! Thanks for reporting this!

Unfortunately Ganache isn't currently intended as a client or wallet to any of the public Ethereum networks. We're tracking on how to better communicate this and handle the error better in #666

In the meantime you can change the network settings to point to your localhost and open port by modifying the file located at C:\Users\youruser\AppData, try each of the folders here and look for a folder called Ganache with a file named Settings. Modifying that file to have a host am of 127.0.0.1 and port of 7545 should get you running again
