### ISSUE TITLE
idea: add in warning to help switch over to new "pending tx" mode

### ISSUE THREAD

**Issue by davidmurdoch** [trufflesuite/ganache#674]
If a transaction is submitted with a future nonce (not immediately executable), and no other requests coming for _n_ seconds, we could log a helpful message that there is a pending transaction, and why it is pending.

We could also/instead, log useful information about each transaction, in a way that informs the user that the transaction will not be mined immediately because of its future nonce.

/cc @cds-amal

**Comment by gnidan** [comment]
@eggplantzzz graciously implemented this already.

**Comment by eggplantzzz** [comment]
I'm actually not sure this was done, I implemented a warning when people are using the newer instamine feature and request a tx that is pending. There might be more that this ticket suggests be done.

**Comment by davidmurdoch** [comment]
Discussed this with @eggplantzzz and @micaiahreid and I think we should add this for 7.1.0, if at all. We could do it behind a new opt-in `--hints` flag, or by default behind an opt-out `--no-hints` flag.

**Comment by MicaiahReid** [comment]
Closing cause @davidmurdoch regrets opening it.
