### ISSUE TITLE
Bug: Test blockchain does not update string variable when the new one is shorter

### ISSUE THREAD

**Issue by scelts** [trufflesuite/ganache#678]
## Expected Behavior
String variables should be updated with public setter functions

## Current Behavior
They are not if the new string is much shorter than the existing one in the blockchain.

## Steps to Reproduce (for bugs)
Publish this contract:
```javascript
pragma solidity ^0.4.19;

contract StringCheck{
    string public testString;
    
    constructor () public {}
    
    function set(string _s) public {
        testString = _s;
    }
}
```

Set the testString to "1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890" - it should change the testString.

After you set it to the long string, set it to "123" - it does not change the testString.

Making it longer than the existing one works.

## Environment
* Version used: 1.1.0
* Operating System and version: Windows 7 and 10

**Comment by seesemichaelj** [comment]
Hey @scelts! You say that the string must be significantly shorter to not take? What about 1 or 2 characters shorter?

This may be prudent and unhelpful, but strings in solidity/EVM do not act like normal strings. They're a special case of dynamically-sized UTF-8 encoded byte arrays (see http://solidity.readthedocs.io/en/develop/types.html#dynamically-sized-byte-array). It's not jumping out to me why you're seeing the behavior that you are, but I'm going to think about it.

If you don't see this behavior on a testnet/mainnet (i.e. or using geth client), then your issue likely resides within the EVM implementation that Ganache uses: https://github.com/ethereumjs/ethereumjs-vm. I'd look into reaching out to them to see if they may know the issue (and whether or not this is a feature and not a bug)

**Comment by seesemichaelj** [comment]
I'm not sure if I'd expect a shorter string. I'm not entirely sure how the string type is implemented, but it could be something like:

```
set(val) {
  if (this.capacity < val.length) {
    this = new bytes[val.length]
  }

  for (i = 0; i < val.length; i++) {
    this[i] = val[i]
  }
}
```

If this is the case, then I wouldn't expect a shorter string; I'd expect just as long of a string with the first 3 characters changed. I'm thinking this actually may be a solidity (https://github.com/ethereum/solidity) question/issue (as I'd expect the same behavior in the "test blockchain" as a geth implementation).

**Comment by scelts** [comment]
The contract I pasted above should update the string - the getter should always return the new string, regardless on the way it's stored - i.e. it does not change only the first 3 characters.

It happens only when I use ganache for local testing. On ropsten network or in remix (also JavaScript VM) the contract executes as expected - updates the string.

I don't know if it's just ganache but I wasn't sure where to submit the bug. It would be nice if someone could replicate it, as it's quite a strange behaviour so I'm not sure if I'm doing something wrong
