### ISSUE TITLE
Support running multiple instances of Ganache simultaneously

### ISSUE THREAD

**Issue by jakicho** [trufflesuite/ganache#684]
This is what happened when I launch 2 ganaches windows at the same time:

PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
This is just for the record (for me really in the future): Being able to run multiple instances was explicitly prohibited in https://github.com/trufflesuite/ganache/commit/0397613b70f7e341ce7bc2fb6e5f170f00cd5fcb

**Comment by seesemichaelj** [comment]
The ability to run multiple instances of Ganache UI is coming with the upcoming 2.0 release. With the introduction of Workspaces, you can now have different configurations with different port numbers to enable this feature.

If you want to get notified when 2.0 is released, you should checkout Github's new "watch Releases Only option":
![image](https://user-images.githubusercontent.com/549323/49690518-85503c80-fb00-11e8-8104-a954e0410525.png)
You'll get notified when new releases are made if you select that `Releases Only` option. The auto updater should also notify you when a release is ready too!
