### ISSUE TITLE
System Error when running Ganache 1.1.0 on win32

### ISSUE THREAD

**Issue by satyajit007** [trufflesuite/ganache#694]
PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 192.168.100.123:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"192.168.100.123","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this! This is actually being tracked in #666. Ganache doesn't support listening to other RPCs. By the looks of it, it looks like you're trying to connect to another instance of Ganache that's running on another computer in your network? The `hostname` you provide must be a valid local-to-the-machine-running-ganache network interface.

There are instructions in #666 on how to get your Ganache back up and running in the meantime.

**Comment by satyajit007** [comment]
so how can i use ganache for aws cloud..?

**Comment by seesemichaelj** [comment]
Can you elaborate on what you're trying to accomplish @satyajit007? I don't think I quite understand

**Comment by satyajit007** [comment]
I had install ganache on my machine which is connected to local LAN .. so my blockchain application workes fine.  now I want to setup same on a windows server running in aws environment. so that I can access my application anywhere from the world.

**Comment by seesemichaelj** [comment]
If I'm understanding correctly, you want to deploy your contract onto a private Ganache blockchain. It's currently working fine on a local machine, but you'd like to start a blockchain on an AWS Windows Server. When you start up Ganache on the Windows Server, this is the error you get?

One possible reason: the IP address you put in the `hostname` field is invalid. Check `ipconfig` in the command prompt to see valid ip addresses to use. You can always use `127.0.0.1` which is your loopback IP or `0.0.0.0` which is all network interfaces. You'll need to change your settings file (`%APPDATA%\Ganache\Settings`) to set the hostname variable.

Second: I'm not familiar with Windows Server AWS environments, but it's possible you're having a permissions issue and not being able to listen to a port. If you have admin access, try running Ganache with Administrator access. Perhaps the firewall is preventing you using this port.

**Please use with caution:** Opening the RPC port on a server like this is for advanced users.

Have you considered using a test blockchain like Rinkeby or Ropsten to obtain your goal of testing your application from anywhere? Here's a link to how to deploy to Ropsten using Truffle: https://medium.com/@guccimanepunk/how-to-deploy-a-truffle-contract-to-ropsten-e2fb817870c1

**Comment by satyajit007** [comment]
I installed ganache on central aws server. and now my blockchain application wants to access that ganache. so I put aws serve host address to settings file (%APPDATA%\Ganache\Settings).  when I launch ganache server it gets crash and shows above error. I allow port number from a firewall and from other settings.
