### ISSUE TITLE
System Error when running Ganache 1.1.0 on win32

### ISSUE THREAD

**Issue by lambo4jos** [trufflesuite/ganache#703]
EXPERIENCE: Upon launching the instance of Ganache.exe from the system programs in the start menu, the launch encountered this error. The error looks like it is due to the port already being used. I checked my running processes in the Windows task manager and noticed that there was an orphaned Ganache.exe process that was still running from the previous session which was probably what was using the port. When i ended that orphaned process, and relaunched Ganache.exe, everything launched and began working as expected.

PLATFORM: win32
OS VERSION: Windows 7 Ultimate
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
@lambo4jos Thanks for reporting this. We're actually tracking this issue in #665.

I've noticed the orphaned tasks, and have located a couple of potential causes. Were you using Ganache before you opened this from the start menu? If so, did it crash? Did an error popup? If an error did popup, did you press "RELAUNCH"?

**Comment by lambo4jos** [comment]
@seesemichaelj No problem.

Yes I was using Ganache.exe prior then closed out, Came back a couple hours later to restart Ganache.exe and the error came up when trying to launch it from the start menu. It appeared to start up, and the Ganache start screen showed up, then crashed and provided the prompt to report or relaunch. I tried to relaunch and it didn't work, and the same error came up, so I reported, but first I checked the error and it appeared to be EADDRINUSE so I checked my processes and low and behold that was it, there was a process still running when I closed out of the error screen. So I ended the process and relaunched and it worked

**Comment by seesemichaelj** [comment]
And you're certain it was a EADDRINUSE error the first time it failed?

**Comment by seesemichaelj** [comment]
Perfect. Thank you for the details! It helps out tremendously.

Do you remember how you exited Ganache the first time (a couple of hours ago)? Clicking the X or Alt+F4 or?

**Comment by lambo4jos** [comment]
@seesemichaelj Clicking the X. No worries, glad I could help

**Comment by seesemichaelj** [comment]
Great; if you have more to report regarding this, please use #665 going forward.

Cheers!
