### ISSUE TITLE
System Error when running Ganache 1.1.0 on linux

### ISSUE THREAD

**Issue by cosmicapotheosis** [trufflesuite/ganache#716]
I was using Ganache-CLI, closed it, came back, and switched to using the GUI version. GUI version wouldn't start after several tries, gives the exception below.

Running Ubuntu LTS desktop, issue resolves itself when I reboot.

PLATFORM: linux
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:8545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","port":8545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
How did you close `ganache-cli`? Are you using the same port in `Ganache` and `ganache-cli`?

Just so you know, as far as handling the error smoothly, that is being tracked in #665 and will be in the next release. However, the issue you're bringing up may be an issue with `ganache-cli` not closing ports properly.

**Comment by cosmicapotheosis** [comment]
I just ended the process using ctrl + c before closing the terminal window. The settings are default, and indeed using the same port. 

I just tried this again, to see what would happen, and I didn't have any trouble opening Ganache. The first time I did have ganachi-cli running for a while, possibly while the computer went to sleep several times, I don't know if that may have contributed to the different result.

**Comment by seesemichaelj** [comment]
Thanks for the details! Can you tell me what version of ganache-cli you're using? Probably `npm list -g ganache-cli` will suffice

Bummer it's not super reproducible. Also was hoping this was Windows as ports are wonky there. 

I'm going to go ahead and close this and open an issue in ganache-cli (or core) to follow up the investigation of those ports not being closed under undetermined circumstances. As far as the GUI is concerned, #665 should address everything the GUI can do about it.

I'll link the other issue when it's made.

Thanks again!

**Comment by seesemichaelj** [comment]
Please still get me that version number however, thanks!

**Comment by cosmicapotheosis** [comment]
ganache-cli@6.1.0

**Comment by seesemichaelj** [comment]
Which Ubuntu LTS version are you using? 16.04 or 18.04?

**Comment by cosmicapotheosis** [comment]
hi, 16.04

**Comment by seesemichaelj** [comment]
Alright, I opened https://github.com/trufflesuite/ganache-cli/issues/527 to track the issue with the CLI not closing the port properly
