### ISSUE TITLE
[OSX] - Ganache GUI is taking the whole screen and ignore the bottom dock

### ISSUE THREAD

**Issue by zulhfreelancer** [trufflesuite/ganache#721]
I have an old MacBook Pro mid 2012 model which is still working fine for me. I'm using this MBP at home.

While at work, I'm using another model of MBP, the latest [13 inch model](https://www.apple.com/shop/buy-mac/macbook-pro) without the touch bar.

The Ganache GUI is showing fine in my work MBP. But, when I'm using Ganache GUI in my home MBP, it is taking the whole screen and ignore the bottom dock I have.

This is not happening when I'm using other apps. They all obey the dock and never crossed the dock.

All Ganache GUI features are working fine. But, I feel a bit annoying looking at it because my dock is located on top of it. I didn't manage to drag to scale down the window size. I know Ganache is an Electron app - zooming it out also didn't work.

Would be great if this issue can be fixed in the next release(s).

## Expected Behavior

Ganache on my work MBP:

![image](https://user-images.githubusercontent.com/3416976/41203547-3b43f9a4-6cc8-11e8-9cd5-677dd003bb91.png)

## Current Behavior

Ganache on my home MBP:

![screen shot 2018-06-10 at 3 58 40 pm](https://user-images.githubusercontent.com/3416976/41203536-05414ea6-6cc8-11e8-8fcf-2df63fb5ec19.png)

![screen shot 2018-06-10 at 3 58 44 pm](https://user-images.githubusercontent.com/3416976/41203538-0e9bba54-6cc8-11e8-82d7-990a51dd3b6d.png)

## My Environment (Home MBP)

![screen shot 2018-06-10 at 3 59 10 pm](https://user-images.githubusercontent.com/3416976/41203530-ea715602-6cc7-11e8-964c-d768ebd20730.png)

![screen shot 2018-06-10 at 3 59 15 pm](https://user-images.githubusercontent.com/3416976/41203533-f524e384-6cc7-11e8-8569-f58c1c18cc74.png)

* Ganache version: v1.1.0
* OS and version: OSX Sierra 10.12.6

**Comment by seesemichaelj** [comment]
Thanks for the detailed write up! As far as resizing, there is another issue open for that (#116).

However the dock issue is peculiar! We'll see if we can figure out what the issue is; would also be open for a PR!

**Comment by zulhfreelancer** [comment]
You are welcome!
