### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by heshule** [trufflesuite/ganache#731]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 192.168.50.204:9646
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"192.168.50.204","port":9646,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this! We're tracking this in #666. This error means that you cannot create the RPC server and listen on the interface you provided. You'll have to change the hostname to something else (i.e. `127.0.0.1` or `0.0.0.0`). You can change the settings file located here: `~/Library/Application\ Support/Ganache/Setting`

**Comment by heshule** [comment]
hi,  i would like to kown if the next new vesion will fix this issue, right now our geth instance is running  in another PC, the setting about ip:port is right, because the remix tool can connect to the geth succ wtih the same ip:port.
thx.

**Comment by seesemichaelj** [comment]
Hello @heshule, unfortunately the feature you're talking about (having Ganache connect to another RPC instance) will not be implemented/supported in the next version of Ganache.

Ganache currently only supports creating a new blockchain. The IP:port settings you see in Ganache tell Ganache where to listen/bind the RPC server on. Ganache isn't currently meant as a client/viewer of external blockchain/node data.

The next version of Ganache will prevent you from using a non-local IP address, so you would have never been able to put in another computer's IP address in the field.

We have plans to support this "pass-through" nature, but it won't be in the next version. Looks like the feature you're requesting is being tracked in #50

**Comment by seesemichaelj** [comment]
Eek. I guess #50 was closed. I will open a new issue to track this feature request

**Comment by seesemichaelj** [comment]
This feature will be tracked in #741

**Comment by heshule** [comment]
ooooh. I miss understand Ganache, now i kown how to use it,  and also Ganache is a greate tool.

**Comment by seesemichaelj** [comment]
Awesome; glad you like it! Thanks for contributing by providing error reports and feedback!
