### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by KaelThasWang0919** [trufflesuite/ganache#737]
PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 192.168.1.94:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"192.168.1.94","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by seesemichaelj** [comment]
Thanks for reporting this! We're tracking the issue in #666. You can get your Ganache back up and running by changing the port in the `~/Library/Application\ Support/Ganache/Settings` file. There's a bug which leaves the port open sometimes. We've scheduled a fix for the next release.

**Comment by KaelThasWang0919** [comment]
非常感谢,在你的帮助下问题已经解决
建议在初始界面添加配置选项

**Comment by seesemichaelj** [comment]
Hello @KaelThasWang0919, unfortunately I don't speak Chinese; Google Translate said the above translates to:
> Thank you very much. The problem has been solved with your help.
It is recommended to add configuration options in the initial interface

Glad I could help! The upcoming release will allow you to change the settings. That's what #666 is addressing.
