### ISSUE TITLE
System Error when running Ganache 1.1.0 on darwin

### ISSUE THREAD

**Issue by rushikeshjadhav** [trufflesuite/ganache#752]
Following exception is generated when a non local IP address is given to listen on. The application is not able to recover from this and stuck on this exception every restart.

PLATFORM: darwin
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRNOTAVAIL 192.168.0.100:7545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1302:19)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"192.168.0.100","port":7545,"network_id":5777,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by rushikeshjadhav** [comment]
Modified Settings file located in /Users/{user}/Library/Application Support/Ganache/ to reflect correct ip in server:hostname.

**Comment by seesemichaelj** [comment]
Sounds like you may have found the answer already! We're working on fixing the "not being able to recover thing" and "dont let users pick a non local IP" in #666 to prevent this problem. Glad you were able to figure it out on your own! Thanks for reporting!

**Comment by rushikeshjadhav** [comment]
May be a reset button would help with everything reset including settings.
