### ISSUE TITLE
Broken website link

### ISSUE THREAD

**Issue by BenKaufman10** [trufflesuite/ganache#79]
Hey there,
I just noticed the website link doesn't work.
Currently it's http://truffleframework.com/suite/ganache but the correct one is http://truffleframework.com/ganache/
It's just a small mistake in the project description that bothered me.

Thanks,
Ben

**Comment by bmmpxf** [comment]
Hi @BenKaufman10 . What page(s) have the broken link?

**Comment by 3esmit** [comment]
The one in github project description.

**Comment by bmmpxf** [comment]
Oh right you are. Thanks @3esmit ! I just fixed it. If you see any other bad links, please let us know!
