### ISSUE TITLE
System Error when running Ganache 1.1.0 on win32

### ISSUE THREAD

**Issue by notOccupanther** [trufflesuite/ganache#801]
Hi,
Just reporting this as it suggested sending on the info.  Was using Ganache CLI to run through a tutorial I was getting through.

Ganache could not start initially, so went online to check for errors / solutions and one I found was to try the beta .. and when I installed it, this was the error I received.

N

PLATFORM: win32
GANACHE VERSION: 1.1.0

EXCEPTION:
```
Error: listen EADDRINUSE 127.0.0.1:8545
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at Server.setupListenHandle [as _listen2] (net.js:1319:14)
    at listenInCluster (net.js:1367:12)
    at doListen (net.js:1493:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

APPLICATION LOG:
```
T+0ms: Starting server with initial configuration: {"hostname":"127.0.0.1","network_id":5777,"port":8545,"total_accounts":10,"unlocked_accounts":[],"vmErrorsOnRPCResponse":true}
```

**Comment by notOccupanther** [comment]
Hi,

Just to add.  I noticed the EADDRINUSE section of the error and suspected it thinks there was another instance running (or something on 8545).  Sysinternals PortMon found nothing, so I rebooted.  Still the same error on restart.

So then just went into the 'App Settings' section of the app in the windows Store, clicked 'Repair' and 'Reset', and now the app is working again.

Thanks !

**Comment by seesemichaelj** [comment]
Thanks for reporting this!

I'm not sure why you were initially not being able to use Ganache. You shouldn't have to use an older version to run. We do have an issue with 1.1.0 that leaves an old process of Ganache open (weird you didn't see it) in some cases which would present this error without a reboot (weird that it was still having an issue on reboot).

This kind of sounds like a corrupt settings file, but other notes you've presented don't really align with that either. If this happens again, please see if the `%APPDATA%\Ganache\Settings` file is intact and has readable content (it'll look like JSON object).

The generic bug I was talking about is tracked in #665 which will an easier way to change your port quickly (or other settings). The fix will be in the next release.

I'm going to go ahead and close this hoping it's the same issue as #665. If it's not, then please reopen! Thanks again!
