### ISSUE TITLE
Cannot raise Github issue (414 Request-URI Too Large)

### ISSUE THREAD

**Issue by stoney1989** [trufflesuite/ganache#812]
I frequently encounter a bug in Ganache, "Blockchain process exited prematurely with code '7', due to signal 'null'".
Ganache even gives me a popup to raise a Github issue, unfortunately when I hit the "Raise a Github issue" button, it only opens a tab in my browser with the HTTP error 414.

(affected URI is at the end of this issue)

## Expected Behavior
Tab opens with prefilled Github issues page.

## Current Behavior
Tab opens with HTTP error 414 (Request-URI Too Large)

## Your Environment
PLATFORM: win32
GANACHE VERSION: 1.0.2

## Affected URI
https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Ftrufflesuite%2Fganache%2Fissues%2Fnew%3Ftitle%3DSystem%2520Error%2520when%2520running%2520Ganache%25201.0.2%2520on%2520win32%26body%3D%253C%21--%2520Please%2520give%2520us%2520as%2520much%2520detail%2520as%2520you%2520can%2520about%2520what%2520you%2520were%2520doing%2520at%2520the%2520time%2520of%2520the%2520error%252C%2520and%2520any%2520other%2520relevant%2520information%2520--%253E%250A%250A%250APLATFORM%253A%2520win32%250AGANACHE%2520VERSION%253A%25201.0.2%250A%250AEXCEPTION%253A%250A%2560%2560%2560%250ABlockchain%2520process%2520exited%2520prematurely%2520with%2520code%2520%25277%2527%252C%2520due%2520to%2520signal%2520%2527null%2527.%250A%2560%2560%2560%250A%250AAPPLICATION%2520LOG%253A%250A%2560%2560%2560%250AT%252B153143ms%253A%2520%2520%2520Runtime%2520Error%253A%2520revert%250AT%252B153150ms%253A%2520evm_revert%250AT%252B153162ms%253A%2520evm_snapshot%250AT%252B153177ms%253A%2520eth_blockNumber%250AT%252B153182ms%253A%2520eth_sendTransaction%250AT%252B153241ms%253A%2520%2520%2520Transaction%253A%25200xefe8cfceaa65b85b8eb122ad385adcfbd83edf560de3c5b6c7ccfc6c258f19e8%250AT%252B153241ms%253A%2520%2520%2520Gas%2520usage%253A%2520106932%250AT%252B153241ms%253A%2520%2520%2520Block%2520Number%253A%252015%250AT%252B153241ms%253A%2520%2520%2520Block%2520Time%253A%2520Wed%2520Jul%252004%25202018%252018%253A11%253A35%2520GMT%252B0200%2520%28W.%2520Europe%2520Daylight%2520Time%29%250AT%252B153243ms%253A%2520eth_getTransactionReceipt%250AT%252B153250ms%253A%2520eth_call%250AT%252B153296ms%253A%2520eth_sendTransaction%250AT%252B153345ms%253A%2520%2520%2520Transaction%253A%25200xb01f01a9dcb22bb04223042e252d266f2704b946c3dd2dacbfa4ac7da358dc87%250AT%252B153345ms%253A%2520%2520%2520Gas%2520usage%253A%252018188%250AT%252B153345ms%253A%2520%2520%2520Block%2520Number%253A%252016%250AT%252B153345ms%253A%2520%2520%2520Block%2520Time%253A%2520Wed%2520Jul%252004%25202018%252018%253A11%253A35%2520GMT%252B0200%2520%28W.%2520Europe%2520Daylight%2520Time%29%250AT%252B153348ms%253A%2520eth_getTransactionReceipt%250AT%252B153354ms%253A%2520eth_call%250AT%252B153375ms%253A%2520evm_revert%250AT%252B153406ms%253A%2520evm_snapshot%250AT%252B153420ms%253A%2520eth_blockNumber%250AT%252B153423ms%253A%2520eth_sendTransaction%250AT%252B153470ms%253A%2520%2520%2520Transaction%253A%25200x16e84de8cdaa2354f5513ba3785449043870d63066070a4eab1a8568d5208542%250AT%252B153470ms%253A%2520%2520%2520Gas%2520usage%253A%252023784%250AT%252B153470ms%253A%2520%2520%2520Block%2520Number%253A%252015%250AT%252B153470ms%253A%2520%2520%2520Block%2520Time%253A%2520Wed%2520Jul%252004%25202018%252018%253A11%253A35%2520GMT%252B0200%2520%28W.%2520Europe%2520Daylight%2520Time%29%250AT%252B153473ms%253A%2520eth_getTransactionReceipt%250AT%252B153481ms%253A%2520evm_revert%250AT%252B153493ms%253A%2520evm_snapshot%250AT%252B153510ms%253A%2520eth_blockNumber%250AT%252B153514ms%253A%2520eth_call%250AT%252B153528ms%253A%2520eth_sendTransaction%250AT%252B153593ms%253A%2520%2520%2520Transaction%253A%25200xf7c7fdf0182d3ed3b6cd80b4127a365e8891013b367f0d7988b7f098219df238%250AT%252B153593ms%253A%2520%2520%2520Gas%2520usage%253A%2520106932%250AT%252B153593ms%253A%2520%2520%2520Block%2520Number%253A%252015%250AT%252B153593ms%253A%2520%2520%2520Block%2520Time%253A%2520Wed%2520Jul%252004%25202018%252018%253A11%253A35%2520GMT%252B0200%2520%28W.%2520Europe%2520Daylight%2520Time%29%250AT%252B153596ms%253A%2520eth_getTransactionReceipt%250AT%252B153602ms%253A%2520eth_sendTransaction%250AT%252B153657ms%253A%2520%2520%2520Transaction%253A%25200x2e4bff5bf9a831442ac6f95ddb9f039ac0bd1e5d5665c7873810a22c9dd30c17%250AT%252B153657ms%253A%2520%2520%2520Gas%2520usage%253A%252076932%250AT%252B153657ms%253A%2520%2520%2520Block%2520Number%253A%252016%250AT%252B153657ms%253A%2520%2520%2520Block%2520Time%253A%2520Wed%2520Jul%252004%25202018%252018%253A11%253A35%2520GMT%252B0200%2520%28W.%2520Europe%2520Daylight%2520Time%29%250AT%252B153659ms%253A%2520eth_getTransactionReceipt%250AT%252B153665ms%253A%2520eth_sendTransaction%250AT%252B153724ms%253A%2520%2520%2520Transaction%253A%25200xd7fb1a5ebd881f1a37e46c3fc372b66a6b7f7f0d7392b5b30ce2c866ec23e9e2%250AT%252B153724ms%253A%2520%2520%2520Gas%2520usage%253A%252076932%250AT%252B153724ms%253A%2520%2520%2520Block%2520Number%253A%252017%250AT%252B153724ms%253A%2520%2520%2520Block%2520Time%253A%2520Wed%2520Jul%252004%25202018%252018%253A11%253A35%2520GMT%252B0200%2520%28W.%2520Europe%2520Daylight%2520Time%29%250AT%252B153726ms%253A%2520eth_getTransactionReceipt%250AT%252B153732ms%253A%2520eth_sendTransaction%250AT%252B153793ms%253A%2520%2520%2520Transaction%253A%25200xb61d22da92f7f1df52548c78147390f9ade903ee3728e3f157f5ec9176eaf46e%250AT%252B153793ms%253A%2520%2520%2520Gas%2520usage%253A%252076932%250AT%252B153793ms%253A%2520%2520%2520Block%2520Number%253A%252018%250AT%252B153793ms%253A%2520%2520%2520Block%2520Time%253A%2520Wed%2520Jul%252004%25202018%252018%253A11%253A35%2520GMT%252B0200%2520%28W.%2520Europe%2520Daylight%2520Time%29%250AT%252B153796ms%253A%2520eth_getTransactionReceipt%250AT%252B153802ms%253A%2520eth_call%250AT%252B153812ms%253A%2520eth_sendTransaction%250AT%252B153919ms%253A%2520%2520%2520Transaction%253A%25200xb19ffe6cf54d963bc2cfeee4a48d6b87d86416abd7d7e3bb82352303fb9924aa%250AT%252B153919ms%253A%2520%2520%2520Gas%2520usage%253A%252059260%250AT%252B153919ms%253A%2520%2520%2520Block%2520Number%253A%252019%250AT%252B153919ms%253A%2520%2520%2520Block%2520Time%253A%2520Wed%2520Jul%252004%25202018%252018%253A11%253A35%2520GMT%252B0200%2520%28W.%2520Europe%2520Daylight%2520Time%29%250AT%252B153922ms%253A%2520eth_getTransactionReceipt%250AT%252B153927ms%253A%2520eth_call%250AT%252B153945ms%253A%2520eth_call%250AT%252B153964ms%253A%2520eth_call%250AT%252B153989ms%253A%2520eth_call%250AT%252B154007ms%253A%2520C%253A%255CProgram%2520Files%255CWindowsApps%255CGanache_1.0.2.0_x64__zh355ej5cj694%255Capp%255Cresources%255Capp%255Cnode_modules%255Cganache-cli%255Cbuild%255Clib.node.js%253A63898%250AT%252B154007ms%253A%2520var%2520Module%253Bif%28%21Module%29Module%253D%28typeof%2520Module%21%253D%253D%2522undefined%2522%253FModule%253Anull%29%257C%257C%257B%257D%253Bvar%2520moduleOverrides%253D%257B%257D%253Bfor%28var%2520key%2520in%2520Module%29%257Bif%28Module.hasOwnProperty%28key%29%29%257BmoduleOverrides%255Bkey%255D%253DModule%255Bkey%255D%257D%257Dvar%2520ENVIRONMENT_IS_WEB%253Dfalse%253Bvar%2520ENVIRONMENT_IS_WORKER%253Dfalse%253Bvar%2520ENVIRONMENT_IS_NODE%253Dfalse%253Bvar%2520ENVIRONMENT_IS_SHELL%253Dfalse%253Bif%28Module%255B%2522ENVIRONMENT%2522%255D%29%257Bif%28Module%255B%2522ENVIRONMENT%2522%255D%253D%253D%253D%2522WEB%2522%29%257BENVIRONMENT_IS_WEB%253Dtrue%257Delse%2520if%28Module%255B%2522ENVIRONMENT%2522%255D%253D%253D%253D%2522WORKER%2522%29%257BENVIRONMENT_IS_WORKER%253Dtrue%257Delse%2520if%28Module%255B%2522ENVIRONMENT%2522%255D%253D%253D%253D%2522NODE%2522%29%257BENVIRONMENT_IS_NODE%253Dtrue%257Delse%2520if%28Module%255B%2522ENVIRONMENT%2522%255D%253D%253D%253D%2522SHELL%2522%29%257BENVIRONMENT_IS_SHELL%253Dtrue%257Delse%257Bthrow%2520new%2520Error%28%2522The%2520provided%2520Module%255B%2527ENVIRONMENT%2527%255D%2520value%2520is%2520not%2520valid.%2520It%2520must%2520be%2520one%2520of%253A%2520WEB%257CWORKER%257CNODE%257CSHELL.%2522%29%257D%257Delse%257BENVIRONMENT_IS_WEB%253Dtypeof%2520window%253D%253D%253D%2522object%2522%253BENVIRONMENT_IS_WORKER%253Dtypeof%2520importScripts%253D%253D%253D%2522function%2522%253BENVIRONMENT_IS_NODE%253Dtypeof%2520process%253D%253D%253D%2522object%2522%2526%2526%2522function%2522%253D%253D%253D%2522function%2522%2526%250AT%252B154007ms%253A%2520%250AT%252B154007ms%253A%2520TypeError%253A%2520Cannot%2520read%2520property%2520%2527get%2527%2520of%2520undefined%250AT%252B154007ms%253A%2520%2520%2520%2520%2520at%2520dbGet%2520%28C%253A%255CProgram%2520Files%255CWindowsApps%255CGanache_1.0.2.0_x64__zh355ej5cj694%255Capp%255Cresources%255Capp%255Cnode_modules%255Cganache-cli%255Cbuild%255Clib.node.js%253A56029%253A7%29%250AT%252B154007ms%253A%2520%2520%2520%2520%2520at%2520C%253A%255CProgram%2520Files%255CWindowsApps%255CGanache_1.0.2.0_x64__zh355ej5cj694%255Capp%255Cresources%255Capp%255Cnode_modules%255Cganache-cli%255Cbuild%255Clib.node.js%253A17614%253A5%250AT%252B154007ms%253A%2520%2520%2520%2520%2520at%2520C%253A%255CProgram%2520Files%255CWindowsApps%255CGanache_1.0.2.0_x64__zh355ej5cj694%255Capp%255Cresources%255Capp%255Cnode_modules%255Cganache-cli%255Cbuild%255Clib.node.js%253A23091%253A20%250AT%252B154007ms%253A%2520%2520%2520%2520%2520at%2520iterate%2520%28C%253A%255CProgram%2520Files%255CWindowsApps%255CGanache_1.0.2.0_x64__zh355ej5cj694%255Capp%255Cresources%255Capp%255Cnode_modules%255Cganache-cli%255Cbuild%255Clib.node.js%253A23172%253A13%29%250AT%252B154007ms%253A%2520%2520%2520%2520%2520at%2520C%253A%255CProgram%2520Files%255CWindowsApps%255CGanache_1.0.2.0_x64__zh355ej5cj694%255Capp%255Cresources%255Capp%255Cnode_modules%255Cganache-cli%255Cbuild%255Clib.node.js%253A23184%253A29%250AT%252B154007ms%253A%2520%2520%2520%2520%2520at%2520C%253A%255CProgram%2520Files%255CWindowsApps%255CGanache_1.0.2.0_x64__zh355ej5cj694%255Capp%255Cresources%255Capp%255Cnode_modules%255Cganache-cli%255Cbuild%255Clib.node.js%253A22954%253A16%250AT%252B154007ms%253A%2520%2520%2520%2520%2520at%2520C%253A%255CProgram%2520Files%255CWindowsApps%255CGanache_1.0.2.0_x64__zh355ej5cj694%255Capp%255Cresources%255Capp%255Cnode_modules%255Cganache-cli%255Cbuild%255Clib.node.js%253A17619%253A7%250AT%252B154007ms%253A%2520%2520%2520%2520%2520at%2520C%253A%255CProgram%2520Files%255CWindowsApps%255CGanache_1.0.2.0_x64__zh355ej5cj694%255Capp%255Cresources%255Capp%255Cnode_modules%255Cganache-cli%255Cbuild%255Clib.node.js%253A56034%253A9%250AT%252B154007ms%253A%2520%2520%2520%2520%2520at%2520dispatchError%2520%28C%253A%255CProgram%2520Files%255CWindowsApps%255CGanache_1.0.2.0_x64__zh355ej5cj694%255Capp%255Cresources%255Capp%255Cnode_modules%255Cganache-cli%255Cbuild%255Clib.node.js%253A36358%253A36%29%250AT%252B154007ms%253A%2520%2520%2520%2520%2520at%2520C%253A%255CProgram%2520Files%255CWindowsApps%255CGanache_1.0.2.0_x64__zh355ej5cj694%255Capp%255Cresources%255Capp%255Cnode_modules%255Cganache-cli%255Cbuild%255Clib.node.js%253A22744%253A14%250A%2560%2560%2560

**Comment by seesemichaelj** [comment]
I more or less pulled out the application logs from the above URI:

```T+153143ms:   Runtime Error: revert%250A
T+153150ms: evm_revert%250A
T+153162ms: evm_snapshot%250A
T+153177ms: eth_blockNumber%250A
T+153182ms: eth_sendTransaction%250A
T+153241ms:   Transaction: 0xefe8cfceaa65b85b8eb122ad385adcfbd83edf560de3c5b6c7ccfc6c258f19e8%250A
T+153241ms:   Gas usage: 106932%250A
T+153241ms:   Block Number: 15%250A
T+153241ms:   Block Time: Wed Jul 04 2018 18:11:35 GM
T+0200 %28W. Europe Daylight Time%29%250A
T+153243ms: eth_getTransactionReceipt%250A
T+153250ms: eth_call%250A
T+153296ms: eth_sendTransaction%250A
T+153345ms:   Transaction: 0xb01f01a9dcb22bb04223042e252d266f2704b946c3dd2dacbfa4ac7da358dc87%250A
T+153345ms:   Gas usage: 18188%250A
T+153345ms:   Block Number: 16%250A
T+153345ms:   Block Time: Wed Jul 04 2018 18:11:35 GM
T+0200 %28W. Europe Daylight Time%29%250A
T+153348ms: eth_getTransactionReceipt%250A
T+153354ms: eth_call%250A
T+153375ms: evm_revert%250A
T+153406ms: evm_snapshot%250A
T+153420ms: eth_blockNumber%250A
T+153423ms: eth_sendTransaction%250A
T+153470ms:   Transaction: 0x16e84de8cdaa2354f5513ba3785449043870d63066070a4eab1a8568d5208542%250A
T+153470ms:   Gas usage: 23784%250A
T+153470ms:   Block Number: 15%250A
T+153470ms:   Block Time: Wed Jul 04 2018 18:11:35 GM
T+0200 %28W. Europe Daylight Time%29%250A
T+153473ms: eth_getTransactionReceipt%250A
T+153481ms: evm_revert%250A
T+153493ms: evm_snapshot%250A
T+153510ms: eth_blockNumber%250A
T+153514ms: eth_call%250A
T+153528ms: eth_sendTransaction%250A
T+153593ms:   Transaction: 0xf7c7fdf0182d3ed3b6cd80b4127a365e8891013b367f0d7988b7f098219df238%250A
T+153593ms:   Gas usage: 106932%250A
T+153593ms:   Block Number: 15%250A
T+153593ms:   Block Time: Wed Jul 04 2018 18:11:35 GM
T+0200 %28W. Europe Daylight Time%29%250A
T+153596ms: eth_getTransactionReceipt%250A
T+153602ms: eth_sendTransaction%250A
T+153657ms:   Transaction: 0x2e4bff5bf9a831442ac6f95ddb9f039ac0bd1e5d5665c7873810a22c9dd30c17%250A
T+153657ms:   Gas usage: 76932%250A
T+153657ms:   Block Number: 16%250A
T+153657ms:   Block Time: Wed Jul 04 2018 18:11:35 GM
T+0200 %28W. Europe Daylight Time%29%250A
T+153659ms: eth_getTransactionReceipt%250A
T+153665ms: eth_sendTransaction%250A
T+153724ms:   Transaction: 0xd7fb1a5ebd881f1a37e46c3fc372b66a6b7f7f0d7392b5b30ce2c866ec23e9e2%250A
T+153724ms:   Gas usage: 76932%250A
T+153724ms:   Block Number: 17%250A
T+153724ms:   Block Time: Wed Jul 04 2018 18:11:35 GM
T+0200 %28W. Europe Daylight Time%29%250A
T+153726ms: eth_getTransactionReceipt%250A
T+153732ms: eth_sendTransaction%250A
T+153793ms:   Transaction: 0xb61d22da92f7f1df52548c78147390f9ade903ee3728e3f157f5ec9176eaf46e%250A
T+153793ms:   Gas usage: 76932%250A
T+153793ms:   Block Number: 18%250A
T+153793ms:   Block Time: Wed Jul 04 2018 18:11:35 GM
T+0200 %28W. Europe Daylight Time%29%250A
T+153796ms: eth_getTransactionReceipt%250A
T+153802ms: eth_call%250A
T+153812ms: eth_sendTransaction%250A
T+153919ms:   Transaction: 0xb19ffe6cf54d963bc2cfeee4a48d6b87d86416abd7d7e3bb82352303fb9924aa%250A
T+153919ms:   Gas usage: 59260%250A
T+153919ms:   Block Number: 19%250A
T+153919ms:   Block Time: Wed Jul 04 2018 18:11:35 GM
T+0200 %28W. Europe Daylight Time%29%250A
T+153922ms: eth_getTransactionReceipt%250A
T+153927ms: eth_call%250A
T+153945ms: eth_call%250A
T+153964ms: eth_call%250A
T+153989ms: eth_call%250A
T+154007ms: C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:63898%250A
T+154007ms: var Module;if%28%21Module%29Module%253D%28typeof Module%21%253D%253D%2522undefined%2522%253FModule:null%29%257C%257C%257B%257D;var moduleOverrides%253D%257B%257D;for%28var key in Module%29%257Bif%28Module.hasOwnProperty%28key%29%29%257BmoduleOverrides%255Bkey%255D%253DModule%255Bkey%255D%257D%257Dvar ENVIRONMENT_IS_WEB%253Dfalse;var ENVIRONMENT_IS_WORKER%253Dfalse;var ENVIRONMENT_IS_NODE%253Dfalse;var ENVIRONMENT_IS_SHELL%253Dfalse;if%28Module%255B%2522ENVIRONMENT%2522%255D%29%257Bif%28Module%255B%2522ENVIRONMENT%2522%255D%253D%253D%253D%2522WEB%2522%29%257BENVIRONMENT_IS_WEB%253Dtrue%257Delse if%28Module%255B%2522ENVIRONMENT%2522%255D%253D%253D%253D%2522WORKER%2522%29%257BENVIRONMENT_IS_WORKER%253Dtrue%257Delse if%28Module%255B%2522ENVIRONMENT%2522%255D%253D%253D%253D%2522NODE%2522%29%257BENVIRONMENT_IS_NODE%253Dtrue%257Delse if%28Module%255B%2522ENVIRONMENT%2522%255D%253D%253D%253D%2522SHELL%2522%29%257BENVIRONMENT_IS_SHELL%253Dtrue%257Delse%257Bthrow new Error%28%2522The provided Module%255B'ENVIRONMENT'%255D value is not valid. It must be one of: WEB%257CWORKER%257CNODE%257CSHELL.%2522%29%257D%257Delse%257BENVIRONMENT_IS_WEB%253Dtypeof window%253D%253D%253D%2522object%2522;ENVIRONMENT_IS_WORKER%253Dtypeof importScripts%253D%253D%253D%2522function%2522;ENVIRONMENT_IS_NODE%253Dtypeof process%253D%253D%253D%2522object%2522%2526%2526%2522function%2522%253D%253D%253D%2522function%2522%2526%250A
T+154007ms: %250A
T+154007ms: TypeError: Cannot read property 'get' of undefined%250A
T+154007ms:     at dbGet %28C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56029:7%29%250A
T+154007ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17614:5%250A
T+154007ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23091:20%250A
T+154007ms:     at iterate %28C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23172:13%29%250A
T+154007ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:23184:29%250A
T+154007ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22954:16%250A
T+154007ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:17619:7%250A
T+154007ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:56034:9%250A
T+154007ms:     at dispatchError %28C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:36358:36%29%250A
T+154007ms:     at C:\Program Files\WindowsApps\Ganache_1.0.2.0_x64__zh355ej5cj694\app\resources\app\node_modules\ganache-cli\build\lib.node.js:22744:14%250A%2560%2560%2560```

The root issue you're having is being tracked in #667. Can you elaborate what you're doing when you get these errors? It'll help us fix #667

As far as the the too large URI, We'll look into what is causing the message to be too big. I'm thinking it's the part of the stack trace which kind of dumps the webpacked code since it's one large line

**Comment by seesemichaelj** [comment]
Removing just the `var Module` line wasn't enough. We'll need to cut down on the number of lines that are reported

**Comment by stoney1989** [comment]
Thanks for the fast reply!
I tried to run a truffle test suite with around 20 test cases. Before each test case, 3 smart contracts will be redeployed.  The bug doesn't occur on every run of the test suite, only about after every third or forth execution.

**Comment by benjamincburns** [comment]
@stoney1989 you're running a very old version of Ganache. Grab version v1.2.1 and don't look back - the bug causing the crashes is fixed there.

**Comment by FlashSheridan** [comment]
Just happened to me with 1.2.2 (1.2.2.24):

TypeError: Cannot read property 'pop' of undefined
    at CheckpointTrie.Trie._updateNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:360:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:107:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:461:14
    at processNode (/node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:471:23)
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:516:13
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:180:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:75:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:52:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:269:32
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:44:16
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/util.js:71:7
    at /node_modules/ganache-core/node_modules/merkle-patricia-tree/baseTrie.js:157:9
    at /node_modules/ganache-core/lib/database/levelupobjectadapter.js:30:23
    at /node_modules/ganache-core/node_modules/level-sublevel/shell.js:101:15
    at /node_modules/ganache-core/node_modules/level-sublevel/nut.js:121:19
    at /node_modules/ganache-core/node_modules/cachedown/index.js:58:21
    at ReadFileContext.callback (/node_modules/ganache-core/lib/database/filedown.js:27:14)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)

**Comment by seesemichaelj** [comment]
i opened a new issue for you @FlashSheridan
