### ISSUE TITLE
MacOs: Option 'Help/Learn More' points to a 404 page

### ISSUE THREAD

**Issue by Chococoin** [trufflesuite/ganache#839]
**MacOs: Option Help/Learn More point to a wrong URL**

The option 'help/learn more' opens a webpage of truffleframework.com in my browser but the the link is outdated. It points to 'https://truffleframework.com/suite/ganache' instead https://truffleframework.com/ganache 

## Your Environment

* Version used: Versione 1.2.1 (1.2.1)
* Operating System and version: macOs High Sierra

**Comment by seesemichaelj** [comment]
Fixed in #840; will go into the next release

Thanks again for reporting and fixing!
