### ISSUE TITLE
Set custom ETH balance

### ISSUE THREAD

**Issue by TheBojda** [trufflesuite/ganache#84]
ETH balance is 100 ETH / account now. It would be good, if balance can be set on the settings screen.

**Comment by plutoegg** [comment]
This would be an extremely useful feature - as is a huge pain to do with testrpc at the moment

**Comment by benjamincburns** [comment]
Agreed. We'll be bringing the Ganache settings UI up to speed with the newer options in `ganache-cli` soon.

**Comment by Geeroz** [comment]
Any update on the ETH balance settings UI? Is there a way to set them via cli at the moment?
Thanks

**Comment by siman** [comment]
Is it possible to connect Ganache GUI to Ganache CLI? So far I see that they don't work together :(
What I am trying to achieve: run Ganache CLI on a server in a background and connect to it with GUI on my local laptop.

**Comment by senju-dev** [comment]
+1 on this feature

**Comment by Orionarm2018** [comment]
# **I have found a method !!!**

**Just add `"default_balance_ether": 10000` to your `Settings` file, then restart Ganache, the balance will be active!!!**
![image](https://user-images.githubusercontent.com/30675228/39792503-9123205c-5373-11e8-884b-3fcdd8bf307d.png)

> 
> {
>   "googleAnalyticsTracking": false,
>   "cpuAndMemoryProfiling": false,
>   "verboseLogging": false,
>   "firstRun": false,
>   "server": {
>     "gasLimit": 9007199254740991,
>     "gasPrice": 1,
>     "hostname": "127.0.0.1",
>     "mnemonic": "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat",
>     "network_id": 5777111,
>     "port": 8545,
>     "total_accounts": 10,
>     "unlocked_accounts": [],
>     "vmErrorsOnRPCResponse": true,
>     "default_balance_ether": 10000
>   },
>   "uuid": "80483ac9-3c8b-4e78-ae77-19788197b38c"
> }
> 

In my Win10 os, the `Settings` file is here:

`D:\WpSystem\S-1-5-21-3479786796-3682928581-4074990344-8947\AppData\Local\Packages\Ganache_zh355ej5cj694\LocalCache\Roaming\Ganache\Settings`

**Ganache version : 1.1.0**

@TheBojda @plutoegg @benjamincburns @Geeroz @siman

**Comment by seesemichaelj** [comment]
This was fixed in #656; it will be in the next release (hoping for next week)
