### ISSUE TITLE
Transaction Nonce mismatch in version >= 1.2.0

### ISSUE THREAD

**Issue by mallapurbharat** [trufflesuite/ganache#841]
I'm using Ganache 1.2.0 and Metamask 4.8.0 on Ubuntu 16.04 to run my blockchain app which uses Truffle Framework and Web3. 
## Expected Behaviour
Transactions should go through without any nonce mismatch errors. NOTE: I am aware that sometimes Metamask gives an error about nonce mismatch, which is either solvable via "Reset Account" or uninstall/reinstall Metamask.

##Current Behaviour 
Just 2 days ago, I updated Ganache to 1.2.0 and shortly afterwards, I found an error while using Metamask to do transactions. 

Initially I reported this as a Metamask issue, but later on found that when I use Ganache 1.1.0, **there is no error** in transactions. So it's definitely not an issue with Metamask. I also tested this on Ganache 1.2.1 just to be sure, and even there I am facing an error.

The  problem is that my nonce in my local Ganache network is 8, after deploying my contracts. However, Metamask is having nonce 0. Hence I'm getting a nonce error (Metamask nonce: 0, Tx nonce: 8). Please see attached snapshots.

**Error details as below:**

Error: Error: Error: Error: [ethjs-rpc] rpc error with payload {"id":1424189557055,"jsonrpc":"2.0","params":["0xf8ec088501dcd65000834c4b409426081ddc1956a6fa8ac0d624759bed658d01f87480b884946be2610000000000000000000000008f756250f09c8bc2113705e7e1ca0c8b9a332e0e0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000d57696c6c79204865726d616e6e00000000000000000000000000000000000000822d45a09dd75acb1d07c3786be9eec47ea3d5eba0fee22cf19ebbce559593d41fcee39ba073578003f07988b66db1b790e2a9702f36d8ed0c20bdabe9eba60f78a125a0c3"],"method":"eth_sendRawTransaction"} Error: the tx doesn't have the correct nonce. account has nonce of: 0 tx has nonce of: 8

**Ganache after registering my contracts (8 blocks)**

![ganache_8_transactions](https://user-images.githubusercontent.com/10878214/42728758-d23fa178-87df-11e8-835a-47008f40b3cc.png)

**Error in Javascript console when I try to submit transaction using Metamask**
![js_console_error](https://user-images.githubusercontent.com/10878214/42728759-d270ff98-87df-11e8-89a1-e8e3832866a3.png)

## Possible Solution
Downgrade to Ganache 1.1.0 fixes this issue of nonce mismatch.

## Steps to Reproduce (for bugs)
I deployed my contracts to the Ganache local network. I then called a function that changes the state of the blockchain (Transaction). When I submit the transaction using Metamask, I was getting a nonce mismatch error (Metamask Nonce: 0, Tx Nonce: 8).

## Context
Was unable to proceed with development of my project as none of my transactions were getting written to the blockchain. Initially I thought it was my own code at fault, but then after eliminating all possibilities, finally zeroed in on the fact that it was some change in Ganache 1.20 (compared to 1.1.0) that was causing this issue.

## Your Environment

* Version used: Ganache 1.2.0
* Environment name and version (e.g. nodejs, metamask 4.8.0):
* Operating System and version:Ubuntu 16.04 64-bit

**Comment by seesemichaelj** [comment]
We really appreciate you taking the time to report these verbose issues! It's this kind of contribution that helps us help you! Thank you so much!

Unfortunately, I'm not sure if I have anything productive other "are you sure 1.2.1 isn't working?" Can you please triple check (follow the same steps as in #842; make sure every ganache process is stopped, start up `1.2.1`, and try again). You can make sure what version you're running by going to Settings>About. This issue (https://github.com/trufflesuite/ganache-core/issues/131) was supposedly fixed in `ganache-core@2.1.5`, `ganache-cli@6.1.6`, and `ganache@1.2.0` and is due to the same problem that causes your other open issue #842.

Thanks again!

**Comment by mallapurbharat** [comment]
Thanks for the encouragement! I wish I could help out more by helping **solve** bugs, but need some more time to understand electron, react etc enough to be able to patch code.

You were right! As you pointed out, in order to ensure that old ganache 1.2.0 instances weren't running from my earlier execution and creating an issue with 1.2.1, I clean restarted my system, ensured that no ganache processes are listed in System Monitor, and then ran 1.2.1.

 **My transactions went through without any issues!** YAY!

Just to be sure, I did the same thing without clean restarting (but ensuring that no ganache processes remain in memory), then ran 1.2.1. Again I had successful transactions!

**So, yes, it looks like 1.2.1 does have fixes for this issue.**

Thanks to this, I'll be using 1.2.1 going forward!
