### ISSUE TITLE
Attempting to run transaction which calls a contract function, but recipient address XXXXXXX is not a contract address

### ISSUE THREAD

**Issue by eliodecolli** [trufflesuite/ganache#849]
Basically I created a contract and deployed it, everything fine till that, then when I tried to call a function on the contract (which was a transaction not a call) I got that message. Even though the address that I used was the same that ganache showed me. I'm running Win10 64bit and the latest release of ganache.
My code is in Go.

**Comment by mallapurbharat** [comment]
It'd be helpful if you were to include some snapshots of the transaction view of Ganache GUI. Also some sample go code?

**Comment by eliodecolli** [comment]
Well unfortunately, I deleted my code (since I moved on other stuff), but got it working on infura, the code was the same, it just didn't work on Ganache... =\

Another thing is, does this app support ws? I needed to test events too

**Comment by davidmurdoch** [comment]
Thanks for the report, @eliodecolli! We're tracking a related issue in trufflesuite/ganache-core#117

And yes, Ganache has supported websockets and web3 1.0 pub/sub since v1.1.0 (March release).

**Comment by jobinjohnym84** [comment]
I have the same problem. Any workaround for now?  Below is the scenario-
1. Published one smart contract
2. Installed ganache cli and started
3. Wrote code to use the ganache localhost as the provider
4. Both call and send transaction is showing above error.

Detailed steps which I am following is here _  
https://medium.com/@yangnana11/interacting-with-a-smart-contract-through-web3-js-tutorial-56a7ff2ff153

Can someone help plz.

**Comment by nicholasjpaterno** [comment]
Thanks, @eliodecolli @mallapurbharat @jobinjohnym84.  We've issued a fix for this that can be found in the [develop](https://github.com/trufflesuite/ganache-core/tree/develop) branch.  This will also be included in the next release which we expect to be out this week!
