### ISSUE TITLE
Ganache launch stuck when changing port on mac

### ISSUE THREAD

**Issue by ben-kaufman** [trufflesuite/ganache#85]
Hey there, 

I just noticed when I change the port number and then click on save and restart Ganache gets stuck on the launch animation screen. Closing Ganache completely and reopening it solves the problem.
I am using Mac OS High Sierra. 

Thanks,
Ben

**Comment by melnikaite** [comment]
The same issue when change chain settings

**Comment by BenKaufman10** [comment]
It doesn't happen when I change back to the original default port.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LiveDuo** [comment]
Issue persists as of today. I am using windows 10.

**Comment by Alko89** [comment]
I can confirm the same when changing the IP here on Arch Linux.

**Comment by seesemichaelj** [comment]
This actually ended up being a duplicate of #665. We have addressed it in PR #712 and it will go into the next release
