### ISSUE TITLE
Exceeds block gas limit error to call view functions

### ISSUE THREAD

**Issue by xxorg3** [trufflesuite/ganache#853]
With solidity view function, you can specific a large number of gas to use. Since it is not a state changing transaction, all the gas cost is not charged for, and the client should be able to allow the call function to run with a gas limit larger than the block limit. 

![image](https://user-images.githubusercontent.com/7900175/43245547-0a96cb8a-90f2-11e8-9549-cbcfbdb5f20a.png)

**Comment by benjamincburns** [comment]
Issue moved to [trufflesuite/ganache-core #148](https://github.com/trufflesuite/ganache-core/issues/148) via [**ZenHub**](https://www.zenhub.com/)
