### ISSUE TITLE
[Feature] Add Clear Log Button

### ISSUE THREAD

**Issue by myspivey** [trufflesuite/ganache#865]
## Expected Behavior
Would be great to have a button the Logs view that allowed you to clear the current logs printout. This would allow for better debugging.

## Current Behavior
Currently on verbose mode when left open during dev a fair amount of logs are displayed, it would be great to have a clear button to clear this out so as you do an action you can easily figure out in the logs where that occured.

## Possible Solution
Add a "Clear Logs" button on this view.

## Context
Improving the debugging experience during development.

## Your Environment
Mac v1.2.1

**Comment by seesemichaelj** [comment]
Thanks for request! This was actually implemented in #267 and will be available in the next release!
