### ISSUE TITLE
Not enough gas when deploy a new contract of remix solidity ^0.4.22 from myEtherWallet v3.21.22 

### ISSUE THREAD

**Issue by heltian** [trufflesuite/ganache#882]
## Expected Behavior

Should succeed in deploying a contract

## Current Behavior

Using myEtherWallet 3.21.22 version, 
select contract/deploy contract
paste from bytecode the object value to Bytecode field,
select "private key", and copy private key from Ganache Eth user 1 private key, and paste in the key field,
click "Unlock",
see raw data, select "Deploy contract", 
a pop up window, select "Yes",
now see the error message "
Insufficient Funds, as the image below showed.
This error repeated multiple times. With both Solidity .22 or .24
![image](https://user-images.githubusercontent.com/42652289/44542116-87b59480-a6d1-11e8-83f6-9916bc9d049d.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by seesemichaelj** [comment]
Hi @heltian Thanks for reporting the issue. You didn't mention what version of Ganache you are using. I'm suspecting you are on 1.2.0. You can check your version in Settings>About

**Comment by heltian** [comment]
Thank you Mike for your time and helps. Now the issue resolved by Devanshu's help. I used version 1.2.1 and after updating to use custom network when deploying contract, it worked well.
