### ISSUE TITLE
How to configure hostname in the server page as another host address

### ISSUE THREAD

**Issue by amActiveHello** [trufflesuite/ganache#896]
How to configure hostname in the server page as another host address

![image](https://user-images.githubusercontent.com/11773000/45209265-1a078c00-b2bf-11e8-9f5a-af52ad388228.png)

 

## Expected Behavior
hostname config as another host , for example 172.20.22.153 ,not a host in the drop down option。

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: v1.2.2
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by seesemichaelj** [comment]
Hi! We actually removed the ability to do this in #666 and replaced it with a drop down in your network interfaces.

Ganache cannot currently be used to connect to a different RPC server. This host field is the server/ip in which to listen on, not to connect to. See my comment over at https://github.com/trufflesuite/ganache/issues/731#issuecomment-396683496 for some more details.

We have an open issue already to add the ability to connect to other RPC servers: #741

**Comment by seesemichaelj** [comment]
A more technical answer is: the host used here is passed to [server.listen](https://nodejs.org/api/net.html#net_server_listen) function which must be a host that your computer has access to, which is one of your network interfaces.
