### ISSUE TITLE
Ganache wont open or run on Ubuntu 17.10

### ISSUE THREAD

**Issue by smibbie** [trufflesuite/ganache#901]
## Expected Behavior

It should at least open. Nothing happens when attempting to run the program.

## Current Behavior

same as above

## Steps to Reproduce (for bugs)

1. Download from link on site
2. Attempt to open
3.
4.

## Context

I'm just trying to open it and it wont run at all.

## Your Environment

* Version used: 
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version: 
* Operating System and version: Ubuntu 17.10
* Link to your project:

**Comment by seesemichaelj** [comment]
Hi @smibbie! Thanks for reporting this!

You may need to add the Execute permission to the AppImage file before opening. Have you done this already? You can find more details on how to do this [here](https://howtoubuntu.org/how-to-execute-a-run-or-bin-file-in-ubuntu), but the gist is:
- Open a terminal, navigate to the folder, and run `chmod +x ganache-1.2.2-x86_64.AppImage`
- or you can right click on the file in the file browser, Click Properties, go to the Permissions tab, check the box that says "Allow executing file as program" (or something of the like)

This is pretty typical for AppImage files

Let me know if this helps or not! Thanks!

**Comment by smibbie** [comment]
awesome! worked perfectly. Thank you!

**Comment by leeboss82** [comment]
Hello, I'm still having trouble running this.  I've executed the permission as described above both in the browser and in the terminal, and still nothing happens when I try to run.
