### ISSUE TITLE
Problems with positioning in GUI.

### ISSUE THREAD

**Issue by reducio** [trufflesuite/ganache#908]
Problems with positioning in GUI.

![image](https://user-images.githubusercontent.com/6662917/45684452-11c90f80-bb4f-11e8-96b4-e81900b74929.png)

OS: macOS Sierra 10.13.6 (17G65)
Ganache: v1.2.2
Display: 13 inches.

**Comment by DiscRiskandBisque** [comment]
Closing because after testing this appears to be fixed in `2.0.0-beta.2`.
