### ISSUE TITLE
Error: Returned error: sender doesn't have enough funds to send tx. The upfront cost is: 2000000000000000 and the sender's account only has: 0

### ISSUE THREAD

**Issue by djneely** [trufflesuite/ganache#918]
Ganache 1.2.2.24

Signing a transaction I'm getting the above error. The gas is set to 20000. If I log the balance of the account before doing the transaction I'm seeing that the address has 99782508800000000000

 

## Expected Behavior

Hoping the transaction would go through.

## Current Behavior

The current issue is that the sender doesn't have enough funds to send tx.

## Steps to Reproduce (for bugs)

1. Use web3 to sign a transaction.
2.
3.
4.

## Context

Trying to build an application for a project of ours.

## Your Environment

* Version used: 1.2.2.24
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
Web3, VueJS
* Server type and version:
* Operating System and version: Mac
* Link to your project:

**Comment by djneely** [comment]
Also attempted this over on: Ganache CLI v6.1.3 (ganache-core: 2.1.2) And seeing the same error.

**Comment by djneely** [comment]
Follow up. Upgraded ganache-cli: Ganache CLI v6.1.8 (ganache-core: 2.2.1) and the issue is gone. Still seeing the issue in ganache which I believe is the latest and greatest 1.2.2.24

**Comment by seesemichaelj** [comment]
This is peculiar as ganache @ 1.2.2 should be using ganache-core 2.2.1

This could be fixed when we release the next Ganache version

**Comment by davidmurdoch** [comment]
This may be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Can you let me know if you have any issues or if this update doesn't solve the issue for you?

**Comment by SirPhemmiey** [comment]
I am still having the same issue on `Ganache-CLI: v6.6.0 (ganache-core: 2.7.0)`

**Comment by mwaeckerlin** [comment]
I've got thesame problem:
> Ganache CLI v6.7.0 (ganache-core: 2.8.0)

```
     Error: Returned error: sender doesn't have enough funds to send tx. The upfront cost is: 134439500001000000 and the sender's account only has: 0
     at PromiEvent (node_modules/truffle/build/webpack:/packages/contract/lib/promievent.js:6:1)                                                              
      at TruffleContract.deploy (node_modules/truffle/build/webpack:/packages/contract/lib/execute.js:158:1)                                                  
      at Context.it (test/2_AssociationMinimumTest.js:20:28)                                                                                                  
```

**Comment by SirPhemmiey** [comment]
@mwaeckerlin , while using Ganache can you reconfirm if you're using the free account addresses provided by the ganache CLI/GUI? 

Because the issue could occur if you use any account address not associated with Ganache. And the reason is because you're still local and Ganache doesn't recognize that address (without private key) that you're using to transact.
