### ISSUE TITLE
Feature: Parse contract call tx data into function+args

### ISSUE THREAD

**Issue by craustin** [trufflesuite/ganache#93]
It would be useful to see what calls (function name and passed args) are being sent by our dapp. If Ganache allowed us to point it at our Truffle-generated contract wrappers, it should have all the info it needs to parse the tx data.

**Comment by seesemichaelj** [comment]
We implemented this feature in the upcoming version 2.0.

This is enabled with a new feature called Workspaces where you can link your Truffle projects to get contract state awareness.

If you want to get notified when 2.0 is released, you should checkout Github's new "watch Releases Only option":
![image](https://user-images.githubusercontent.com/549323/49690518-85503c80-fb00-11e8-8104-a954e0410525.png)
You'll get notified when new releases are made if you select that `Releases Only` option. The auto updater should also notify you when a release is ready too!
