### ISSUE TITLE
Create an eslint configuration to help contributors

### ISSUE THREAD

**Issue by maxme** [trufflesuite/ganache#935]
I started to make some contributions to my fork of this repo, but I noticed the style was not consistent. 

You should have an eslint config with your style defined so contributors would just have to setup their editor to use it or lint/reformat on commit.

**Comment by seesemichaelj** [comment]
Thanks @maxme! We started on this a week or so but got pushed due to TruffleCon; we'll be sure to get this soon. It helps us too since we are growing a lot and need some consistency between the team.

**Comment by maxme** [comment]
Perfect, I'll wait for it and use mine in the meantime.

**Comment by eshaben** [comment]
ESLint configuration has been added to `ganache-core`!
