### ISSUE TITLE
Feature: Contract state explorer

### ISSUE THREAD

**Issue by craustin** [trufflesuite/ganache#95]
It would be very helpful to have another tab ("CONTRACTS"?) that allows us to view the public (and private?) state of a contract - as-of any block. This would greatly aid in debugging.

**Comment by seesemichaelj** [comment]
We implemented this feature in the upcoming version 2.0. The first 2.0.0 release will only show you the contract state at the latest block. I'll create a new issue for exploring past blocks!

If you want to get notified when 2.0 is released, you should checkout Github's new "watch Releases Only option":
![image](https://user-images.githubusercontent.com/549323/49690518-85503c80-fb00-11e8-8104-a954e0410525.png)
You'll get notified when new releases are made if you select that `Releases Only` option. The auto updater should also notify you when a release is ready too!
