### ISSUE TITLE
Ganache UI Server Settings page Automine button issues.

### ISSUE THREAD

**Issue by balexander4** [trufflesuite/ganache#955]
Automine button is not triggering Save/Restart , once Automine is toggled it can't be undone.

 

## Steps to Reproduce (for bugs)
1. In any session go to the Server Settings page and try to toggle Automine on/off
2. Observe Restart behavior
3. Observe behavior once Automine toggle has been changed once.

## Context
Trying to change all settings to make sure they are all functioning and savable. 

## Your Environment

* Version used:Ganache 2.0.0 beta
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version: Apache
* Operating System and version: Mac iOS High Sierra 10.13.6

**Comment by seesemichaelj** [comment]
Fixed in https://github.com/trufflesuite/ganache/commit/47d03ac83a0f9b13e3d54ab14e55b96606475890
