### ISSUE TITLE
Delegatecall is not working at ganache

### ISSUE THREAD

**Issue by JeanoLee** [trufflesuite/ganache#962]
I tested the delegatecall by linking the remix IDE with ganache.
However, the return value for delegatecall is 0 in ganache, so I can not get the correct result. At first I thought that the delegatecall call method was wrong, but after testing it on Ropsten testnet, it returned the correct value without any problem.

Does Ganache have no support for delegate calls?
I would like to know how the EVM context works in a delegatecall.

**Comment by davidmurdoch** [comment]
Thanks for filing this issue, @JeanoLee. What version of solidity are you using? Can you provide a link to a minimal viable reproduction?

**Comment by davidmurdoch** [comment]
This should be fixed in our latest beta: https://github.com/trufflesuite/ganache/releases/tag/v2.0.1-beta.0 Can you let me know if you have any issues or if this update doesn't solve the issue for you?
