### ISSUE TITLE
Gas Price not updating on main UI screen after changing and saving in settings.

### ISSUE THREAD

**Issue by balexander4** [trufflesuite/ganache#963]
## Expected Behavior

Changing the Gas Price in the setting should update on the main Ganache UI, it does not, after the Gas Price has been cached it will not longer update on the main page. 

## Steps to Reproduce (for bugs)

1.Note the Gas Price that is set on main page
2.Go to Settings and change Gas Price
3.Save/Restart Navigate back to main page
4.View the Gas Price to see if it has updated. 
5.Navigate back to the settings page, the changes should have been saved. 

-I also noticed that it will revert back to the previously set Gas Price after appearing to save the new price.

## Your Environment

* Version used:2.0.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: ios and windows, tested and occurring on both
* Link to your project:

**Comment by seesemichaelj** [comment]
I found an issue with numbers not being parsed properly, and this should affect the price as well, but doesn't come apparent in the tests that I was doing earlier
