### ISSUE TITLE
Updating Total Accounts to generate sets the Eth Balance at 0.

### ISSUE THREAD

**Issue by balexander4** [trufflesuite/ganache#967]
Changing the Total number of accounts adds on the new accounts, but any new accounts have Eth set at 0 instead of what the set account balance is set to. 

## Expected Behavior

It's expected that any new accounts would take the set Eth Balance. Instead it just displays 0.

## Steps to Reproduce (for bugs)

1.View set Account Balance on Main screen and in the settings
2.Change the set number of accounts and save/restart
3.View that new accounts have been created, but the Eth Balance is at 0.

## Your Environment

* Version used:2.0.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: mac ios high sierra and windows 10
* Link to your project:

**Comment by seesemichaelj** [comment]
Fixed in 166d08d
