### ISSUE TITLE
Adding a truffle contract that is not compiled to Ganache appears to be able to attach but does not, on darwin.

### ISSUE THREAD

**Issue by balexander4** [trufflesuite/ganache#970]
Adding a truffle contract that is unconfigured to Ganache appears to be able to attach but does not, on darwin.

## Expected Behavior

Selecting a contract in a workspace that is not compiled appears to attach but once saved and restarted does not appear. 

## Possible Solution

Where and when does Ganache realize that the contracts are or are not compiled?

## Steps to Reproduce (for bugs)

1.Open an existing workspace or start a new one.
2.Attach a project to Ganache you know is not compiled.
3.The project appears to be selectable. Save/Restart.
4.The project will not attach and no results are visible in Ganache.

## Your Environment

* Version used:2.0.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: 
* Link to your project:

**Comment by seesemichaelj** [comment]
This has been fixed with the introduction of the `projectFsWatcher.js` file
