### ISSUE TITLE
Ganache -cli local running storage logs

### ISSUE THREAD

**Issue by akash1936** [trufflesuite/ganache#970]
When we run ganache-cli on our local, then whatever the logs are being created on the console are saved in our storage and we can't able to find that logs or storage part?

Is it happening with someone else as well?

**Comment by kevinbluer** [comment]
Hey @akash1936 aware this was raised over a year ago, but to confirm are you requesting for the console output / stdout to be optionally written to disk?

**Comment by haltman-at** [comment]
OK, we're going to close this for issue maintenance, but @akaash1936 please feel free to get back to us with more details and we can look into this.  Thanks!
