### ISSUE TITLE
Ganache will allow you to attach multiple projects but error occurs

### ISSUE THREAD

**Issue by balexander4** [trufflesuite/ganache#971]
Ganache will allow you to attach multiple projects but will not function and will hang when trying to reopen projects that have 3 or more projects attached.

 

## Expected Behavior

Attaching multiple projects would function and be visible in Ganache as the work flow appears to do. 

## Current Behavior

Currently adding any more then 2 small contracts will cause Ganache to hang and you can not reenter those workspaces through the UI after you have added 3 or more. 

## Steps to Reproduce (for bugs)

1.Add 3 or more projects to any workspace.
2.Save/Restart
3.If Ganache hangs and fails with command line error, restart
4.Try opening the same project after restarting Ganache UI 
5.Ganache then hangs and fails again.

## Your Environment

* Version used:2.0.0
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version: iOS/High Sierra, Windows 10
* Link to your project:

**Comment by seesemichaelj** [comment]
This has been fixed through a slew of different commits for supporting multiple projects better.
