### ISSUE TITLE
Should fail when trying to create an instance of an abstract contract (solc 0.6)

### ISSUE THREAD

**Issue by elenadimitrova** [trufflesuite/ganache#971]
## Expected Behavior
Creating an abstract contract should fail.

## Current Behavior
Returns an address for created contract but calls to that contract fail.

Sorry for not being too detailed with this issue submissions but I'm assuming it's easy to reproduce and might even be that Solidity 0.6 features aren't yet implemented.

## Your Environment
* Version used: Ganache CLI v6.9.1 (ganache-core: 2.10.2)
* Version of Truffle/Remix/Other tools used: using `etherlime` for compilation and deployment
* NodeJS Version: v10.12.0
* Operating System and version (include distro if Linux): OSX Catalina

**Comment by kevinbluer** [comment]
Hey @elenadimitrova, super sorry for the delay in getting to this! Not sure if this is still an issue but we're not sure if it's actually a Ganache bug. Through a brief bit of testing we can confirm that both Truffle and Remix handle this case with custom error messaging. For reference Solidity compiles abstract contracts to empty bytecode which the EVM allows.

Let us know if you want to dig into this more.

**Comment by haltman-at** [comment]
Hi @elenadimitrova do you have any more details about this?  Sorry, we just came across this old issue and weren't sure what to do about it; we're not entirely sure whether there's a real issue here or not but I think we need a little more information.  Do you still know the details here?  Thanks!

**Comment by elenadimitrova** [comment]
I've long forgotten this and not sure if it's still an issue, but basically if you have an abstract contract say

```
abstract contract Test {
  function doSomething() public view virtual returns (bool);
}
```
you should not be able to instantiate it in a test, e.g. via `await Test.new()` but iirc this was successful.

**Comment by haltman-at** [comment]
Hm, that's odd.  That shouldn't work.  I'll try this out later and see if I can reproduce it on latest Truffle/Ganache.  Thanks!

**Comment by haltman-at** [comment]
OK, I couldn't reproduce this with latest Truffle/Ganache.  I got an error as expected:

```
  1) Contract: Test
       should deploy successfully (not really):
     Error: Test error: contract binary not set. Can't deploy new instance.
This contract may be abstract, not implement an abstract parent's methods completely
or not invoke an inherited contract's constructor correctly

      at Function.new (/home/sniffnoy/truffle/truffle/packages/contract/lib/contract/constructorMethods.js:48:13)
      at Context.<anonymous> (test/test.js:5:19)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Is it OK if we close this, then?
