### ISSUE TITLE
accidentally transferred ether into mainnet with ganache generated mnemonic

### ISSUE THREAD

**Issue by billtlee** [trufflesuite/ganache#974]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 5.4 on nginx 1.9.1):
* Server type and version:
* Operating System and version:
* Link to your project:

**Comment by billtlee** [comment]
Hi, I accidentally transferred some ether into an account with mnemonic generated with ganache.  It was randomly generated, not the original "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat".  It's one that I generated randomly.  Has it been automatically sweep into an account?  The ether ended up in this account:
0xF2D00E3080E1D9Fd5E47F54188434E24CFe54Da2

Is there anyway I can get the ether back?  If not, then how did this account get the fund?  Can people access my ganache accounts even though I generated the accounts with a random mnemonic?

**Comment by seesemichaelj** [comment]
@billtlee, sorry you're having issues.

Is there any more information you can provide for me to help? A couple of quest

**Comment by billtlee** [comment]
hi @seesemichaelj 
Thanks for getting back.  The is the originate transaction:
https://etherscan.io/address/0x93d06abf524be323a812bf0426a22bf48c04f8db
Then
https://etherscan.io/address/0x8fcae66ca2565966f5be02ef6e09c3f821f4e9df
Then
https://etherscan.io/address/0xf2d00e3080e1d9fd5e47f54188434e24cfe54da2

The mnemonic was created using Ganache GUI.

Are any of these accounts own by you guys?

**Comment by davidmurdoch** [comment]
@billtlee we do not own any of these accounts, sorry. Do you still have the mnemonic (don't paste it here, of course)?

**Comment by billtlee** [comment]
Yes I do.

Sent from my iPhone

On 22 Nov 2018, at 9:44 AM, David Murdoch <notifications@github.com<mailto:notifications@github.com>> wrote:


@billtlee<https://github.com/billtlee> we do not own any of these accounts, sorry. Do you still have the mnemonic (don't paste it here, of course)?

**Comment by benjamincburns** [comment]
Hi @billtlee,

I'm afraid there is nothing we can do here to help you, but there _might_ be something _you_ can do.

If you're using a newer version of Ganache (>= v1.1.0) your mnemonic is randomly generated and stored to a config file on your machine. This means that the mnemonic you used was unique to you, and if you never shared it with anyone, posted it online, etc, then the ETH _should_ still be in the destination account.

If the ETH is still in the account that you sent it to, and if that account was generated from your mnemonic, you can use MetaMask to recover the eth. You'll need to restore MetaMask with the mnemonic that Ganache gave you. If the account you sent funds to wasn't the first account in the list, use the add account feature to get the account to be shown in MetaMask. That is, if the account you sent funds to was the 5th account in the list in Ganache, you'll need to add four automatically generated accounts in MetaMask to get the destination account to appear. At that point, if you're connected to mainnet with MetaMask, you should see a balance for the account which received your funds, and you should be able to send those funds back to your account.

Finally, to help encourage the MetaMask team to implement a feature that will prevent others from making this same mistake, please share your experience here: https://github.com/MetaMask/metamask-extension/issues/3131
