### ISSUE TITLE
Upgrade to ethereumjs-vm 2.5.0 for Constantinople support

### ISSUE THREAD

**Issue by axic** [trufflesuite/ganache#976]
The VM has a new API, it is possible to specify a hard fork: https://github.com/ethereumjs/ethereumjs-vm/blob/master/docs/index.md#vm

It would be nice to expose this option in Ganache.

cc @holgerd77

**Comment by davidmurdoch** [comment]
Thanks @axic. This is currently blocked by https://github.com/trufflesuite/ganache-core/pull/230, but we'll be sure to update Ganache as soon as we can merge it in to core.

p.s., any chance we could get the open [keccakjs](https://github.com/axic/keccakjs/pull/6) and [scrypt.js](https://github.com/axic/scrypt.js/pull/3) PRs merged and published soon? (the keccakjs PR will also need the `sha3` dep moved to over to `optionalDependencies`).
