### ISSUE TITLE
Ganache CLI broken in Windows 10

### ISSUE THREAD

**Issue by dipdatta** [trufflesuite/ganache#978]
* I asked about this on [gitter](https://gitter.im/ConsenSys/truffle): [ X]
* Link to my question on gitter: https://gitter.im/ConsenSys/truffle?at=5ed9c7f3f0b8a2053ad558b4

## Expected Behavior

After successful installation of Ganach-cli, the command should run

## Current Behavior
Installed Ganach-cli in a windows 10 machine different way (through NPM or Yarn, using both normal & elavated powershell). In every case, it throws error:
 
_Ganache CLI v6.9.1 (ganache-core: 2.10.2)
Error: EPERM: operation not permitted, rename 'C:\Users\XXX\AppData\Local\Temp\tmp-105308sZYl4zzSwXKN_tmp\tmp-105308AyFqxhFh77oY' -> 'C:\Users\XXX\AppData\Local\Temp\tmp-105308sZYl4zzSwXKN!trie_db!0x5911f24d96912350de50f297c2d34d5d10e136757bf4cfff5fa41bfca219554a'_ 

I tried running the command from WSL console (using same windows installation/binary) & it runs fine.

**CLI Installation log**
_PS C:\home\Developement> yarn global add ganache-cli
yarn global v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "ganache-cli@6.9.1" with binaries:
      - ganache-cli
Done in 50.42s._ 

**Node versions**
_PS C:\home\Developement> node --version
v12.18.0
PS C:\home\Developement> npm --version
6.14.4
PS C:\home\Developement> yarn --version
1.22.4_

## Possible Solution

Since same ganache-cli binary fails to run in windows but runs fine on linux console (WSL), it seems like the issue is with non-standard filename (which is rejected by windows but ok for linux)

## Steps to Reproduce (for bugs)

1. Install nodejs, npm & Yarn
2. Install ganachi-cli through npm or Yarn (tried both)
3. Invoke ganache-cli (tried both normal PS & elavated PS)
4. Cli doesn't run & throw error

## Context
The windows build seems broken & non functional

## Your Environment
* Version used: latest
* Version of Truffle/Remix/Other tools used: NA
* NodeJS Version: [ ] 6.x, [ ] 7.x (unsupported), [ ] 8.x, [ ] 9.x : 12.18.0
* Operating System and version (include distro if Linux): Windows 10 enterprise
* Link to your project or repro gist:
* Commit hash to use with above link for reproduction:
* I intend to submit a pull request to fix this issue: [ ]

**Comment by kevinbluer** [comment]
Closing this as "wont-fix" given it's a problem with `npm` (or `yarn`) and Windows Defender. Also for reference, we've experienced this internally and usually it's resolved by re-running `npm install` and / or turning off Defender temporarily.

Sorry for the inconvenience and any future related challenges, feel free to open a new issue.

**Comment by peadenjd** [comment]
How do you temporarily disable windows defender firewall for installation purposes?

**Comment by peadenjd** [comment]
> )

where can I go to download older versions?
