### ISSUE TITLE
Event parsing error when multiple events with the same name.

### ISSUE THREAD

**Issue by MoMannn** [trufflesuite/ganache#989]
This is linked to https://github.com/trufflesuite/truffle/issues/2449 which should be fixed.

Any plan on fixing this?

**Comment by samuelfrench** [comment]
Hope we can get this fixed. I'm getting a `Warning: Could not decode event!` error:
```
Truffle v5.4.10 (core: 5.4.10)
Solidity - 0.6.12 (solc-js)
Node v16.3.0
Web3.js v1.5.2

**Comment by leeftk** [comment]
Hey @samuelfrench could you file a [new issue](https://github.com/trufflesuite/truffle/issues/new) for this on the Truffle repository and provide more information so that we can get started on it. We're going to close this for now because this is a Truffle issue rather than a Ganache issue. Thanks!
