### ISSUE TITLE
Using an existing DB results in ganache lying about accounts and balances.

### ISSUE THREAD

**Issue by MicahZoltu** [trufflesuite/ganache#992]
First run ganache-cli with a mnemonic and a db path.
```
npx ganache-cli --db "./db" --mnemonic "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo wrong"
```
Exit and then run again without a mnemonic, but with the same db path:
```
npx ganache-cli --db "./db"
```
- Notice that the accounts listed in the startup splash are different between runs.
- Notice that the second run indicates each account has 100 ETH balance.
- Notice that if you call `eth_accounts` against the second run it will list the accounts using the random mnemonic.
- Notice that if you call `eth_getBalance` against any of the accounts listed by the second run you will get a `0` balance (different from what startup splash shows)
- Notice that if you call `eth_getBalance` against the accounts from the first run you will see 100 ETH balance.

## Expected Behavior
Accounts and balances correctly listed by splash screen and `eth_accounts` RPC when using an existing DB.

## Current Behavior
The accounts/balances listed do not match the splash screen.

## Possible Solution
I _think_ the right solution here is to have the splash screen show the actual balances rather than assuming the accounts have a balance.

Another option would be to store the original mnemonic with the DB files so that it can be used in subsequent runs.

If the first solution is chosen, it would be good to display a warning to the user that an existing DB is being used and the original mnemonic is unknown, thus the original accounts cannot be referenced.

**Comment by dongmingh** [comment]
Thanks for reporting this bug and we will address this bug in #1030. Closing this as duplicate.
