### ISSUE TITLE
Incorrect hex encoding of transaction input

### ISSUE THREAD

**Issue by sabondano** [trufflesuite/ganache#997]
`eth_getTransactionByHash` returns invalid `DATA` type for a transaction's input field. For details please see: https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding

## Expected Behavior
A transaction's `input` should be encoded as hex, prefixed with "0x", and two hex digits per byte.

Examples:
* no bytes = `0x`
* 1 zero byte = `0x00`

## Current Behavior
`input` of `0x0` is an invalid `DATA` type.

```
{
"id": 617862604210,
"jsonrpc": "2.0",
"result": {
"hash": "0x196ff86dee5781d3e6d574ccaa8c298fd6751faa6af8c06913e729efa1293394",
"nonce": "0x0",
"blockHash": "0x272146d809e6d9dd44c97f6561afcdfa0f7fa24ae8da705e64647f37e362e9bf",
"blockNumber": "0x01",
"transactionIndex": "0x00",
"from": "0x97cfe4e81ba0549b177eb7c28504015de986d715",
"to": "0x30870f4b5b7458c9a4ca3ad3b72a033359ceddf2",
"value": "0x0de0b6b3a7640000",
"gas": "0x5208",
"gasPrice": "0xee6b2800",
"input": "0x0",
"v": "0x2d46",
"r": "0x50a1fa44d0e61ce0ce96521c4c997b973601b3adbfcf9de3f3cc9fd3b3d5b7d7",
"s": "0x6298294d0626bca0c4942f906e611be9145641c9bae7dfcf61552900b4965010"
}
}
```

## Steps to Reproduce (for bugs)
1. Run almost any truffle based code that performs transactions
2.
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["<insert hash here>"],"id":1}'  -H "Content-Type: application/json" -X POST localhost:7545
```

**Comment by davidmurdoch** [comment]
Thanks for filing the issue, @sabondana!

This should be fixed in the next release of Ganache, as it's already been fixed in ganache-core and ganache-cli. We're just fixing a few bugs introduced into the latest version of core and will release a new Ganache as soon as these fixes are fully tested. Thanks again!

**Comment by eshaben** [comment]
Closing this as the fix has been made and will be released in the next version of Ganache!
