### ISSUE TITLE
Performance regression in ganache-cli > 6.4.5

### ISSUE THREAD

**Issue by alcuadrado** [trufflesuite/ganache#999]
I found a big performance regression in ganache-cli > 6.4.5. Some RPC requests are taking up to 19 seconds to finish. Most of them are `eth_call` calls, but sometimes `net_version` ones also get stuck.

## Expected Behavior

Ganache > 6.4.5 should have around the same performance than 6.4.5.

## Current Behavior

Some requests take much much longer.

## Steps to Reproduce (for bugs)

1. Clone this repo in that particular version: https://github.com/clovers-network/clovers-contracts/tree/53036b6d462c6e440a9e71360cd4fcf4ad49faed 
2. Install ganache-cli ` 6.4.5`.
3. Run the repo tests against ganache. Take note of the time spent by each test.
4. Install a newer ganache-cli, say ` 6.7.0`.
3. Run the repo tests against ganache. Take note of the time spent by each test. Some of them will be much larger.

## Your Environment
* Version used: 6.4.5, 6.5.1, 6.6.0, 6.7.0
* Version of Truffle/Remix/Other tools used: Truffle v4.1.13, Buidler 1.0.0-beta.10
* NodeJS Version: v8.16.0
* Operating System and version (include distro if Linux): MacOS 10.14.6 (18G87)
* Link to your project or repro gist: https://github.com/clovers-network/clovers-contracts/tree/53036b6d462c6e440a9e71360cd4fcf4ad49faed
* Commit hash to use with above link for reproduction: 53036b6d462c6e440a9e71360cd4fcf4ad49faed
* I intend to submit a pull request to fix this issue: [ ]

**Comment by dongmingh** [comment]
This issue is fixed in ganache@7.0.0-alpha.1.  Please open a new issue if you see the issue in ganache@7.0.0-alpha.1. Thanks for raising the issue!
